### ISSUE TITLE
Add text over AreaChart

### ISSUE THREAD

**Issue by Neha3011** [JesperLekland/react-native-svg-charts#103]
### What is the problem?
I want to add Text/label over the areachart region. But when I add Text from react-native-svg to the decorators method, the app crashes without error. If I remove it, the app works fine. I am looking to generate something like this:
<img width="261" alt="screen shot 2018-04-05 at 7 29 56 pm" src="https://user-images.githubusercontent.com/10024090/38370472-ca145c5e-3907-11e8-82c2-4431705f67b2.png">

* [x] iOS 
* [ ] Android 

Versions:
"react-native": "0.52.0",
"react-native-svg": "^6.3.1",
"react-native-svg-charts": "^4.2.0",

### Code to reproduce

```javascript
// put code here
import React from 'react';
import { Path, Circle, Line, G, Text } from 'react-native-svg'
import { AreaChart } from 'react-native-svg-charts'
import * as shape from 'd3-shape'

const Chart = props => (
    <AreaChart
        style={{height: 100}}
        showGrid={false}
        data={props.item}
        contentInset={{top: 30, bottom: 30}}
        curve={shape.curveNatural}
        svg={{fill: '#BFE5EC'}}
        renderDecorator={({ x, y, index, value }) => (
            <G key={index}>
              <Circle
                  style={{ zIndex: 10}}
                  cx={x(index)}
                  cy={y(value)}
                  r={4}
                  strokeWidth={2}
                  stroke={'#20AAC3'}
                  fill="white"
              />
              <Line
                  x1={x(index)}
                  y1={"250"}
                  x2={x(index)}
                  stroke="#BFE5EC"
                  strokeWidth="0.3"
              />
              <Text
                  stroke="#383834"
                  fontSize="12"
                  x={50}
                  y={50}
                  textAnchor="middle"
              >Test</Text>
            </G>
        )}
        extras={[
          ({line}) => (
              <Path
                  key={'line'}
                  d={line}
                  strokeWidth={2}
                  stroke={'#20AAC3'}
                  fill={'none'}
              />
          ),
        ]}
    />
);

export default Chart;
```

**Comment by JesperLekland** [comment]
"Crashing without an error" isn't possible, check the native logs for a stack trace

**Comment by Neha3011** [comment]
Hey @JesperLekland Thanks for responding. I am using Xcode simulator to run this code which is run using command react-native-scripts ios. When the Expo closes, there is no stack trace on the terminal. I tried to find a way to find the stack trace, but I am unable to.

**Comment by Neha3011** [comment]
Hey @JesperLekland Thanks for responding. I am using Xcode Expo simulator to run this code which is run using command react-native-scripts ios. When the app closes, there is no stack trace on the terminal or JS debugger. I tried to find a way to find the stack trace, but I am unable to.

**Comment by JesperLekland** [comment]
Ugh, I hate Expo... I'll try to run your example when I get the chance and see if I can find what's going on

**Comment by Neha3011** [comment]
Hey @JesperLekland, I was able to get system logs.
`Apr  9 19:22:57 Nehas-MacBook-Pro-4 systemsoundserver-simd[1231]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
Apr  9 19:22:58 Nehas-MacBook-Pro-4 Exponent[1228]: -[__NSArrayM floatValue]: unrecognized selector sent to instance 0x60000104e640
Apr  9 19:22:58 Nehas-MacBook-Pro-4 Exponent[1228]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM floatValue]: unrecognized selector sent to instance 0x60000104e640'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x000000010fca8b0b __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x000000010f071141 objc_exception_throw + 48
		2   CoreFoundation                      0x000000010fd18134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
		3   CoreFoundation                      0x000000010fc2f840 ___forwarding___ + 1024
		4   CoreFoundation                      0x000000010fc2f3b8 _CF_forwarding_prep_0 + 120
		5   Exponent                            0x000000010526dd81 +[ABI25_0_0RNSVGPercentageConverter stringToFloat:relative:offset:] + 130
		6   Exponent                            0x0000000105265b61 -[ABI25_0_0RNSVGGlyphContext pushContext:deltaX:deltaY:positionX:positionY:] + 150
		7   Exponent                            0x0000000105272ff6 -[ABI25_0_0RNSVGText pushGlyphContext] + 234
		8   Exponent                            0x0000000105272a92 -[ABI25_0_0RNSVGText getGroupPath:] + 36
		9   Exponent                            0x0000000105272906 -[ABI25_0_0RNSVGText renderLayerTo:] + 80
		10  Exponent                            0x000000010526f687 -[ABI25_0_0RNSVGRenderable renderTo:] + 166
		11  Exponent                            0x0000000105266b62 __37-[ABI25_0_0RNSVGGroup renderGroupTo:]_block_invoke + 178
		12  Exponent                            0x0000000105269968 -[ABI25_0_0RNSVGNode traverseSubviews:] + 285
		13  Exponent                            0x0000000105266a86 -[ABI25_0_0RNSVGGroup renderGroupTo:] + 147
		14  Exponent                            0x000000010526f687 -[ABI25_0_0RNSVGRenderable renderTo:] + 166
		15  Exponent                            0x000000010527144b -[ABI25_0_0RNSVGSvgView drawRect:] + 1371
		16  UIKit                               0x000000010ccd4d45 -[UIView(CALayerDelegate) drawLayer:inContext:] + 489
		17  QuartzCore                          0x000000010c748500 -[CALayer drawInContext:] + 257
		18  QuartzCore                          0x000000010c65eae5 CABackingStoreUpdate_ + 2505
		19  QuartzCore                          0x000000010c7480fa ___ZN2CA5Layer8display_Ev_block_invoke + 61
		20  QuartzCore                          0x000000010c747df3 _ZN2CA5Layer8display_Ev + 1633
		21  QuartzCore                          0x000000010c73c31d _ZN2CA5Layer17display_if_neededEPNS_11TransactionE + 315
		22  QuartzCore                          0x000000010c73c3ab _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 35
		23  QuartzCore                          0x000000010c6cbe92 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 294
		24  QuartzCore                          0x000000010c6f8130 _ZN2CA11Transaction6commitEv + 468
		25  QuartzCore                          0x000000010c6f8b37 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 115
		26  CoreFoundation                      0x000000010fc4e717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
		27  CoreFoundation                      0x000000010fc4e687 __CFRunLoopDoObservers + 391
		28  CoreFoundation                      0x000000010fc33720 __CFRunLoopRun + 1200
		29  CoreFoundation                      0x000000010fc33016 CFRunLoopRunSpecific + 406
		30  GraphicsServices                    0x00000001118eda24 GSEventRunModal + 62
		31  UIKit                               0x000000010cc12134 UIApplicationMain + 159
		32  Exponent                            0x0000000104796381 main + 80
		33  libdyld.dylib                       0x00000001108b465d start + 1
		34  ???                                 0x0000000000000001 0x0 + 1
	)
Apr  9 19:22:58 Nehas-MacBook-Pro-4 SpringBoard[1118]: UNSUserNotificationServerConnectionListener connection invalidated
Apr  9 19:22:58 Nehas-MacBook-Pro-4 SpringBoard[1118]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
Apr  9 19:22:58 Nehas-MacBook-Pro-4 com.apple.CoreSimulator.SimDevice.546035E3-A3DA-43CF-8FDB-BEEC204C51DD.launchd_sim[1098] (UIKitApplication:host.exp.Exponent[0x167d][1123][1228]): Service exited due to Abort trap: 6
Apr  9 19:22:58 Nehas-MacBook-Pro-4 backboardd[1119]: [Common] Unable to get short BSD proc info for 1228: No such process
Apr  9 19:22:58 Nehas-MacBook-Pro-4 backboardd[1119]: [Common] Unable to get proc info for 1228: Undefined error: 0
Apr  9 19:22:58 Nehas-MacBook-Pro-4 com.apple.CoreSimulator.SimDevice.546035E3-A3DA-43CF-8FDB-BEEC204C51DD.launchd_sim[1098] (com.apple.WebKit.Networking.A6635D8B-76CE-4148-A57C-1B2D9B9D0420[1229]): Service exited with abnormal code: 1
Apr  9 19:22:58 Nehas-MacBook-Pro-4 com.apple.CoreSimulator.SimDevice.546035E3-A3DA-43CF-8FDB-BEEC204C51DD.launchd_sim[1098] (com.apple.WebKit.WebContent.A7D86D2E-1831-4AFB-B239-0F47ED69A547[1230]): Service exited with abnormal code: 1
Apr  9 19:22:59 Nehas-MacBook-Pro-4 systemsoundserver-simd[1231]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
Apr  9 19:23:03 --- last message repeated 1 time ---
Apr  9 19:23:03 Nehas-MacBook-Pro-4 assertiond[1123]: Deleted job with label: UIKitApplication:host.exp.Exponent[0x167d][1123]
Apr  9 19:23:03 Nehas-MacBook-Pro-4 watchlistd[1185]: Now playing app did change to '(null)' (playing: 0) from '(null)'
Apr  9 19:23:03 Nehas-MacBook-Pro-4 watchlistd[1185]: WLKPlaybackSummary - Parameter failed validation bundleID. It is nil
Apr  9 19:23:03 Nehas-MacBook-Pro-4 systemsoundserver-simd[1231]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
Apr  9 19:23:33 --- last message repeated 14 times ---
Apr  9 19:23:33 Nehas-MacBook-Pro-4 systemsoundserver-simd[1231]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
Apr  9 19:23:44 --- last message repeated 5 times ---
Apr  9 19:23:44 Nehas-MacBook-Pro-4 routined[1106]: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
Apr  9 19:23:45 Nehas-MacBook-Pro-4 systemsoundserver-simd[1231]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
`

**Comment by Neha3011** [comment]
@JesperLekland That doesn't work either. :( I will find a work around. Thanks.
