### ISSUE TITLE
Scale Domain is not a function

### ISSUE THREAD

**Issue by kenvandemar** [JesperLekland/react-native-svg-charts#105]
I'm trying to implement scale with domain and range like this: 

<YAxis
              data={yAxisLeft}
              svg={{
                fill: 'grey',
                fontSize: 10,
                scale: 1,
              }}
              contentInset={{left: 10, top: 10, bottom: 20}}
            d3.scaleLinear()
            .domain([10, 130])
           .range([0, 960])
             />
But it raises err: scale(...).domain is not a function. I install 'd3-scale' already

<img width="422" alt="screen shot 2018-04-12 at 9 57 03 am" src="https://user-images.githubusercontent.com/8335788/38654155-1ae56bac-3e38-11e8-9ca4-4fd1b490c9a9.png">

**Comment by JesperLekland** [comment]
Your code is not complete. Please provide a minimum code example to reproduce

**Comment by kenvandemar** [comment]
Oh sorry. Here is my code

import React from 'react'
import {
  AppRegistry,
  StyleSheet,
  
  View, 
  processColor,
  FlatList,
  TouchableOpacity,
} from 'react-native'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'

import { LineChart, YAxis, XAxis } from 'react-native-svg-charts'
import { Circle, G, Text, Line, Rect, Polygon, TSpan } from 'react-native-svg'
import moment from 'moment'

import {Header} from '../components/Header'
import { fetchGraphData } from '../modules/userMetrics.module'
import ActivePeriod from './ActivePeriod'

import { getActiveItem } from '../actions/graph.action'
import Constant from '../constant'
import * as scale from 'd3-scale'

class Graph extends React.Component {

  static navigationOptions = {
    header: null,
  }

  constructor() {
    super()
    this.state = {
      periods: [
        {time: '7days'},
        {time: '31days'},
        {time: '90days'},
        {time: '180days'},
        {time: '365days'},
        {time: '3 years'},
      ],
      dayRange: [],
      periodRange: [],
      showToolTip: false,
      showToolTipBodyFat: false,
      toolTipX: null,
      toolTipY: null,
      toolTipBFX: null,
      toolTipBFY: null,

    }
  }

  componentDidMount() {
    this.props.getActiveItem(this.state.periods[0])
    for (let i = 0; i < 7; i++) {
      const day7 = moment().add(i, 'days').format('llll')
      this.state.dayRange.push(day7)
      this.setState({
        dayRange: this.state.dayRange,
      })
    }
    console.log('CHEcK DATA', this.state.dayRange)
  }

  renderDayRange(number) {
  }
  renderItem(item) {
    const periodItem = item.item
    const index = item.index
    return (
      <TouchableOpacity
        onPress={() => {
          this.props.getActiveItem(periodItem)

          switch (periodItem.time) {
            case '7days':
              this.renderDayRange(7)
              break
            case '31days':
              console.log('HELLO')
              break
            case '90days':
              console.log('HELLO')
              break
            case '180days':
              console.log('HELLO')
              break
            case '365days':
              console.log('HELLO')
              break
            case '3 years':
              console.log('HI')
              break
            
            default:
              break
          }
        }}
      >
        <ActivePeriod 
          periodItem={periodItem}
          index={index}
        />
      </TouchableOpacity>
    )
  }
  renderPeriod() {
    return(
      <View 
        style={{
          flexDirection: 'row',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        {
          this.state.dayRange.map((item, index) => {
            let itemFormat = item
            itemFormat =  String(itemFormat).substring(-1, 11)
            itemFormat = String(itemFormat).slice(-2)
            const dayRangeText = (
              <Text key={index}>{itemFormat}</Text>
            )
            return dayRangeText
          })
        }
      </View>
    )
  }
  render() {
    const { theme } = this.props
    const xData = [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec' ]
    const yAxisLeft = [ 46, 47, 48, 49, 50, 51, 52, 53]
    const yAxisRight = [21, 22, 23, 24, 25 ,26, 27, 28]

    const weightData = [51, 50.3, 51.5, 51.2, 51, 50.9, 50.8, 51.1]
    const bodyFatData = [23.3, 22.5, 23.9, 22.65, 22.6, 23, 23.7]

    const contentInset = { top: 5, bottom: 20, right: 10 }

    const minText = ({ x, y }) => (
      <G
        x={x(1)}
        y={y(weightData[1]) + 25}
      >
        <Text
          stroke="none"
          fontSize="20"
          fill={'rgb(246, 195, 217)'}
          fontWeight="normal"
          textAnchor="middle" 
        >Min</Text>
      </G>
    )
   
    const maxText = ({ x, y }) => (
      <G
        x={x(2) + 3}
        y={y(weightData[2]) - 12}
      >
        <Text
          stroke="none"
          fontSize="20"
          fill={'rgb(246, 195, 217)'}
          fontWeight="normal"
          textAnchor="middle" 
        >Max</Text>
      </G>
    )
    const TooltipWeight = ({ x, y, index, value }) => {
      const toolTip = this.state.showToolTip ? (
        <G
          x={this.state.toolTipX - 58}
          y={this.state.toolTipY - 110}
          key={ 'tooltip' }
          
        >
          <Rect
            height={80}
            width={120}
            stroke={null}
            fill={'rgb(246, 195, 217)'}
            ry={10}
            rx={10}
            onPress={() => {this.setState({showToolTip: !this.state.showToolTip})}}
          />
          <Text
            x={ 75 / 2 }
            dy={20}
            
            stroke={null}
            fill={'#fff'}
          >
            <TSpan x="30">2018/3/34</TSpan>
            <TSpan x="25" dx="10" dy="15" fontWeight="bold" fontSize="15">50.9kg</TSpan>
            
            <TSpan x="5" dx="0" dy="15">BMI 19.2 BF 22.5%</TSpan>
            <TSpan x="10" dx="10" dy="15">-0.4kg +0.3%</TSpan>
          </Text>
          
          <Polygon
            points="26,30 53,30 40,55" 
            fill={'rgb(246, 195, 217)'}
            stroke={null}
            strokeWidth="0"
            x={18}
            y={48}
          />
        </G>
      ) : null
      return toolTip
    }
    const TooltipBodyFat = ({ x, y, index, value }) => {
      const toolTip = this.state.showToolTipBodyFat ? (
        <G
          x={this.state.toolTipBFX - 58}
          y={this.state.toolTipBFY - 110}
          key={ 'tooltip' }
          
        >
          <Rect
            height={80}
            width={120}
            stroke={null}
            fill={'rgb(137, 212, 247)'}
            ry={10}
            rx={10}
            onPress={() => {this.setState({showToolTipBodyFat: !this.state.showToolTipBodyFat})}}
          />
          <Text
            x={ 75 / 2 }
            dy={20}
            
            stroke={null}
            fill={'#fff'}
          >
            <TSpan x="30">2018/3/34</TSpan>
            <TSpan x="25" dx="10" dy="15" fontWeight="bold" fontSize="15">50.9kg</TSpan>
            
            <TSpan x="5" dx="0" dy="15">BMI 19.2 BF 22.5%</TSpan>
            <TSpan x="10" dx="10" dy="15">-0.4kg +0.3%</TSpan>
          </Text>
          
          <Polygon
            points="26,30 53,30 40,55" 
            fill={'rgb(137, 212, 247)'}
            stroke={null}
            strokeWidth="0"
            x={18}
            y={48}
          />
        </G>
      ) : null
      return toolTip
    }

    return (
         
      <View style={{flex: 1}}>
        <Header
          text={'GOAL INFO'}
          navigation={this.props.navigation}
          hasActionButton={false}
          style={{backgroundColor: theme.primaryColor}}
        />
        <View style={{flex: 1, backgroundColor: '#fff'}}>
          <View>
            <FlatList
              style={{
                marginTop: 10,
                alignSelf: 'center',
              }}
              data={this.state.periods}
              renderItem={this.renderItem.bind(this)}
              keyExtractor={(item, index) => `key-${item}-${index}`}
              horizontal={true}
            />
          </View>
         
          <View style={{ 
            height: 250, 
            flexDirection: 'row', 
            marginLeft: 10, 
            width: '100%',
            alignItems: 'center',
            marginTop: 80,
          }}>
          
            <YAxis
              data={weightData}
              svg={{
                fill: 'grey',
                fontSize: 10,
                scale: 1,
              }}
              contentInset={{left: 10, top: 10, bottom: 10}}
              formatLabel={ (value, index) => value}
            />
          
            <LineChart
              style={{ width: '80%', height: 220}}
              data={weightData}
              svg={{ 
                stroke: 'rgb(246, 195, 217)',
                strokeWidth: 3,
              }}
              contentInset={{left: 10, top: 25, bottom: 140, right: 10}}
              showGrid={false}
              renderDecorator={({ x, y, index, value }) => {
                const decorator = (
                  <G key={index}>
                    <Circle
                      key={index}
                      cx={x(index)}
                      cy={y(value)}
                      r={6}
                      fill={'rgb(246, 195, 217)'}
                      onPress={() => {
                        this.setState({
                          showToolTip: !this.state.showToolTip,
                          toolTipX: x(index),
                          toolTipY: y(weightData[index]),
                        })
                      }}
                    />
                    
                  </G>
                )
                return decorator
              }}
              extras={[   
                minText,
                maxText,
                TooltipWeight,
              ]}
            />
             
            <LineChart
              style={{position: 'absolute',width: '80%', height: 220, top: 90, left: 10, right: 10 }}
              data={bodyFatData}
              svg={{ 
                stroke: 'rgb(137, 212, 247)',
                strokeWidth: 3,
              }}
              contentInset={{left: 10, top: 20, bottom: 150, right: 10}}
              showGrid={false}
              renderDecorator={({ x, y, index, value }) => {
                const decorator = (
                  <G key={index}>
                    <Circle
                      key={index}
                      cx={x(index)}
                      cy={y(value)}
                      r={6}
                      fill={'rgb(137, 212, 247)'}
                      onPress={() => {
                        this.setState({
                          showToolTipBodyFat: !this.state.showToolTipBodyFat,
                          toolTipBFX: x(index),
                          toolTipBFY: y(bodyFatData[index]),
                        })
                      }}
                    />
                  </G>
                )
                return decorator
              }}
              extras={[   
                TooltipBodyFat,
              ]}
            />
            <YAxis
              contentInset={{left: 10, top: 10, bottom: 10}}
              data={bodyFatData}
              svg={{
                fill: 'grey',
                fontSize: 10,
                scale: 1,
              }}
              
            />
          </View>  
          <XAxis 
            style={styles.xAxis}
            data={[5, 4, 5]}
            contentInset={{ left: 10, right: 10 }}
            svg={{ 
              fontSize: 12,
              fontStyle: 'italic',
            }}
            formatLabel={(value) => {
              console.log('VALUE', value)
              return value
            }}
            xAcessor={ ({ value }) => {
              console.log('VALUE', value)
              return value
            } }
          />
          <View>
            {
              this.renderPeriod()
            }
          </View>
        </View>
      </View>
         
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  xAxis: {
    paddingHorizontal: 20,
    marginTop: 30,
    backgroundColor: 'rgb(254, 249, 250)',
    paddingTop: 15,
    paddingBottom: 10,
    borderTopColor: 'rgb(189, 189, 192)',
    borderTopWidth: 1,
    borderLeftColor: 'rgb(189, 189, 192)',
    borderLeftWidth: 1,
    borderRightColor: 'rgb(189, 189, 192)',
    borderRightWidth: 1,
    borderStyle: 'solid',
  },
})
const mapStateToProps = (state) => {
  return {
    theme: state.theme.themeStore,
  }
}
const mapDispatchToProps = dispatch => {
  return bindActionCreators(
    {
      fetchGraphData,
      getActiveItem,
    },
    dispatch
  )
}

export default connect(mapStateToProps, mapDispatchToProps)(Graph)

**Comment by JesperLekland** [comment]
Please format correctly and try to keep your example to a minimum. I won't bother with to big examples
