### ISSUE TITLE
Progress Circle progress direction bug

### ISSUE THREAD

**Issue by hansen94** [JesperLekland/react-native-svg-charts#110]
### What is the problem?

When progress circle have progress more than 50%, the circle is filled clockwise. But when progress is less than 50%, circle is filled counter-clockwise.

### When does it happen?

Set progress to 0.4
Set progress to 0.7
### What platform?

* [x] iOS 
* [x] Android 

React Native version: 0.52

### Code to reproduce
import React from 'react'
import { ProgressCircle } from 'react-native-svg-charts'

class ProgressCircleExample extends React.PureComponent {

    render() {

        return (
            <ProgressCircle
                style={ { height: 200 } }
                progress={ 0.7 }
                progressColor={ 'rgb(134, 65, 244)' }
                { ...this.props }
            />
        )
    }

}

export default ProgressCircleExample

Screenshot:
![screenshot_1523592967](https://user-images.githubusercontent.com/8460050/38716845-22ea902c-3f0d-11e8-877e-3618d8b24a4e.png)
![screenshot_1523592998](https://user-images.githubusercontent.com/8460050/38716851-27756c70-3f0d-11e8-8e51-293b6d196baf.png)

**Comment by JesperLekland** [comment]
I'll have a look!
