### ISSUE TITLE
Render Grid on top of the chart

### ISSUE THREAD

**Issue by Amnesthesia** [JesperLekland/react-native-svg-charts#111]
### What is the problem?
<Grid /> is rendered beneath the chart right now, which might make sense for some charts, but if you want the grid lines to be visible on top of an AreaChart or StackedAreaChart, you're forced to go with a fill with opacity.

### What platform?

* [X] iOS 
* [X] Android 

React Native version: 0.52.2

It would be nice to allow a prop that makes the <Grid /> stuff be put after the Chart SVG in the AreaChart / StackedAreaChart components :-) 

If possible, it would also be nice to have the option to render the YAxis labels *on* the lines (right now, the lines and the text seem to get slightly offset, where the text moves up just ever so slightly for each row). We can pass the `svg` prop to the rendered SVGText, but this wont let us modify any X/Y values to add any offset

**Comment by JesperLekland** [comment]
Released in 5.0.0. Render your chart with a `Grid` as a child and set prop `belowChart={false}` on the grid.

**Comment by Amnesthesia** [comment]
Hmm — would be really nice with some more documentation on `StackedAreaChart.extractDataPoints` — if I have two keys, every second value is 0 (although no values are 0 in the graph). When I pass `data` and `yAccessor` as usual, I get a completely different scale, and the scale is really off it seems. Digging through the code, I'm still not sure how `extractDataPoints` works, and what I should pass to it to fix it

**Comment by JesperLekland** [comment]
@Amnesthesia Please open another issue for that.
