### ISSUE TITLE
Trying to build a gauge

### ISSUE THREAD

**Issue by davidck** [JesperLekland/react-native-svg-charts#114]
### What is the problem?
Trying to build a gauge using the `PieCharts` or `ProgressCircle`.
Similar to: https://github.com/Reggino/react-svg-gauge

Are there plans to support a start and end angle similar to what `ProgressCircle` does?
It doesn't seem possible with the current version, I'm using `ProgressCircle` right now, but the edges of the active area is rounded giving a unwanted effect.

See screenshot:
<img width="349" alt="screen shot 2018-04-17 at 6 45 48 pm" src="https://user-images.githubusercontent.com/135805/38902711-b0d70784-426f-11e8-89dd-9bdee8a95072.png">

React Native version: 0.55.3

**Comment by JesperLekland** [comment]
Hi! 

So basically you want what you have but without the rounded edges? I'll see what I can do

**Comment by davidck** [comment]
Yes! Also, there is an empty space that makes the full `ProgressCircle`.  If there is a way to reduce the height or use the full height, then it'll be perfect.

If not, then I'll probably have to wrap another `View` over it and `overflow:'hidden'` it.

**Comment by JesperLekland** [comment]
The empty issue was discussed [here](https://github.com/JesperLekland/react-native-svg-charts/issues/71).

**Comment by aalhaimi** [comment]
I'm also trying to do something similar but with ```PieChart```.. I  need to make multiple sections, but don't want to keep the chart as a complete circle. If you can extend the ```startAngle``` and ```endAngle``` just like in the d3.js PieChart that would be great!
