### ISSUE TITLE
Some of examples are not working or not updated to v5.0.0

### ISSUE THREAD

**Issue by seriiix** [JesperLekland/react-native-svg-charts#119]
For example this chart is not shown as expected: [horizontal-with-labels.js
](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/horizontal-with-labels.js)And this one is not updated to v5.0.0: [vertical-with-labels.js
](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/vertical-with-labels.js)

**Comment by seriiix** [comment]
[horizontal-with-labels.js
](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/horizontal-with-labels.js)issue is gone after downgrading `react-native-svg` to **`6.2.2`**

**Comment by JesperLekland** [comment]
@seriiix Thanks for trouble shooting. What version of `react-native-svg` didn't work?

**Comment by seriiix** [comment]
`6.3.1`

**Comment by vishrut** [comment]
@JesperLekland Thanks for creating and maintaining this library.

Experienced the same issue as @seriiix and downgrading react-native-svg to 6.2.2 fixed it too.

**Comment by JesperLekland** [comment]
Interesting that it doesn't work for you guys on 6.3.1, it worked just fine for me
