### ISSUE TITLE
Error: Activity class {com.rnsvgcharts/com.rnsvgcharts.MainActivity} does not exist." and 'websocket: connection error', 'Failed to connect to localhost/127.0.0.1:7008'

### ISSUE THREAD

**Issue by ajmalpkc** [JesperLekland/react-native-svg-charts#12]
"Starting: Intent { cmp=com.rnsvgcharts/.MainActivity }
Error type 3
Error: Activity class {com.rnsvgcharts/com.rnsvgcharts.MainActivity} does not exist."

**Comment by JesperLekland** [comment]
@ajmalpkc The error message actually happens after the build and installation, it's just that `react-native run-android` fails to launch the intent (start the app). If you look in your emulator the app will be installed and will launch just fine when clicked

**Comment by ajmalpkc** [comment]
In Android Storybook got error `'websocket: connection error', 'Failed to connect to localhost/127.0.0.1:7008'` and was fixed by running command `adb reverse tcp:7008 tcp:7008` in terminal and reloading the app

**Comment by JesperLekland** [comment]
@ajmalpkc I'm assuming you got it to work as you closes the issue?

**Comment by ajmalpkc** [comment]
Yes, Worked Fine. Great Work @JesperLekland

**Comment by geomih** [comment]
@JesperLekland The reason for 
```
Error type 3
Error: Activity class {com.rnsvgcharts/com.rnsvgcharts.MainActivity} does not exist."
``` 

is because in ``` android/app/build.gradle ``` you have set ``` applicationId "com.rnsvgcharts.app" ``` but it should be ``` applicationId "com.rnsvgcharts" ``` as described [here](https://github.com/facebook/react-native/issues/14952#issuecomment-314683712).
