### ISSUE TITLE
Is it possible to draw a chart like this using this library

### ISSUE THREAD

**Issue by MohithHasan** [JesperLekland/react-native-svg-charts#121]
![capture](https://user-images.githubusercontent.com/34531234/39085840-8efa2fae-45aa-11e8-8d46-a63419b98a63.PNG)

**Comment by msevestre** [comment]
Check this example out:
https://github.com/JesperLekland/react-native-svg-charts/blob/5fce49fc1e902939cb063440a6a01cf09b537556/storybook/stories/partial-chart/line-chart.js

**Comment by MohithHasan** [comment]
sir after running above code provided in the link  i got output like this :
![screen shot 2018-04-22 at 11 57 22 am](https://user-images.githubusercontent.com/34531234/39092003-08a4fb3a-4624-11e8-847d-ec28d28bd12c.png)

**Comment by MohithHasan** [comment]
found the problem!!! I was using react-native-svg-chartsv5.0.0 but 
and  react-native-svg latest release which is 6.3.1
but in package.json file of react-native-svg-chartsv5.0.0 I found that it was using "react-native-svg": "^6.2.1",
so it was not working
so i installed react-native-svg6.2.1 ,
now it is working !!
and running below code:
import React from 'react'
import { ClipPath, Defs, Rect,Line } from 'react-native-svg'
import { LineChart, Path ,XAxis,YAxis} from 'react-native-svg-charts'
import {View} from 'react-native'
import * as shape from 'd3-shape'
const heightGrap = 200
const contentInset = { top: 20, bottom: 20 }
class PartialLineChartExample extends React.PureComponent {

    render() {

        const data = [ 50, 10, 40, 95, -4, -24, 85, 91, 35, 53, -53, 24, 50, -20, -80 ]
        const DataLabel = ["6.00","12.00","18.00","0.00","6.00"]
        let max =-1000
        let min = 1000
        for(let i = 0; i < data.length; i++){
            if(max < data[i])
            {
                max = data[i]
            }
            if(min > data[i])
            {
                min =data[i]
            }
        }
        if(min<0)
        {
            min = min *(-1)
        }
        const totalLength=(max+min)

        const indexToClipFrom = 10
        const limitLineValue = 28
        let upperColorLimitValueInNumber = ((heightGrap/totalLength)*(max-limitLineValue))/2
        let upperColorLimit = upperColorLimitValueInNumber.toString()+"%"
        const Clips = ({ x, width }) => (
            <Defs key={ 'clips' }>
                <ClipPath id="clip-path-1">
                    <Rect x={ '0' } y={ '0' } width={ width} height={ '100%' }/>
                </ClipPath>
                <ClipPath id={ 'clip-path-2' }>
                    <Rect x={ x(0) } y={ '0' } width={width } height={ upperColorLimit }/>
                </ClipPath>
            </Defs>
        )
        const HorizontalLine = (({ y }) => (
          <Line
              key={ 'zero-axis' }
              x1={ '0%' }
              x2={ '100%' }
              y1={ y(limitLineValue) }
              y2={ y(limitLineValue) }
              stroke={ 'grey' }
              strokeDasharray={ [ 4, 8 ] }
              strokeWidth={ 2 }
          />
      ))
        // Line extras:
        const DashedLine = ({ line }) => (
            <Path
                key={ 'line-1' }
                d={ line }
                stroke={ 'red' }
                strokeWidth={ 2 }
                fill={ 'none' }
                strokeDasharray={ [ 4, 0 ] }
                clipPath={ 'url(#clip-path-2)' }
            />
        )

        const Shadow = ({ line }) => (
            <Path
                y={ 3 }
                key={ 'shadow-1' }
                d={ line }
                stroke={ 'rgba(134, 65, 244, 0.2)' }
                strokeWidth={ 5 }
                fill={ 'none' }
            />
        )

        return (
          <View style={{ height: 400 ,padding:20}}>
            <View style={{flexDirection:'row'}}>
              <YAxis
                      data={ data }
                      contentInset={ contentInset }
                      svg={{
                          fill: 'grey',
                          fontSize: 10,
                      }}
                      numberOfTicks={ 10 }
                      formatLabel={ value => `${value} -` }
                  />
              <LineChart
                  style={{ height: 200,width:300,left:10 }}
                  data={ data }
                  contentInset={{ top: 20, bottom: 20 }}
                  svg={{
                      stroke: 'rgb(134, 65, 244)',
                      strokeWidth: 2,
                      clipPath: 'url(#clip-path-1)',
                  }}
                  curve={ shape.curveMonotoneX }
              >
                  <Clips/>
                  <HorizontalLine/>
                  <DashedLine/>
              </LineChart>
            </View>
            <XAxis
                    style={{ marginHorizontal: -10 }}
                    data={ DataLabel }
                    xAccessor={({ value }) => value}
                    formatLabel={(value) => value }
                    contentInset={{ left: 10, right: 10 }}
                    svg={{ fontSize: 10, fill: 'black' }}
                />
            </View>
        )
    }
}

export default PartialLineChartExample


# I got ouput like this # :
![screen shot 2018-04-23 at 7 59 06 pm](https://user-images.githubusercontent.com/34531234/39131093-713acde8-4730-11e8-90a3-a16c403ca28e.png)

but Xaxis label is not showing!!!!
i want  to show xAxis label like this:
![lal](https://user-images.githubusercontent.com/34531234/39131538-790cc764-4731-11e8-9da4-97ed092c85e7.PNG)
How to do it can you please help me??

**Comment by vyshakh** [comment]
<img width="323" alt="graph realtime" src="https://user-images.githubusercontent.com/2608067/74869865-32178200-5372-11ea-962e-629b08e74b26.png">

```
/**
 *  Real time graph
 */

import React, {Component} from 'react';
import {StyleSheet, View, Text, StatusBar} from 'react-native';
import {LineChart, Grid, YAxis, XAxis, Path} from 'react-native-svg-charts';
import {ClipPath, Defs, Rect, Line} from 'react-native-svg';

const Clips = ({x, y, indexToClipFrom, height, bountry}) => {
  return (
    <Defs key={'clips'}>
      <ClipPath id="clip-path-1">
        <Rect x={'0'} y={'0'} width={x(indexToClipFrom) - 2} height={'100%'} />
      </ClipPath>
      <ClipPath id="clip-path-2">
        <Rect
          x={'0'}
          y={'0'}
          width={x(indexToClipFrom) - 2}
          height={y(bountry)}
        />
      </ClipPath>
    </Defs>
  );
};

const RedDashedLine = ({y, bountry}) => (
  <Line
    x1="0"
    y1={y(bountry)}
    x2="100%"
    y2={y(bountry)}
    stroke="red"
    strokeWidth="2"
    strokeDasharray={[4, 4]}
  />
);

const LineRealTime = ({line}) => (
  <Path
    key={'line-1'}
    d={line}
    stroke={'red'}
    strokeWidth={2}
    fill={'none'}
    clipPath={'url(#clip-path-2)'}
  />
);

const RealTimeLineGraph = props => {
  const {yaxisData, indexToClipFrom, bountry, yMax} = props;
  const contentInset = {top: 20, bottom: 20};
  return (
    <View style={{flex: 1}}>
      <View style={{height: 200, flexDirection: 'row'}}>
        <YAxis
          data={yaxisData}
          contentInset={contentInset}
          svg={{
            fill: 'grey',
            fontSize: 10,
          }}
          formatLabel={value => `${value}`}
        />

        <LineChart
          style={{flex: 1, marginLeft: 16}}
          yMin={0}
          yMax={yMax}
          data={yaxisData}
          svg={{
            stroke: 'green',
            strokeWidth: 2,
            clipPath: 'url(#clip-path-1)',
          }}
          contentInset={contentInset}>
          <Grid />
          <Clips indexToClipFrom={indexToClipFrom} bountry={bountry} />
          <LineRealTime />
          <RedDashedLine bountry={bountry} />
        </LineChart>
      </View>
    </View>
  );
};

class App extends Component {
  max = 150;
  bountry = 80;
  timer;
  constructor(props) {
    super(props);
    const yaxisData = Array.from(Array(this.max).keys()).map(() => {
      return 0;
    });

    this.state = {yaxisData, counter: 0};
  }

  componentDidMount() {
    this.timer = setInterval(() => {
      const {yaxisData, counter} = this.state;
      if (yaxisData.length > this.max) {
        clearInterval(this.timer);
        return;
      }
      yaxisData[counter] = this.getRandomInt(this.max);
      this.setState({yaxisData, counter: counter + 1});
    }, 300);
  }

  componentWillUnmount() {
    if (this.timer) {
      clearInterval(this.timer);
    }
  }

  getRandomInt = max => {
    return Math.floor(Math.random() * Math.floor(this.max));
  };

  render() {
    return (
      <View style={{flex: 1, padding: 20}}>
        <RealTimeLineGraph
          yaxisData={this.state.yaxisData}
          indexToClipFrom={this.state.counter - 1}
          bountry={this.bountry}
          yMax={this.max}
        />
      </View>
    );
  }
}

export default App;



```
