### ISSUE TITLE
How to limit the number of bar to be shown?

### ISSUE THREAD

**Issue by anjusr** [JesperLekland/react-native-svg-charts#126]
If there is large amount of values to display, I want to limit it to some particular value. So that screen should display the limited bar while scrolling next value can be seen. Now its looking congested if more number of values are there.

![interactive-stacked-chart-plugin-with-jquery-css3-barchart](https://user-images.githubusercontent.com/10432081/39244666-f3ed1e10-48ae-11e8-9019-055c8a64f08c.jpg)

I want something like this . So that while scrolling prev/ next date value's can be seen not all together.

**Comment by JesperLekland** [comment]
Then just add your Chart as a child to a horizontal scrollview and set the chart's width to something appropriate 👍

**Comment by anjusr** [comment]
Thanks for the answer. It did solve my problem 😀 
but value just above the bar . I don't know why its not displaying for me.
I have written as per your example in  renderDecorator={Labels}

**Comment by JesperLekland** [comment]
`renderDecorator` is no longer a prop in 5.0.0, please see the examples repo and the README for more info. 

PS. The stacked charts have some parts missing for proper decorator support. Use [this] issue to track the Stacked charts progress. Closing this issue as the original issue has been solved

**Comment by guptavishesh143** [comment]
> If there is large amount of values to display, I want to limit it to some particular value. So that screen should display the limited bar while scrolling next value can be seen. Now its looking congested if more number of values are there.
> 
> ![interactive-stacked-chart-plugin-with-jquery-css3-barchart](https://user-images.githubusercontent.com/10432081/39244666-f3ed1e10-48ae-11e8-9019-055c8a64f08c.jpg)
> 
> I want something like this . So that while scrolling prev/ next date value's can be seen not all together.

hey Can you share your code please, In my case my graph disappears





``<ScrollView horizontal={true}>
                  <BarChart
                    style={{height: 180, paddingHorizontal: 40}}
                    data={data}
                    svg={{fill}}
                    // numberOfTicks={90}
                    contentInset={{top: 30, bottom: 30, Right: 10}}
                    showValuesOnTopOfBars={true}
                    yAxisLabel={'jhihji'}
                    spacingInner={0.8}>
                    <Grid />
                    {/* spacingOuter={0.7} */}
                  </BarChart>
                </ScrollView>``
