### ISSUE TITLE
No ViewManager defined for class RNSVGGroup

### ISSUE THREAD

**Issue by Rajat421** [JesperLekland/react-native-svg-charts#13]
React-native v0.45.1
react-native-svg version v 5.2.0

**Comment by JesperLekland** [comment]
@Rajat421 I'm going to need a bit more help than that. 
* What is your problem? 
* When does it happen?
* What platform?
* Code to reproduce

**Comment by JesperLekland** [comment]
I'll go ahead and close this due to inactivity. Please reopen with more detail if problem persists
