### ISSUE TITLE
React Native SVG Charts for Windows (UWP)

### ISSUE THREAD

**Issue by Danushka50** [JesperLekland/react-native-svg-charts#132]
### What is the problem?

Does it support for UWP

### When does it happen?

Applied that to the UWP

### What platform?

* [ ] Windows 

React Native version: 0.53.3

### Stacktrace (if crash)

![windows error in charts](https://user-images.githubusercontent.com/19383469/39471488-10bb8c6e-4d61-11e8-90ce-e524f43c600f.PNG)

**Comment by JesperLekland** [comment]
Does react-native-svg work with Windows? I don't think it does and as such is not an issue with this library.
