### ISSUE TITLE
LineChart Gradient

### ISSUE THREAD

**Issue by bangersandflash** [JesperLekland/react-native-svg-charts#133]
### What is the problem?
I can't seem to get a LineChart to display with a gradient.

The code below renders the line chart with a red stroke instead of a gradient.

### What platform?

Android API 27

"react-native": "0.54.2",
"react-native-svg": "^6.3.1",
"react-native-svg-charts": "^5.0.0",

### Code to reproduce
const Gradient = () => (
            
              <LinearGradient id="lineGradient" x1={'0'} y={'0%'} x2={'100%'} y2={'100%'}>
                <Stop offset={'0%'} stopColor={'green'}/>
                <Stop offset={'100%'} stopColor={'blue'}/>
              </LinearGradient>
            
          )

                        <LineChart
                            style={{ height: 100, position: 'absolute', top: 0, width: 1200 }}
                            data={data}
                            showGrid={false}
                            svg={{ stroke: '#ff0000', strokeWidth: 2, }}
                            
                        >
                            <Gradient />

**Comment by JesperLekland** [comment]
Try downgrading to `react-native-svg@6.2.2`. We've had reports of broken compatibility with rn-svg 6.3.*

**Comment by bangersandflash** [comment]
Thanks @JesperLekland 

Ive downgraded but still no luck. Does the code above look like it should work? I'm new to the library so I may not have implemented the gradient correctly.

**Comment by JesperLekland** [comment]
ah I didn't even look at the code, sorry! No you need to reference the gradient in the `svg` prop of the LineChart. Check the [examples repo](https://github.com/JesperLekland/react-native-svg-charts-examples) for inspiration. Closing this as it's not really an issue :)
