### ISSUE TITLE
How to draw a chart like this???

### ISSUE THREAD

**Issue by MohithHasan** [JesperLekland/react-native-svg-charts#134]
![svgcircle](https://user-images.githubusercontent.com/34531234/39621869-0d40b3d6-4fb2-11e8-90db-38893112c132.PNG)

**Comment by JesperLekland** [comment]
Not supported at the moment. At most you could get the outer circle without the gradient

**Comment by JesperLekland** [comment]
Closing as this is not really an issue, and way to specific to be considered a feature request
