### ISSUE TITLE
YAxis labels are cut off

### ISSUE THREAD

**Issue by axelkennedal** [JesperLekland/react-native-svg-charts#139]
### What is the problem?
The YAxis labels are not fully displayed, they are cut off both at the left and right side.

![Screenshot](https://user-images.githubusercontent.com/8863787/40149046-9d6e5bca-5971-11e8-8f67-aed0cd746e18.png)

### When does it happen?
When attempting to make a simple Line Chart with a YAxis.

### What platform?
* [ ] iOS 
* [x] Android 7

React Native version: 0.55.4

### Code to reproduce

```javascript
import React, { Component } from 'react';
import {
    Platform,
    StyleSheet,
    Text,
    View
} from 'react-native';

import { AreaChart, LineChart, Grid, YAxis } from "react-native-svg-charts";
import * as shape from 'd3-shape';

export default class App extends Component {
    render() {

        const data = [ 1945, 1960, 1980, 2010, 1995, 2024]

        const contentInset = { top: 20, bottom: 20 }

        return (
            <View style={{ height: 200, flexDirection: 'row', margin: 20}}>
                <YAxis
                    style={{padding: 10}}
                    data={ data }
                    svg={{
                        fill: 'grey',
                        fontSize: 16,
                        padding: 20
                    }}
                    numberOfTicks={ 10 }
                    formatLabel={ value => `${value} SR` }
                />
                <LineChart
                    style={{ flex: 1, marginLeft: 16 }}
                    data={ data }
                    curve={ shape.curveNatural }
                    svg={{ stroke: 'rgba(134, 65, 244, 0.8)', strokeWidth: 2}}
                >
                </LineChart>
            </View>
        )
    }
}
```

**Comment by JesperLekland** [comment]
Try to remove the `padding` on the YAxis `svg` prop and use a regular `horizontalMargin` on the `style` prop instead. Will allow the axis to measure itself more accurately.  Feel free to reopen issue if this didn't solve the problem

**Comment by JesperLekland** [comment]
On closer inspection the `padding: 10` on the YAxis will ruin the layout of the axis anyway, it must have the same height (inner) as the chart (how else would it layout it's labels?). The padding on the YAxis labels don't make much sense either, they're spaced based on the data, nothing else. If you need horizontal spacing use some sort of horizontalMargin, either on the axis or on the chart 👍

**Comment by axelkennedal** [comment]
I tried removing padding both from the `svg` prop and the `style` prop of YAxis, and it looks the same, the issue persists.

I can't reopen the issue since I don't have the proper rights for it.

**Comment by JesperLekland** [comment]
What version of this library are you using? I can't recreate with the above code

**Comment by mikerodham** [comment]
I'm also facing the same issue using the above code, my labels look exactly the same as above. Padding, horizontalmargin all are having no effect. Did this issue ever get properly solved? I just need the labels to be able to be wider and the graph smaller but no matter what size of the graph, the labels never get any bigger.

**Comment by mikerodham** [comment]
Here's how I've solved it: `formatLabel={ value => ' ' + ` ${value} Items ` + ' ' }` where previously I would see `item` with half the of the M cut off, adding in these extra spaces made it render correctly.

**Comment by dskusuma** [comment]
> Here's how I've solved it: `formatLabel={ value => ' ' + ` ${value} Items ` + ' ' }` where previously I would see `item` with half the of the M cut off, adding in these extra spaces made it render correctly.

Thanks! At some point, your solution help me. But, I still facing this issue.

**Comment by hugoh59** [comment]
I have the same issue but instead of the sides being cut off it's the tops and bottoms.

**Comment by herparis** [comment]
> Here's how I've solved it: `formatLabel={ value => ' ' + ` ${value} Items ` + ' ' }` where previously I would see `item` with half the of the M cut off, adding in these extra spaces made it render correctly.

you have my respects

**Comment by McPatto** [comment]
Have the same issue, but with XAxis. I cpuldn't figure out how to add height to svg container
![image](https://user-images.githubusercontent.com/43398227/118553087-39c10480-b736-11eb-9eca-a14e6fff0d7d.png)
