### ISSUE TITLE
Add typings for TypeScript

### ISSUE THREAD

**Issue by krzysztof-miemiec** [JesperLekland/react-native-svg-charts#141]
### What is the problem?
We use TS for development of our projects. There are no TypeScript typings for this amazing library.

* When does it happen? *does not apply*
* What platform? *does not apply*
* Code to reproduce *does not apply*

I'll try to come up with some today and create a PR with it.

**Comment by krzysztof-miemiec** [comment]
Done!

**Comment by JesperLekland** [comment]
Closing this as it's being implemented [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25880). Thank you @krzysztof-miemiec for your contribution!
