### ISSUE TITLE
How can I use a Dashed Line and Decorator with an XAccessor

### ISSUE THREAD

**Issue by ORoberts221** [JesperLekland/react-native-svg-charts#143]
It seems that both the Dashed Line and Decorator examples reply on having evenly spaced data points. 

I would like to be able to use another value (time, in minutes) as my X Axis data, this draws the graph correctly but the Dashed Line and Data points decorators are out of place. I'm afraid I don't know how the svg library works well enough to re-position them dynamically myself.

Without xAccessor the chart looks like this: 
![withoutxaccessor](https://user-images.githubusercontent.com/10622911/40246075-5c4bc732-5abf-11e8-8db3-2c2506358d80.PNG)

However with the xAccessor added it looks like this: 
![withxaccessor](https://user-images.githubusercontent.com/10622911/40246088-6a46cfc6-5abf-11e8-9e38-e2bca426bf02.PNG)

The graph is actually correct, just the styling is off.

My code is: 
`export default ProgressChart = ({ book, sessions }) => {

    const data = getData(book, sessions);

    const indexToClipFrom = book.currentPage >= book.pageCount ? data.length : (data.length - 2);
    const contentInset = { top: 20, bottom: 20, left: 20, right: 20 }

    const Decorator = ({ x, y, data }) => {
        return data.map((value, index) => {
            stroke = index === (data.length - 1) ? 'rgb(255, 68, 68)' : 'rgb(26, 188, 156)';
            return (
                <Circle
                    key={index}
                    cx={x(index)}
                    cy={y(value.page)}
                    r={4}
                    stroke={stroke}
                    fill={'white'}
                />
            )
        })
    }

    const Clips = ({ x, width }) => {
        return (
            <Defs key={'clips'}>
                <ClipPath id="clip-path-1">
                    <Rect x={'0'} y={'0'} width={x(indexToClipFrom)} height={'100%'} />
                </ClipPath>
                <ClipPath id={'clip-path-2'}>
                    <Rect x={x(indexToClipFrom)} y={'0'} width={width - x(indexToClipFrom)} height={'100%'} />
                </ClipPath>
            </Defs>
        )
    }

    const DashedLine = ({ line }) => {
        return (
            <Path
                key={'line-1'}
                d={line}
                stroke={'rgb(255, 68, 68)'}
                strokeWidth={2}
                fill={'none'}
                strokeDasharray={[4, 4]}
                clipPath={'url(#clip-path-2)'}
            />
        )
    }

    return (
        <LineChart
            style={{ height: 250 }}
            data={data}
            contentInset={contentInset}
            yAccessor={({ item }) => item.page}
            scale={scale.scaleLinear}
            svg={{
                stroke: 'rgb(26, 188, 156)',
                strokeWidth: 2,
                clipPath: 'url(#clip-path-1)',
            }}
            curve={shape.curveMonotoneX}
        >
            <Grid />
            <Clips />
            <DashedLine />
            <Decorator />
        </LineChart>
    )}`

The data supplied is: 
`[{page: 2, time: 5},
{page: 3, time: 7},
{page: 3, time: 7},
{page: 8, time: 10},
{page: 81, time: 10},
{page: 100, time: 25},]`

Any help or advice with this would be appreciated.

**Comment by JesperLekland** [comment]
In your case you need both the y- and x-Accessor (since you pass complex objects as data).  Seeing that you also want your data points distributed not linearly but based on the time you also need to change the scale to `scale.scaleTime`.  Your circle decorator will then also have to change its `cx` to `cx={x(value.time)}`. All of these changes make sense if you think about it.

**Comment by ORoberts221** [comment]
Thank you very much! It does absolutely make sense. I was also able to get the clip path working by changing `x(indexToClipFrom)` to `x(data[index].time)` working perfectly now.
