### ISSUE TITLE
JSON Parsing Error

### ISSUE THREAD

**Issue by Korysam15** [JesperLekland/react-native-svg-charts#147]
### What is the problem?
Using one of the examples from this library, the error: JSON value '1' of type NSString cannot be converted to NSNumber. This a casting error between the ios string and integer value. 

### When does it happen?
No actions necessary, screen needs to load.  
### What platform?

* [X ] iOS 
* [ ] Android 

React Native version: 0.55.3

### Code to reproduce

```javascript
import React from 'react'
import { PieChart } from 'react-native-svg-charts'

class PieChartWithDifferentArcs extends React.PureComponent {

    render() {

        const data = [
            {
                key: 1,
                value: 50,
                svg: { fill: '#600080' },
                arc: { outerRadius: '130%', cornerRadius: 10,  }
            },
            {
                key: 2,
                value: 50,
                svg: { fill: '#9900cc' }
            },
            {
                key: 3,
                value: 40,
                svg: { fill: '#c61aff' }
            },
            {
                key: 4,
                value: 95,
                svg: { fill: '#d966ff' }
            },
            {
                key: 5,
                value: 35,
                svg: { fill: '#ecb3ff' }
            }
        ]


        return (
            <PieChart
                style={{ height: 200 }}
                outerRadius={'70%'}
                innerRadius={10}
                data={data}
            />
        )
    }

}

export default PieChartWithDifferentArcs;

```

**Comment by JesperLekland** [comment]
Hmm, interesting. And where does the value `1` come from?

**Comment by JesperLekland** [comment]
Can't reproduce on `react-native@0.52.2`. Are you still experiencing this? If so could you try another verison of RN and see if this issue still persists?

**Comment by JesperLekland** [comment]
Seems like it could be. Since the owner of this issue still haven't gotten back to me I'll go ahead and close this issue due to inactivity. If somebody else happens on the same thing please comment here (or create a new issue referencing this) and I'll try to investigate further
