### ISSUE TITLE
Pie chart not rendering labels and numbers. 

### ISSUE THREAD

**Issue by RahulCubet** [JesperLekland/react-native-svg-charts#149]
Hi,

I have copied the same code from with centered label example from <a href="https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/pie-chart/with-centered-labels.js">https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/pie-chart/with-centered-labels.js</a> here. But it wont render the labels. All other examples are working pretty well.

**Comment by RahulCubet** [comment]
I have fixed the issue. Just go through this code. The denderDecor method worked fine for me


import React from 'react'
import { PieChart } from 'react-native-svg-charts'
import { Circle, G, Line, Text} from "react-native-svg";

class PieChartWithCenteredLabels extends React.PureComponent {

    render() {

        const data = [
            {
                key: 1,
                amount: 50,
                svg: { fill: '#cc00ff' },
            },
            {
                key: 2,
                amount: 50,
                svg: { fill: '#0066ff' }
            },
            {
                key: 3,
                amount: 40,
                svg: { fill: '#ff0000' }
            },
            {
                key: 4,
                amount: 95,
                svg: { fill: '#009900' }
            },
            {
                key: 5,
                amount: 35,
                svg: { fill: '#0000ff' }
            }
        ]

        const Labels = ({ slices, height, width }) => {
            return slices.map((slice, index) => {
                const { labelCentroid, pieCentroid, data } = slice;
                return (
                    <Text
                        key={index}
                        x={pieCentroid[ 0 ]}
                        y={pieCentroid[ 1 ]}
                        fill={'white'}
                        textAnchor={'middle'}
                        alignmentBaseline={'middle'}
                        fontSize={24}
                        stroke={'black'}
                        strokeWidth={0.2}
                    >
                        {data.amount}
                    </Text>
                )
            })
        }

        return (
            <PieChart
                style={{ height: 200 }}
                valueAccessor={({ item }) => item.amount}
                data={data}
                spacing={10}
                outerRadius={'95%'}
                innerRadius={'50%'}
                labelRadius={10}
                renderDecorator={({ item, pieCentroid, labelCentroid, index }) => (
                <G key={index}>
                  <Text
                              key={index}
                              x={pieCentroid[0]}
                              y={pieCentroid[1]}
                              fill={'white'}
                              textAnchor={'middle'}
                              alignmentBaseline={'middle'}
                              fontSize={18}
                              stroke={'white'}
                              strokeWidth={0.2}
                          >
                              {item.amount}%
                          </Text>

                </G>
              )}
            />
        )
    }

}

export default PieChartWithCenteredLabels

**Comment by JesperLekland** [comment]
In that case you are on an old version of the library. 5.0.0 deprecates the `renderDecorator` prop in favor of the children pattern

**Comment by RahulCubet** [comment]
Yes I was working on 4.0.0. Anyway thanks for your quick reply.

**Comment by ivanherve** [comment]
Hi @JesperLekland,
If I have an upper version of the library, what should I use instead of the `renderDecorator` prop ? :)
Because I tried @RahulCubet 's code but it doesn't show any labels. 
Thank you

**Comment by ivanherve** [comment]
I just have fixed my problem, I just haven't seen the example code, the new one [https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/pie-chart/with-centered-labels.js](url)

Sorry! :)

**Comment by linux08** [comment]
Hi @JesperLekland,
I am trying to show labels as @RahulCubet  did above.I am using the latest version and i am following the example here https://github.com/JesperLekland/react-native-svg-charts/issues/215 .
The label facebook,google, linkedin and so on doesnt show,only the charts display.Kindly help with an example .
