### ISSUE TITLE
Line Chart not drawn in signed Release

### ISSUE THREAD

**Issue by ORoberts221** [JesperLekland/react-native-svg-charts#150]
### What is the problem?
The actual lines in this line chart are not drawn in the signed release version of the app, works fine in debug with the same data. Other charts (progress circle & bar chart) working fine.

I did need to include a `android.enableAapt2=false` flag in gradle.properties in order to get the build working re facebook/react-native#16906, could this be the cause of the problem?

### Examples:
* Debug
![debug](https://user-images.githubusercontent.com/10622911/40478534-34b44830-5f41-11e8-9057-a3b14192e67a.PNG)

* Release
![release](https://user-images.githubusercontent.com/10622911/40478538-3984e43c-5f41-11e8-81fd-93b8938f229d.PNG)

### What platform?

* [ x ] Android 

React Native version: 0.55.4

### Code to reproduce
`

export default ProgressChart = ({ book, sessions }) => {
    const green = 'rgb(26, 188, 156)';
    const red = 'rgb(255, 68, 68)';

    const data = getData(book, sessions);

    const indexToClipFrom = book.currentPage >= book.pageCount ? (data.length - 1) : (data.length - 2);
    const contentInset = { top: 10, bottom: 10, left: 10, right: 10 };
    const axesSvg = { fill: 'grey', fontSize: 10, alignmentBaseline: 'baseline' };
    const xAxisHeight = 30;

    const Decorator = ({ x, y, data }) => {
        return data.map((value, index) => {
            stroke = index === (data.length - 1) ? red : green;
            return (
                <Circle
                    key={index}
                    cx={x(value.time)}
                    cy={y(value.page)}
                    r={4}
                    stroke={stroke}
                    fill={'white'}
                />
            )
        })
    }

    const Clips = ({ x, y, width, data }) => {
        let startPoint = data[indexToClipFrom];
        return (
            <Defs key={'clips'}>
                <ClipPath id="clip-path-1">
                    <Rect x={'0'} y={'0'} width={x(startPoint.time)} height={'100%'} />
                </ClipPath>
                <ClipPath id={'clip-path-2'}>
                    <Rect x={x(startPoint.time)} y={'0'} width={width - x(startPoint.time)} height={'100%'} />
                </ClipPath>
            </Defs>
        )
    }

    const DashedLine = ({ line }) => {
        return (
            <Path
                key={'line-1'}
                d={line}
                stroke={red}
                strokeWidth={2}
                fill={'none'}
                strokeDasharray={[4, 4]}
                clipPath={'url(#clip-path-2)'}
            />
        )
    }

    return (
        <View style={{ flex: 1, marginTop: 10 }}>
            <View style={{ height: 250, margin: 5 }}>
                <View style={{ flex: 1, flexDirection: 'row' }}>
                    <YAxis
                        style={{ height: 250 }}
                        data={data}
                        svg={{ fill: 'grey', fontSize: 12 }}
                        yAccessor={({ item }) => item.page}
                        formatLabel={(value) => `${value}%`}
                        contentInset={contentInset}
                        numberOfTicks={3}
                    />
                    <LineChart
                        style={{ flex: 1, height: 250, marginLeft: 5 }}
                        data={data}
                        contentInset={contentInset}
                        yAccessor={({ item }) => item.page}
                        xAccessor={({ item }) => item.time}
                        scale={scale.scaleTime}
                        svg={{
                            stroke: green,
                            strokeWidth: 2,
                            clipPath: 'url(#clip-path-1)',
                        }}
                        curve={shape.curveMonotoneX}
                    >
                        <Grid />
                        <Clips />
                        <DashedLine />
                        <Decorator />
                    </LineChart>
                </View>
            </View>
            <Text style={{ alignSelf: 'center' }}>Total Reading Time</Text>
        </View>
    )
}
`

**Comment by JesperLekland** [comment]
Could you try the same code in a different project where where you don't disable aapt2?

**Comment by ORoberts221** [comment]
Good idea - will try that.

**Comment by ORoberts221** [comment]
In the end this turned out to be an issue with npm versioning. 

react-native-svg 6.3.1 does not draw the line for the line charts, to get around this I had reverted to using 6.2.1 instead, unfortunately I forgot to pin the version in package.json, so my build server was using the newer, incorrect version when building the release apk. 

The fix was as simple as changing `react-native-svg:"^6.2.1"` to `react-native-svg:"6.2.1"`. 

Working as intended now, happy to close this.
