### ISSUE TITLE
Line Chart for Streaming Real-time Data

### ISSUE THREAD

**Issue by Yaweii** [JesperLekland/react-native-svg-charts#154]
First of all, thank you so much for the great job! I've been searching around and this is the best chart library. This is more of a question instead of a problem. Please feel free to share your thoughts. 

### What is the problem?
Trying to draw the line chart for real time data.  I am building an application for vehicle data visualization.  The data looks like this **{ speed: 55 }** and the server will send me this data every 0.3 seconds. 

I'm looking at this [example](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/line-chart/with-shadow.js) and trying to build the line chart like this.

The data we passed is an array. However, with my case, the data isn't prepared and it is real-time data. My question is how to pass or structure this data and pass it in order to animate the line chart. 
### What platform?
Android

React Native version: 0.55.4

### Code to reproduce

```javascript
// put code here
const SpeedLineChart = (props) => {
  
    const { vehicleStates } = props.vehicleStates;
    console.log( vehicleStates .speed)
        return (
            <View style = {{ height: 200, flexDirection: 'row'}}>
            <LineChart
                style = {{ height: 300, width: 300}}
                animated = {true}
                animationDuration = {10}
                gridMin = {0}
                gridMax = {100}
                data = { [vehicleStates.speed] }
                svg = {{ stroke: 'rgb(134, 65, 244)' }}
                contentInset = {{ top: 20, bottom: 20 }}
            >
                <Grid/>
            </LineChart>
            </View>
        )
  }

console log output:
speed: 50
speed: 51
speed: 45
speed: 53
...
### Stacktrace (if crash)
```

```
-->

**Comment by Yaweii** [comment]
@JesperLekland Thanks for the reply!   I am trying to build something like this [animation](https://bost.ocks.org/mike/path/).

**Comment by JesperLekland** [comment]
Well that animation has a data set that is full from the beginning. If you would have that many dataPoints and switch them out for an equally long array with different points it would (should) behave exactly like the one you've linked

**Comment by JesperLekland** [comment]
Oh, that link contained several animation, which one did you mean?

**Comment by Yaweii** [comment]
@JesperLekland  [Example](http://bl.ocks.org/simenbrekken/6634070)  this might be a better example. When new data comes in, the path will transit to the left.

**Comment by Yaweii** [comment]
@JesperLekland Thanks! I will close this issue for now. Really appreciated your help!

**Comment by j-funk** [comment]
@Yaweii I am very interested in your results to this query!  Would you be able to elaborate on what you ended up with?

**Comment by Developekolja** [comment]
I am interestet in your results as well!
