### ISSUE TITLE
How to show Vertical Lines? 

### ISSUE THREAD

**Issue by maryammouse** [JesperLekland/react-native-svg-charts#16]
### What is the problem?
I'm not sure if this is just something not implemented in this library or if I've missed something in the README. How do I get my charts to render *vertical* grid lines, and not horizontal ones? By default only horizontal ones are rendered and while there exists a `showGrid` function this only hides horizontal grid lines.

(edit: I'm fairly new to charting libraries as a whole!)

**Comment by JesperLekland** [comment]
Hi @maryammouse! The library does not support vertical lines at the moment. An easy workaround would be to use the `renderExtra` prop to render them yourself. I'll think of a nice API and see if I can make vertical grid lines a part of the library in the near future

**Comment by JesperLekland** [comment]
Hi again! I implemented a better `Grid` api in this PR #22. Hopefully this will solve your problem in the best way possible. If the supplied default vertical and horizontal grid components doesn't do the trick you're free to create your own grid through the `renderGrid` prop

**Comment by JesperLekland** [comment]
Available in 2.1.0
