### ISSUE TITLE
Area Chart not render when the width is very high value

### ISSUE THREAD

**Issue by Danushka50** [JesperLekland/react-native-svg-charts#161]
### When does it happen? 
datapoints=[]// insert 100 points
Given  width is very high value area chart not render in HCT M8, HUAWI GR5 mobile phones

### What platform?

* [ ] iOS 
* [x] Android 

React Native version: 0.50.4

### Code to reproduce

```javascript

render(
   <ScrollView
            ref="scrollView"
            showsHorizontalScrollIndicator={false}
            horizontal={true}
          >
        <AreaChart
              style={{ height:280, width: 1500 }} //HTC width:1360 works fine
              dataPoints={datapoints}
              fillColor={colorsGraph.chartFill}
              strokeColor={colors.secondaryColor1}
              contentInset={{ top: 100, bottom: 30, left: 50, right: 50 }}
              curve={shape.curveCatmullRom.alpha(1.2)}
              extras={this.state.extras}
              renderExtra={({ item, ...args }) => item(args)}
              showGrid={false}
              animate={false}
              animationDuration={0}
              gridMax={this.stategraphFillHeight} />

    </ScrollView>
)
```
### Stacktrace (if crash)
```
W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (5910x840, max=4096x4096)
```

**Comment by JesperLekland** [comment]
I've stumbled on a similar error before (unrelated to this specific library). I think you might have to split your data and render separate charts in a `FlatList` to avoid this issue. There is nothing I can specifically do to remedy this. Closing due to problem existing outside this library

**Comment by Danushka50** [comment]
Thank you

**Comment by alexjs87** [comment]
@Danushka50 , o FlatList resolveu seu problema?

**Comment by SamuelGalantei4sea** [comment]
@Danushka50, using FlatList solve your problem ?
