### ISSUE TITLE
StackedAreaChart does not use xAccessor/yAccessor props

### ISSUE THREAD

**Issue by ramilushev** [JesperLekland/react-native-svg-charts#163]
### What is the problem?
Passing `xAccessor`/`yAccessor` props to `StackedAreaChart` has no effect.

### When does it happen?
Everytime

### What platform?
* [x] iOS
* [x] Android

React Native version: 0.55.3

**Comment by JesperLekland** [comment]
Indeed it does not. It has a completely different data structure than the other charts. Would you mind posting an example of data that would require any of the `accessor` functions?

**Comment by ramilushev** [comment]
I was previously using them in `AreaChart` to give a non-linear distribution to the x values. Now I need to stack two of them, and I need them to use the same X scale, while still using immutable to do it. I could probably achieve this with two distinct `AreaCharts`, but I cannot figure out how to use the same scale for X.

**Comment by JesperLekland** [comment]
I see! The stacked charts don't support the `xScale` prop yet, but it's next in line to be implemented. Not sure how nice it will play with the d3.js implementation of calculating stacked charts but I guess we'll see :P

**Comment by JesperLekland** [comment]
Looking at the image you attached above I don't think the stacked charts would solve your problem, as they stack the values, not the separate charts (see [this screenshot](https://github.com/JesperLekland/react-native-svg-charts-examples#stackedareachart). What you could do is use two different charts placed on top of each other and pad the data of the "lesser" chart with data points that just have `undefined` as values but xValues that correspond to the minimum and maximum of the other chart. 

Ideally I should introduce something similar to `gridMin` and `gridMax` for the x axis

**Comment by ramilushev** [comment]
@JesperLekland got it working with the method you suggested! Still, a `gridMin/gridMax` prop would be a lot cleaner solution. Thanks!

**Comment by JesperLekland** [comment]
I implemented it today actually. The `gridMin`/`gridMax` will be replaced by the `yMin`/`yMax` and `xMin`/xMax` props. Just have to thoroughly test it and then make a release.
