### ISSUE TITLE
Question: ProgressCircle animation

### ISSUE THREAD

**Issue by muraterd** [JesperLekland/react-native-svg-charts#164]
Hi, 
First of all this is wonderful library. Thank you for your effort. 

I'm using ProgressCircle component and there is a animate property under Common Props. So i tried to animate the component but it didn't worked. 

I'm using component like below
`<ProgressCircle
          style={{ height: 200 }}
          progress={0.9}
          progressColor={"rgb(134, 65, 244)"}
          animate={true}
        />`

Am i missing something?

**Comment by JesperLekland** [comment]
Hi and thank you for your kind words. The `animate` prop is unfortunately very experimental and is currently set to only animate when the values change, not on initial render

**Comment by muraterd** [comment]
Thank you for the quick reply :)
