### ISSUE TITLE
Is it possible to set onPress on the lineChart Component? and return de xAxis value related to that position

### ISSUE THREAD

**Issue by vlimag** [JesperLekland/react-native-svg-charts#169]
I would like to press some place on the line chart, and get the value on the x Axis.
Is that possible?

I am using React Native version: 0.55.4

Solution:

Solved by drawing an rectangle on the chart.js file, making it touchable sensitive.

**Comment by 50shashwat** [comment]
Needed an easier solution to implement on line chart as in bar chart.
