### ISSUE TITLE
Overlapping labels

### ISSUE THREAD

**Issue by dhcmega** [JesperLekland/react-native-svg-charts#170]
### What is the problem?
Overlapping labels over the pie chart.

### When does it happen?
Draw a pie chart with 2 or more slices with very small percentage.

### What platform?

* [x] iOS 
* [x] Android 

React Native version: 0.53.3
    "react": "16.2.0",
    "react-native": "0.53.3",
    "react-native-svg": "^6.3.1",
    "react-native-svg-charts": "^5.0.0",

### Code to reproduce

```javascript
    const LabelsPer = ({ slices, height, width }) => slices.map((slice, index) => {
      const { labelCentroid, pieCentroid, data } = slice;
      return (
        <SVGText
          key={index}
          x={pieCentroid[0]}
          y={pieCentroid[1]}
          fill="white"
          textAnchor="middle"
          alignmentBaseline="middle"
          fontSize={25}
          fontWeight="800"
          stroke="black"
          strokeWidth={1}
        >
          {data.label}
        </SVGText>
      );
    });
          <PieChart
            style={{ height: 250, width: 250, marginBottom: 50 }}
            valueAccessor={({ item }) => item.amount}
            data={percentages}
            spacing={0}
            innerRadius={2}
            outerRadius={125}
            labelRadius={60}
          >
            <LabelsPer/>
          </PieChart>
```

![screenshot_20180614-132457](https://user-images.githubusercontent.com/6719578/41425425-0b179d32-6fd7-11e8-9644-69e400a29399.png)

**Comment by JesperLekland** [comment]
This is expected behaviour. You yourself position the text with `y` and `x` prop. Add your own offset for small slices. This is a medium level library and such will never implement very specific use cases like this one, however we provide you with all the tools to solve it yourself (i.e the props mentioned above).

**Comment by dhcmega** [comment]
Values change, as it is a voting system, so I cannot set a specific position, it changes through out the day. Thanks for your response.
