### ISSUE TITLE
onPress get value from chart

### ISSUE THREAD

**Issue by ashutoshtrack** [JesperLekland/react-native-svg-charts#174]
How can i get value using onPress for all chart?
Please help me.

**Comment by JesperLekland** [comment]
There are several ways. You yourself set the `onPress` on a data item, it's up to that `onPress` to return a relevant resposne. See [this](https://github.com/JesperLekland/react-native-svg-charts/blob/dev/storybook/stories/bar-stack/with-on-press.js) for inspiration
