### ISSUE TITLE
Charts not rendering

### ISSUE THREAD

**Issue by hobbesdaboba** [JesperLekland/react-native-svg-charts#18]
### What is the problem?
Using various examples (I only tried AreaChart and LineChart) in Expo don't render.

**Comment by hobbesdaboba** [comment]
Ok, I got it to work by adding the width style property (in addition to the height style property that is already there). All is well. Please update examples! Thanks!

**Comment by JesperLekland** [comment]
@hobbesdaboba The width should only be needed if placed in a parent with `flexDirection: row`, just the same as a regular `View`, in fact each chart is wrapped in regular `View`
