### ISSUE TITLE
Xaxis label on two lines

### ISSUE THREAD

**Issue by ln0v** [JesperLekland/react-native-svg-charts#180]
### more of is this possible / how to question 

my X axis is a time line, using <XAxis /> labels like  "7 June,2017" takes up too much space. 
I would like it formatted in two lines like:
7 June
2017

can this formatting be done , (can the svg prop take Tspan) in the current <XAxis />
any help is much appreciated

**Comment by gertvdkolk** [comment]
Haven't tested this but maybe this works:
Use formatLabel prop and use a string literal, split on the comma and return the year part on a new line?

**Comment by JesperLekland** [comment]
@gertvdkolk That should technically work, haven't tested it myself either. I saw one user who just added two XAxis and on showed the date, the other the year. Try any solution you see fit.

**Comment by ln0v** [comment]
@gertvdkolk @JesperLekland both your suggestions work
this works:
`7June 
   1870`
spacing & alignment does not work too well with the above, having a another XAxis with just the  year works well. 
Much appreciate you help.
