### ISSUE TITLE
How to create a market depth chart

### ISSUE THREAD

**Issue by longpq18** [JesperLekland/react-native-svg-charts#181]
![workspace 1_010](https://user-images.githubusercontent.com/15885041/42011026-a8b28bbc-7abb-11e8-81f4-4b9e57df10b3.png)

**Comment by JesperLekland** [comment]
Check out the [examples repo](react-native-svg-charts-examples) for partial charts and gradient decorators.

**Comment by Sandeep200995** [comment]
The above example repo is empty please suggest any svg for Market Depth Chart (same as above image)in react native .

**Comment by JesperLekland** [comment]
My bad, link was broken. Fixed now 👍

**Comment by thanhvk** [comment]
Recently I faced this challenge. I have resolved it by using the area chart.

- the result:
![image](https://user-images.githubusercontent.com/11411161/74620169-c911ed80-516a-11ea-88e7-bf9f9be9928d.png)
- fake data to test: https://raw.githubusercontent.com/thanhvk/tomox-sdk-dapp/master/src/components/DepthChart/data.js
- my code (details in [here](https://raw.githubusercontent.com/thanhvk/tomox-sdk-dapp/master/src/components/DepthChart/DepthChartRenderer.js)): 
```
<View style={{ height: 200 }}>
    <AreaChart
        style={{ flex: 1 }}
        data={ data }
        contentInset={{ top: 30, bottom: 30 }}
        svg={{
            fill: 'url(#bid-gradient)',
            clipPath: 'url(#clip-path-bid)',
        }}
        curve={ shape.curveStep }
        yAccessor={ ({ item }) => item.total }
        xAccessor={ ({ item }) => item.price }
        xScale={ scale.scaleLinear }
    >
        <BidGradient/>
        <Clips/>
    </AreaChart>

    <AreaChart
        style={ StyleSheet.absoluteFill }
        data={ data }
        contentInset={{ top: 30, bottom: 30 }}
        svg={{
            fill: 'url(#ask-gradient)',
            clipPath: 'url(#clip-path-ask)',
        }}
        curve={ shape.curveStep }
        yAccessor={ ({ item }) => item.total }
        xAccessor={ ({ item }) => item.price }
        xScale={ scale.scaleLinear }
    >
        <AskGradient/>
        <Clips/>
        <BidLine/>
        <AskLine/>
    </AreaChart>
</View>
```
Hope it will be helpful for someone who is looking a solution to create depth chart with ```react-native-svg-charts```. 
Thank you for the great library.
