### ISSUE TITLE
Yaxis not working in a snack?

### ISSUE THREAD

**Issue by acomito** [JesperLekland/react-native-svg-charts#185]
I was trying to reproduce an issue I had with a snack,. but I'm getting an error sounding like YAxis can't be imported from the npm package? Any ideas of did I miss something specific to working with snacks?

https://snack.expo.io/@arcomito/react-native-svg-charts-label-and-xaxis-bugs

**Comment by JesperLekland** [comment]
I noticed that too yesterday, no idea what it's about :(

**Comment by acomito** [comment]
Closing for now just wanted to make sure it wasn't me.

**Comment by pinchez254** [comment]
same issue here am getting this error '' Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.'' how do  i resolve this
