### ISSUE TITLE
get y values through panResponder

### ISSUE THREAD

**Issue by kevinNejad** [JesperLekland/react-native-svg-charts#187]
Hi
Thank you so much for such an amazing library and great support. 
I am trying to get y values of my point while moving the bar.

![screen shot 2018-07-09 at 00 02 05](https://user-images.githubusercontent.com/26068228/42424884-42868b6e-830c-11e8-910a-7be9e9c2a98a.png)

**Comment by JesperLekland** [comment]
Hi @kevinNejad! It is possible but not something that is supported out of the box. We've discussed it briefly in [this issue](https://github.com/JesperLekland/react-native-svg-charts/issues/122)

**Comment by kevinNejad** [comment]
@JesperLekland Thank you so much.
I'm closing this as it's discussed here. [https://github.com/JesperLekland/react-native-svg-charts/issues/122](url)
