### ISSUE TITLE
PieChart, allow onPress of each pie piece. 

### ISSUE THREAD

**Issue by jayesbe** [JesperLekland/react-native-svg-charts#19]
Is it possible to be able to apply onPress events to each piece of the pie ?

I added an onPress to the Circle label.. however I am not sure how to do make the entire piece touchable

**Comment by JesperLekland** [comment]
Hi @jayesbe and thank you for your issue. This seems like a perfectly valid feature request. I'll make sure it ends up in the next release :)

**Comment by jayesbe** [comment]
Awesome. Thanks.

**Comment by JesperLekland** [comment]
Is available in 2.0.2 :)

**Comment by YahyaBagia** [comment]
Could you provide an example of this (onPress on each Pie piece)?
I followed the example and referred the Readme, but could not find it.

**Comment by colaquecez** [comment]
Did anyone get it?
