### ISSUE TITLE
I found that the scale (YAxis) is automatically calculated based on the data source. I want to customize the scale (YAxis). What should I do next?

### ISSUE THREAD

**Issue by cao1034** [JesperLekland/react-native-svg-charts#191]
![fb50c145-233f-4fad-a1b0-0809fdaa5f66](https://user-images.githubusercontent.com/11959771/42815942-8c780734-89fb-11e8-90f6-96826a7b4c51.png)

**Comment by JesperLekland** [comment]
What do you wan't to customise?

**Comment by cao1034** [comment]
I wish I could set the scale eg: 100 (YAxis : 100,200,300,400)
I tried multiple sets of data and found that the scale can now be 5, 10, 20 and so on.

**Comment by JesperLekland** [comment]
you can pass the YAxis any data set that you want. It will always pick the highest and lowest value and calculate the ticks from those data points. You can tweak the ticks with the `numberOfTicks` prop. See [d3-ticks](https://github.com/d3/d3-scale#continuous_ticks) for more info

**Comment by cao1034** [comment]
I found that the excess could not be displayed, maybe I didn't find a way.
![c956c365-67af-46a7-b834-9a6363689f6d](https://user-images.githubusercontent.com/11959771/42816844-b2bdc156-89fe-11e8-830e-b578db32ca6b.png)

**Comment by cao1034** [comment]
The scale problem has been solved, thank you
