### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by cao1034** [JesperLekland/react-native-svg-charts#192]
Hi Hello, I would like to ask if the label is out of the area, how to display it?
![5546dbb0-f278-4be4-9dd4-494dacd4720f](https://user-images.githubusercontent.com/11959771/42893136-231b3f68-8ae6-11e8-92bb-1a2bbd3516f0.png)
![e577c82f-4770-4194-b276-fe38e75a9116](https://user-images.githubusercontent.com/11959771/42893138-238c6878-8ae6-11e8-9338-11e5ea98ee5a.png)

**Comment by JesperLekland** [comment]
You position the label yourself so there's a million ways of doing it. A suggestion would be to use the `yMax` prop to increase the area above the graph and thus being able to keep it above the graph line.
