### ISSUE TITLE
How to full fill parent view

### ISSUE THREAD

**Issue by flalex** [JesperLekland/react-native-svg-charts#193]
### What is the problem?
First of all, thank you very much for this incredible library. Great work.

I feel that lost obvious thing, sorry for that, but I'm a little bit confused.

I use AreaChart with Path and LinearGradient and see that chart has dynamically width.

Please, check the screenshots.
![chart1](https://user-images.githubusercontent.com/818999/42901806-ad1cece2-8add-11e8-9765-0575a416d2e1.PNG)
![chart2](https://user-images.githubusercontent.com/818999/42901814-afb3e190-8add-11e8-9c46-fa9a4ec8dc57.PNG)

Is it possible to do, that chart always has 100% width and height without left, right and top white padding?

I tried use flex style and change view size, but it didn't give results.
Maybe I must use non default scale?

Look forward for help.
### What platform?

* [ ] iOS 
* [ ] Android 

React Native version: 0.xx

### Code to reproduce
Hope everything is clear. I don't use something special.
```javascript
import React from 'react';
import {StyleSheet, View} from 'react-native'
import { AreaChart } from 'react-native-svg-charts'
import { Defs, LinearGradient, Stop, Path } from 'react-native-svg'
import * as shape from 'd3-shape'

const Gradient = ({ index }) => (
    <Defs key={index}>
        <LinearGradient id={'gradient'} x1={'0%'} y={'0%'} x2={'0%'} y2={'100%'}>
            <Stop offset={'0%'} stopColor={'rgb(123, 256, 123)'} stopOpacity={1}/>
            <Stop offset={'100%'} stopColor={'rgb(56, 265, 235)'} stopOpacity={1}/>
        </LinearGradient>
    </Defs>
)

const Line = ({ line }) => (
    <Path
        y={ -1 }
        key={'line'}
        d={line}
        stroke={'rgba(123, 245, 12, 1)'}
        strokeWidth={ 2 }
        fill={'none'}
    />
)

const ChartWidget = ({ data }) => (
  <View style={styles.chartWidget} >
    <AreaChart
      style={ styles.chart }
      data={data}
      curve={ shape.curveBasisOpen }
      svg={{ fill: 'url(#gradient)' }}
    >
      <Line />
      <Gradient />
    </AreaChart>
  </View>
)

export default class App extends React.Component {
  constructor() {
    super()
  }

  render() {
    return (
      <View style={styles.mainWrapper} >
        <ChartWidget data={[12, 150, 360, 40]}/>
        <ChartWidget data={[12, 150, 360, 40, 1000, 40, 60]}/>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  mainWrapper: {
    width: '100%',
    height: '100%',
    backgroundColor: "#EEF1FD",
    padding: 8,
  },
  chartWidget: {
    marginTop: 20,
    backgroundColor: "#FFFFFF",
  },
  chart: {
    width: '100%',
    height: 124,
  },
})
```

**Comment by JesperLekland** [comment]
Hi @flalex Please provide example code, otherwise it's impossible to help you

**Comment by flalex** [comment]
Hi @JesperLekland Updated request !

**Comment by JesperLekland** [comment]
You're using a `curve` that exhibits the behaviour in your screenshots. Try e.g `shape.curveBasis` and you'll see that everything behaves as expected.

**Comment by flalex** [comment]
@JesperLekland Thank you for the response. But...

Yes, I need "smooth" curve and yes shape.curveLinear behaves as expected, but is not suitable for me.
Sorry, I don't understand this point
>  the data points are bound to go beyond the bounds of the chart

Passing contentInset with zero values to AreaChart in the code above don't change the behavior ...

Any ideas for getting such behavior for "smooth" curve?

**Comment by cao1034** [comment]
AreaChart   parameter：  xMin ，  xMax  。Maybe you can try it, it solves my same problem.

**Comment by flalex** [comment]
@cao1034 Thank you very much, now it solves my issue too!
But, I've tried the same way with yMin, yMax and have no understanding how it works.
Using max data value for yMax not help.

@JesperLekland Why did you close the issue before finding clear solution ?
As you see this issue might be actual for some users and it'll be good help to place here the answer.

**Comment by JesperLekland** [comment]
Because this is not an issue with the library itself but an issue with mathematical interpolation of a curve along data points. Something that there are several ways to tackle and this library supports several. Open issues are for problems within the library, people are still free to search for the closed issues.

**Comment by cao1034** [comment]
@flalex 
If you need to specify  yMax 
 YAxis setting:
data={[yMin,yMax]}
min={yMin}
max={yMax}
numberOfTicks={ticksNumber}
AreaChart
  yMin={yMin}
 yMax={yMax}
numberOfTicks={ticksNumber}

eg: yMin 0, yMax 1000 ticksNumber: 5   result:  0 200, 400, 600, 800, 1000   
default is linear    can be set yScale  
obout yScale https://www.npmjs.com/package/d3-scale
English is not good, please forgive me!
