### ISSUE TITLE
Stacked Area Chart onPress get value and position for tooltip

### ISSUE THREAD

**Issue by kashifsulaiman** [JesperLekland/react-native-svg-charts#195]
### What is the problem?

For Stacked Area Chart, onPress is explicit in svgs array, not in the data. We're unable to get the values & position of the pressed item.

### When does it happen?
Clicking a value in the chart.

### What platform?

* [x] iOS 
* [x] Android 27.0.0

React Native version: 0.55.2

### Code to reproduce

```javascript
     const colors = [ '#8800cc' ];
     const keys   = [ 'count' ];
     const svgs = [ { onPress: () => console.log('apples') }]
    <StackedAreaChart
                            style={ { height: 200, paddingVertical: 16 } }
                            data={ data }
                            keys={ keys }
                            colors={ colors }
                            curve={ shape.curveNatural }
                            svgs={ svgs }
                        />
```

**Comment by kashifsulaiman** [comment]
@JesperLekland Thanks for replying, the issue is, I'm providing an array of object as data where `count` is the key. Now what I need is to check whether which Index or value of count is pressed How's that possible?

**Comment by JesperLekland** [comment]
@kashifsulaiman Could you show me an example of the data?

**Comment by kashifsulaiman** [comment]
@JesperLekland Sure
[ {
    "count": 1,
    "key": 1532336400000
  },
  {
    "count": 2,
    "key": 1532347200000
  }]

**Comment by JesperLekland** [comment]
Well then what would stop you from doing something like this? 
```jsx
svgs = data.map(({count}) => ({ onPress: () => count }))
```

**Comment by kashifsulaiman** [comment]
@JesperLekland no this doesn't fulfill the requirement.
Actually here each onPress object is for each key (Each stack), that is what I got from your example...
With your code, I'm only getting the first element's on Press event at any point I press!

**Comment by kashifsulaiman** [comment]
@JesperLekland Is there any example for this?

**Comment by JesperLekland** [comment]
What do you mean with first element? If you want to know which xIndex as well as which stack the onPress is for you're going to have to build your own decorators for the chart. Each area is built with one path and as such can't tell you where in the area it has been touched.

**Comment by kashifsulaiman** [comment]
@JesperLekland `can't tell you where in the area it has been touched.` this was required actually. Hopefully any work in future for this?

**Comment by JesperLekland** [comment]
As I said, you can build it yourself with decorator. But there won't be any built in support for this in the near future.

**Comment by kashifsulaiman** [comment]
@JesperLekland Could you show any example for decorator usage?

**Comment by kashifsulaiman** [comment]
@JesperLekland It worked using Decorators! Thanks alot!

**Comment by msevestre** [comment]
Could you share your code? I'd like to add a similar feature to one of my app. Thanks

**Comment by kashifsulaiman** [comment]
@msevestre I changed my chart to `AreaChart` and then

**Comment by kashifsulaiman** [comment]
@msevestre I changed my chart to AreaChart and then

     const data = [34, 53, -43, 36, 63];
     const Decorator = ({ x, y, data }) => {
            return data.map((value, index) => (
                    <Circle
                        key={ index }
                        cx={ x(index) }
                        cy={ y(value) }
                        r={ 5 }
                        onPress={() => {}}
                        stroke={ 'rgb(134, 65, 244)' }
                        fill={ 'white' }
                    />
            ))
        }
     <AreaChart
                style={{ height: 200 }}
                data={data}
                contentInset={{ top: 20, bottom: 20 }}
                curve={ shape.curveNatural }
            >
                <Decorator/>
            </AreaChart>

**Comment by msevestre** [comment]
@kashifsulaiman Thanks!! Cheers

**Comment by isabelleaubron** [comment]
Hi @kashifsulaiman, thanks for the code you shared. However I can't make the onPress function work on iOS, can you tell me if you were able to detect onPress event ? 
It seems that there is a zIndex problem, I can't click on any Decorator inside a Chart, any help would be really appreciated !

**Comment by avinashtadavarthy** [comment]
@isabelleaubron I'm guessing this might be too late for a reply but I was recently facing the same issue and I was able to solve it by adding the zIndex style attribute to my main graph element to help detect an onPress event.

```javascript
<StackedBarChart
                style={{ height: 125, zIndex: 1 }} // specified zIndex as a style attribute
                keys={keys1}
                colors={colors1}
                data={this.state.dataTop}
                spacingInner={0.2}>
                <ChartPoints type="top" /> // the decorator for my graph
              </StackedBarChart>
```
