### ISSUE TITLE
StackedBarChart grouped with Bar Chart(s)

### ISSUE THREAD

**Issue by alburdette619** [JesperLekland/react-native-svg-charts#196]
### What is the problem?

I need the ability to group bar and stacked bar charts side by side identical to the current functionality of grouping bars.

### When does it happen?

The feature is not currently supported as per communications with @JesperLekland.

### What platform?

* [x] iOS
* [x] Android

React Native version: `0.55.4`

### Example

Single Data Point:

<img width="110" alt="screen shot 2018-07-20 at 11 53 26 am" src="https://user-images.githubusercontent.com/22638838/43012182-ad799dc0-8c13-11e8-82f0-dd11b1cbb635.png">

**Comment by alburdette619** [comment]
I plan to try to at least figure this out today @JesperLekland.  If there are any implementation details you'd like me to consider let me know but I'll of course try to understand the codebase and work appropriately off of that taking the current bar grouping as a model.  As long as all goes well I'll submit a PR.

**Comment by alburdette619** [comment]
Is it maybe possible to do this today if both charts are rendered side by side using the `spacingOuter` prop?  If the stack supported that property too, the bar group and the stack bar could just be moved over a specific amount.  Otherwise this is something I don't think this library has previously done before.  I'd have to make some specialized container or grouped component.

**Comment by alburdette619** [comment]
Okay, I followed the overlapping charts story and kinda got this to work, but it's not a great solution.  The setting of `spacingInner`, `spacingOuter`, and `contentInset` would have to be very fine tuned and that's what d3 is for.

**Comment by alburdette619** [comment]
After taking some time to just look at the code, I'm a little confused how to accomplish this architecturally and would like your input @JesperLekland.  I think this will either have to be a brand new component or it will extend the stacked bar chart and override measurement functions.  Please provide your thoughts when you have time 😃

**Comment by JesperLekland** [comment]
First of all, thank you for a thorough investigation of the problem 🥇 
Secondly, I'm on my summer vacation and as such won't be able to help all that much. 

I think the best bet right now is to create a new component (at least internally, much as the regular and grouped bar chart) and then see if there's any way we can merge the down the line. Feel free to open a PR and I'll assist you to the best of my abilities

**Comment by usrbowe** [comment]
Closing since #239 was merged.
