### ISSUE TITLE
XAxis labelling behaves unexpectedly with 24hr data set and scaleTime

### ISSUE THREAD

**Issue by markedup** [JesperLekland/react-native-svg-charts#200]
### What is the problem?

When using a data set which comprises a `Date` / `value` pair as an object per data entry, XAxis doesn't seem to be able to plot the time at regular intervals when assigning `numberOfTicks` in combination with D3's `scaleTime` helper.

Furthermore, the XAxis does not span the chart width correctly, or end on the final `Date` in the provided data set in this configuration. It does start from the correct left-most position with the very first `Date` value, however.

Note that if you exclude the `scale` prop from the `XAxis` component, the labels are aligned more as expected, but the values are less useful.

### When does it happen?

Initial chart render; only tested with static data sets.

### What platform?

* [x] iOS: 11.4 (tested in Simulator)
* [ ] Android (untested; probably?)
* react-native: 0.55.4
* react-native-cli: 2.0.1

### Code to reproduce

```javascript
import React from "react";
import { View } from "react-native";
import { LineChart, XAxis, Grid } from "react-native-svg-charts";
import * as Scale from "d3-scale";
import dateFns from "date-fns";

class XAxisDemo extends React.PureComponent {
  render() {
    const data = [
      { date: dateFns.setHours(new Date(2018, 6, 11), 0), value: 50 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 1), value: 10 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 2), value: 40 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 3), value: 95 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 4), value: -4 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 5), value: -24 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 6), value: 85 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 7), value: 91 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 8), value: 35 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 9), value: 53 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 10), value: -53 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 11), value: 24 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 12), value: 50 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 13), value: -20 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 14), value: -80 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 15), value: 50 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 16), value: 10 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 17), value: 40 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 18), value: 95 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 19), value: -4 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 20), value: -24 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 21), value: 85 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 22), value: 91 },
      { date: dateFns.setHours(new Date(2018, 6, 11), 23), value: 35 }
    ];

    return (
      <View style={{ width: 320, height: 200, padding: 20 }}>
        <LineChart
          style={{ flex: 1 }}
          data={data}
          xAccessor={({ item }) => item.date}
          yAccessor={({ item }) => item.value}
          gridMin={0}
          contentInset={{ top: 10, bottom: 10 }}
          svg={{ stroke: "rgb(134, 65, 244)" }}
        >
          <Grid />
        </LineChart>
        <XAxis
          style={{ marginHorizontal: -10 }}
          data={data}
          scale={Scale.scaleTime}
          xAccessor={({ item }) => item.date}
          formatLabel={itemDate => dateFns.format(itemDate, "HH:mm")}
          numberOfTicks={6}
          contentInset={{ left: 10, right: 10 }}
          svg={{ fontSize: 9, fill: "black" }}
        />
      </View>
    );
  }
}

export default XAxisDemo;
```

**Comment by alburdette619** [comment]
I'm having this issue too.  The axis labels bunch up on the left side, drawing over one another.  If I set `scaleBand` The last label is at the absolute midpoint of the graph.

**Comment by JesperLekland** [comment]
*Update*

You should also use the same `xScale` for the lineChart, in this case it works out anyway, but just because of the fact that you're dates are uniformly spaced. 

`numberOfTicks` is to blame for the fact that the last time isn't displayed. What I would do is to circumvent this by passing a different data array to the `XAxis` e.g `[ 00:00, 06:00, 12:00, 18:00, 24:00]` and just omit the `numberOfTicks` prop. This way they axis will align with the chart and will display exactly the times you want (regardless of the original data).

**Comment by markedup** [comment]
@alburdette619 Good catch regarding `Date` string vs. object. I hadn't discerned that from the parts of the D3 documentation I read previously.

And many thanks @JesperLekland, really appreciate you looking into this and the excellent feedback. I'll go with making a subset of the dates in my overall data set exclusively for the `XAxis` component.
