### ISSUE TITLE
`textAnchor` `left` throws fatal error on Android through Expo

### ISSUE THREAD

**Issue by dextermb** [JesperLekland/react-native-svg-charts#203]
### What is the problem?
When using `textAnchor` and setting it to `left` it throws a fatal error when testing through expo.

### When does it happen?
I assume it is whenever a axis (I'm using `YAxis`) is mounted with `textAnchor` set to `left`.

### What platform?

* [ ] iOS 
* [x] Android

I do not seem to get the issue when testing on an iOS simulator.

React Native version: `0.54.0`

### Code to reproduce

```javascript
<YAxis
	data={[ 'a', 'b' ]}
	contentInset={{ top: 20, bottom: 20, marginRight: 20 }}
	svg={{
		fill:       'grey',
		fontSize:   10,
		textAnchor: 'left',
		x:          0
	}}
	numberOfTicks={5}
	formatLabel={label => `${label}`}
/>
```

### Stacktrace (if crash)
```
Uncaught Error: No enum constant
abi26_0_.host.exp.exponent.modules.api.components.svg.TextAnchor.left
```

This might be an expo issue, but I'd like to confirm that here before referencing this post elsewhere

**Comment by JesperLekland** [comment]
This is probably an issue in `react-native-svg` and not this library (we just pass it along to their library). Please post issue with them
