### ISSUE TITLE
Replace interpolatePath with animated path

### ISSUE THREAD

**Issue by mundiallover** [JesperLekland/react-native-svg-charts#21]
It would be awesome to be able to switch to another Path animation. Instead of interpolating the path it would be nice to use something like this instead where the line is drawn.

https://bitbucket.org/ingenuityph/react-native-svg-animations

**Comment by JesperLekland** [comment]
@mundiallover Thanks for your feedback. Had a quick look at it and I don't consider that specific library to be mature enough. Could possibly do something similar in the future but nothing that is prioritized as of now. Feel free to make a PR if you want to implement it yourself.
