### ISSUE TITLE
PieChart - don't want spaces between data.

### ISSUE THREAD

**Issue by asimkhan0** [JesperLekland/react-native-svg-charts#216]
### What is the problem?

I can't see any property which is used to remove those spaces in PieChart.

### What platform?

I have tested it in android.

React Native version: 0.55.4

### Expected result : 
![piechart](https://user-images.githubusercontent.com/39307338/43960507-19d9598e-9c67-11e8-9176-f23e641a2dfa.PNG)

**Comment by JesperLekland** [comment]
use prop `padAngle`, set it to zero
