### ISSUE TITLE
yAxis icons instead of labels?

### ISSUE THREAD

**Issue by niklassaers** [JesperLekland/react-native-svg-charts#218]
Thanks for making a fantastic library. I really enjoy using it.

For a graph I'm creating, I want the yAxis to show icons instead of a label. I haven't found a way to cram that into formatLabel. Are there other ways to go about it?

In my specific case I'm making a "mood-meter" that shows a graph of my mood over time, from unhappy to happy, where unhappy is an image of a sad smiley and happy is an image of a happy smiley. I also want to make similar graphs for other properties such as energised or not.

Currently running v5.2.0

**Comment by raideltorres** [comment]
ok, first of all this code I will paste won't work with copy paste bc it will be missing several pieces and it will have a lot of unnecessary things, but I would say to do something like this 

```
const CustomFaces = ({ x, y, data, ticks }) => {
  return <G>
    {
      ticks.map((tick, index) => {
        let yValue = (index + 1) * 25 * -1;

        return <Image
                      key={ tick }
                      x={'90%'}
                      y={yValue}
                      width={20}
                      height={20}
                      href={require('./face.jpg')} />
      })
    }
  </G>
}

<LineChart
  style={styles.graph}
  data={data}
  animate={true}
  numberOfTicks={3}
  contentInset={contentInset}
  curve={shape.curveCardinal.tension(0.25)}
  svg={{ stroke: strokeColor, strokeWidth: 2 }}
>
  <CustomGrid />
  <CustomFaces />
</LineChart>
```

Again sorry for not putting the entire code, but I was with other pressing stuff.

**Comment by niklassaers** [comment]
Thanks a bunch, I hadn't thought of doing it this way, I'll absolutely follow your lead. :-) Thanks again
