### ISSUE TITLE
Tried to register two views with the same name RNSVGPath

### ISSUE THREAD

**Issue by ivanherve** [JesperLekland/react-native-svg-charts#220]
### What is the problem?

I'm trying to use the PieChart component with labels for my RN application, exactly the same as the example on that link [https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/pie-chart/with-centered-labels.js](url)

With that const Labels as followed : 
``const Labels = ({ slices, height, width }) => {
            return slices.map((slice, index) => {
                const { labelCentroid, pieCentroid, data } = slice;
                return (
                    <Text
                        key={index}
                        x={pieCentroid[ 0 ]}
                        y={pieCentroid[ 1 ]}
                        fill={'white'}
                        textAnchor={'middle'}
                        alignmentBaseline={'middle'}
                        fontSize={24}
                        stroke={'black'}
                        strokeWidth={0.2}
                    >
                        {data.amount}
                    </Text>
                )
            })
        }```

Which use a component called Text from `react-native-svg` library.

### What happens?
When I include it in my router.js file (which manage the navigation of all pages) and try to execute the app, i'm getting this message.
![image](https://user-images.githubusercontent.com/23102351/44434799-56dc3f00-a5ad-11e8-84d8-2896f7ef2d0f.png)
I think it's because it's confusing with the RN Text component so there's a kind of confilt.

### What platform?
I have the same problem in both platforms

* [ ] iOS 
* [ ] Android 

React Native version: 0.xx

### Code to reproduce

```javascript
import React from 'react'
import { Text } from 'react-native' // Conflit HERE
import { PieChart } from 'react-native-svg-charts'
import { Text } from 'react-native-svg' // AND HERE

class PieChartWithCenteredLabels extends React.PureComponent {

    render() {

        const data = [
            {
                key: 1,
                amount: 50,
                svg: { fill: '#600080' },
            },
            {
                key: 2,
                amount: 50,
                svg: { fill: '#9900cc' }
            },
            {
                key: 3,
                amount: 40,
                svg: { fill: '#c61aff' }
            },
            {
                key: 4,
                amount: 95,
                svg: { fill: '#d966ff' }
            },
            {
                key: 5,
                amount: 35,
                svg: { fill: '#ecb3ff' }
            }
        ]

        const Labels = ({ slices, height, width }) => {
            return slices.map((slice, index) => {
                const { labelCentroid, pieCentroid, data } = slice;
                return (
                    <Text
                        key={index}
                        x={pieCentroid[ 0 ]}
                        y={pieCentroid[ 1 ]}
                        fill={'white'}
                        textAnchor={'middle'}
                        alignmentBaseline={'middle'}
                        fontSize={24}
                        stroke={'black'}
                        strokeWidth={0.2}
                    >
                        {data.amount}
                    </Text>
                )
            })
        }

        return (
            <PieChart
                style={{ height: 200 }}
                valueAccessor={({ item }) => item.amount}
                data={data}
                spacing={0}
                outerRadius={'95%'}
            >
                <Labels/>
            </PieChart>
        )
    }

}

export default PieChartWithCenteredLabels
```

**Comment by JesperLekland** [comment]
Why would you import the `Text` from `react-native`?

**Comment by ivanherve** [comment]
If i want to add some description under the chart. Maybe I can only use `Text` from `react-native-svg`, but the problem is that I use `Text from react-native` in other pages and when I import the class `PieChartWithCenteredLabels` in my `router.js` file (A file that manage the navigation of all my project's pages) I still get this error unfortunately

**Comment by JesperLekland** [comment]
you can do `import { Text as RNText } from 'react-native` or `import { Text as SVGText } from 'react-native-svg`. This is a common ES6 rename import

**Comment by lshivanil1986** [comment]
When I include it in my react-native-svg-animations file and  react-native-svg file, i'm getting this message.
Tried to register two views with the same name RNSVGPath register
