### ISSUE TITLE
LineChart with the same data

### ISSUE THREAD

**Issue by raideltorres** [JesperLekland/react-native-svg-charts#221]
### What is the problem?
I can't render a custom grid or even the default grid if all the data is the same.

Example: `data=[10, 10, 10, 10, 10, 10, 10, 10, 10, 10]`

### When does it happen?

Just create a LineChart with the data explained before, like this

```
<LineChart
  style={styles.graph}
  data={data}
  animate={true}
  numberOfTicks={3}
  contentInset={contentInset}
  curve={shape.curveCardinal.tension(0.25)}
  svg={{ stroke: strokeColor, strokeWidth: 2 }}
>
  <CustomGrid />
</LineChart>
```

### What platform?

* [x] iOS 
* [x] Android (Not tested, but I think is the same)

**Comment by JesperLekland** [comment]
This data has no extent and as such has zero height. Add `yMax` and `yMin` props to chart.

**Comment by raideltorres** [comment]
Yeah I forgot to update this ticket sorry.

I tried with `yMax` and `yMin` but those did not worked for me for some reason so I ended using `gridMax` and `gridMin`

**Comment by JesperLekland** [comment]
Then I'm assuming you're not on the latest version?

**Comment by raideltorres** [comment]
yeah, I'm on 5.2.0
