### ISSUE TITLE
Multicoloured line in linechart?

### ISSUE THREAD

**Issue by chrismatchett** [JesperLekland/react-native-svg-charts#222]
Many thanks for react-native-svg-charts.

Are there existing properties which would allow me to have a multi coloured line in a linechart i.e. red, yellow and green dependent on where line is between three thresholds?

If that's not the case can I create a custom grid and colour the thresholds there?

Chris

**Comment by raideltorres** [comment]
I think you could use something like this . . . but I have not applied this to the library

https://stackoverflow.com/questions/29335354/filling-an-svg-path-with-multiple-colors

**Comment by usrbowe** [comment]
Closing since this issue is inactive.

But for reference, we can use gradient to draw a multi coloured line:
https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/line-chart/with-gradient.js
