### ISSUE TITLE
Multiple Area Chart Decorator onPress Issue

### ISSUE THREAD

**Issue by kashifsulaiman** [JesperLekland/react-native-svg-charts#226]
### What is the problem?
The onPress event triggers of the Decorator(Circle) for the only overlap Chart. I need the onPress event for the another chart too.

### When does it happen?
When we've multiple area chart. Implement this example 
https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/layered-charts.js

### What platform?

* [x] iOS 
* [x] Android 

React Native version: latest

**Comment by usrbowe** [comment]
Closing since this issue is stale. Feel free to reopen with reproducible code.
