### ISSUE TITLE
Gradient Line for Area chart

### ISSUE THREAD

**Issue by emretekince** [JesperLekland/react-native-svg-charts#24]
Hi,
How can I make the line gradient for Area charts?
renderGradient only effects the area. I also want the line to have gradient effect.

**Comment by JesperLekland** [comment]
Hi! 

That's not supported at the moment. I did a quick implementation just now and will push any minute. Feel free to test that branch out. I will need some more testing before merging to master

**Comment by JesperLekland** [comment]
Merged and release in v.2.2.1
