### ISSUE TITLE
longest Y value and first X label showing twice on Android

### ISSUE THREAD

**Issue by mtettmar** [JesperLekland/react-native-svg-charts#248]
I'm using BarChart and finding that on Android, the largest Y value and the first X axis label are always showing twice. I'm running RN 0.57.2. 

It seems this line in x-axis.js and y-axis.js is the culprit:
                    <Text style={{ color: 'transparent', fontSize: svg.fontSize }}>

It is fixed by changing to:

                    <Text style={{ color: 'transparent', opacity: 0, fontSize: svg.fontSize }}>

I guess there must be a difference in how 'transparent' works between Android and iOS. There may be a way round this by setting the container object style but the above was the simplest fix for me.

**Comment by alburdette619** [comment]
Having this issue also, about to submit a PR.

**Comment by usrbowe** [comment]
PR #256 was merged, considering as resolved.
