### ISSUE TITLE
Regarding Displaying Layered LineCharts

### ISSUE THREAD

**Issue by nayfusaurus** [JesperLekland/react-native-svg-charts#251]
Just wanted to say thank you for a good charting library.

### What is the problem?

I am facing a small issue, and am not sure whether I am coding it right. I have coded a Layered LineChart, however when using the same data, the scaling of the 2nd line onwards is a bit off. I have read through other similar issues about it by using gridMin/gridMax & yMin/yMax, however the error still persists on Android phones. On iOS simulator, the alignment looks alright.

Image of the unaligned chart on android simulator
<img width="359" alt="screen shot 2018-10-26 at 3 53 18 pm" src="https://user-images.githubusercontent.com/35911760/47553249-201dfe80-d939-11e8-847e-4d248d5203b7.png">

Image of the unaligned chart on my HTC u11 phone
![photo6237862758586624085](https://user-images.githubusercontent.com/35911760/47553275-3af07300-d939-11e8-86d4-fc9137ac55ce.jpg)

### When does it happen?
Just loading the page using static values

### What platform?

* [ iphone X - 11.4 - simulator] iOS 
* [ Android 6 - simulator ] Android 
* [ Android 8 - HTC u11 ] Android

React version: 16.6.0-alpha.8af6728
React Native version: 0.57.3
React Native SVG version: 8.0.8
React Native SVG Charts version: 5.2.0

### Code to reproduce

[https://github.com/nayfusaurus/react-native-chart-comparison/tree/master/App/LineChart](https://github.com/nayfusaurus/react-native-chart-comparison/tree/master/App/LineChart)

**Comment by alburdette619** [comment]
#240 addresses this and adds support for a multi-line graph

**Comment by usrbowe** [comment]
PR #240 was merged, considering this as resolved.
