### ISSUE TITLE
Stacked Line Chart

### ISSUE THREAD

**Issue by mchen37** [JesperLekland/react-native-svg-charts#26]
Hi, is it possible to draw multiple LineCharts over each other? I'm currently trying to do something of the sort but can't get it to work. Is it possible to draw multiple lines with LineChart or will I need something like a StackedLineChart? (Which does not currently exist)

**Comment by JesperLekland** [comment]
Check the doc for "layered charts".

**Comment by mchen37** [comment]
@JesperLekland Ah yes, I forgot about gridMin/gridMax, thanks! I had them layered manually but couldn't figure out how to give them the same Y scale.
