### ISSUE TITLE
PieChart isn't importing Path from animated-path.js

### ISSUE THREAD

**Issue by carlost** [JesperLekland/react-native-svg-charts#261]
using:
- v5.2.0 of react-native-svg-charts - although this issue also appears in master and dev
- v6.3.1 of react-native-svg - although this issue extends to all versions since 6.3.1

You can see that `PieChart` imports `Path` from `react-native-svg` [here](https://github.com/JesperLekland/react-native-svg-charts/blob/v5.2.0/src/pie-chart.js#L5).:

```javascript
import Svg, { G, Path } from 'react-native-svg'
```

The `PieChart` component passes an `animationDuration` prop to the `react-native-svg` `Path` component as part of its render method on [line 148](https://github.com/JesperLekland/react-native-svg-charts/blob/v5.2.0/src/pie-chart.js#L148):

```javascript
<Path
  key={ key }
  onPress={ onPress }
  { ...svg }
  d={ arcs[ index ](slice) }
  animate={ animate }
  animationDuration={ animationDuration }
/>
```

`animationDuration` is *not* a prop on the `Path` component exported from `react-native-svg`.  It was easier to verify in `react-native-svg`'s JS code that `animatedDuration` was not a supported property before v8.0.0 ... when the components props were verified via `PropTypes`.  Now the props are just passed directly to the native components.  However, you can see [in the TypeScript definition file](https://github.com/react-native-community/react-native-svg/blob/v8.0.8/index.d.ts) that Path doesn't have an `animatedDuration` prop.

All of the other charts, except `PieChart`, use the `animated-path.js` `Path` decorator when working with svg `Path` components. `animated-path.js` wraps an `react-native-svg` `Path` component and adds some animation magic.

I suspect that this was the cause for issue #27 that was created when someone couldn't get the `PieChart` animations working.

Let me know if this is correct and if you would like me to issue a PR.

**Comment by carlost** [comment]
One last thing that i forgot to mention ... `animated-path.js` needs to be updated so that it doesn't pass the `animationDuration` prop to the underlying `react-native-svg` `Path` component.

**Comment by carlost** [comment]
One more last thing :) . You would need to scrub all of the special animation props that animated-path excepts above and beyond the standard svg props: animate, animationDuration, and renderPlaceholder.

**Comment by JesperLekland** [comment]
I'm not sure what the issue is here? The passed props would just be ignored by `react-native-svg` anyway.

**Comment by usrbowe** [comment]
Closing stale issue.
