### ISSUE TITLE
Layered chart misalignment with different data

### ISSUE THREAD

**Issue by oste** [JesperLekland/react-native-svg-charts#262]
### What is the problem?

Changing the data on the [layered example](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/b04ba1443f32f6cf2808adb47d0a7911c5dd589c/storybook/stories/layered-charts.js) causes a misalignment as seen in this screenshot.

<img width="390" alt="screen shot 2018-11-09 at 12 07 17 
am" src="https://user-images.githubusercontent.com/350275/48244396-95ff7c80-e3b3-11e8-8327-69bd15acdf9c.png">

### When does it happen?
When switching the example data to this. The data points in the beginning are the same so its easy to see the alignment.

>     const data  = [ 50, 40, 40, 45, -4, -24, 85, 91, 35, 53, -53, 24, 50, -20, -80 ]
>     const data2 = [ 50, 40, 40, 45, -4, -24, 35, 61, 25, 63, -33, 24, 70, -70, -70 ]    

### What platform?

* [x] iOS 10

React Native version: 0.57

### Code to reproduce

```javascript
import React from 'react'
import { AreaChart, Grid } from 'react-native-svg-charts'
import * as shape from 'd3-shape'
import { StyleSheet, View } from 'react-native'

class LayeredChartsExample extends React.PureComponent {

    render() {

       const data  = [ 50, 40, 40, 45, -4, -24, 85, 91, 35, 53, -53, 24, 50, -20, -80 ]
       const data2 = [ 50, 40, 40, 45, -4, -24, 35, 61, 25, 63, -33, 24, 70, -70, -70 ]    

        return (
            <View style={ { height: 200 } }>
                <AreaChart
                    style={ { flex: 1 } }
                    data={ data }
                    svg={{ fill: 'rgba(134, 65, 244, 0.5)' }}
                    contentInset={ { top: 20, bottom: 20 } }
                    curve={ shape.curveNatural }
                >
                    <Grid/>
                </AreaChart>
                <AreaChart
                    style={ StyleSheet.absoluteFill }
                    data={ data2 }
                    svg={{ fill: 'rgba(34, 128, 176, 0.5)' }}
                    contentInset={ { top: 20, bottom: 20 } }
                    curve={ shape.curveNatural }
                />
            </View>
        )
    }

}

export default LayeredChartsExample
```

**Comment by JesperLekland** [comment]
You need to have the same `yMin` and `yMax` for mulitple charts to align properly
