### ISSUE TITLE
Is is possible to plot line chart with some missing data.

### ISSUE THREAD

**Issue by juligupta** [JesperLekland/react-native-svg-charts#266]
I have daily plotted data but it might be missing for one of the days in week. Any way that we can also skip that data point and the line continues from one data point to next.

Also if in a week, I have data coming in from Wednesday, start the line graph plotting also from Wednesday

Something like this
![img_3e9be8250850-1](https://user-images.githubusercontent.com/23554683/48933871-d3bde280-ef27-11e8-846c-abdf3ca2b64e.jpeg)

**Comment by JesperLekland** [comment]
I'm not entirely sure I understand the question. But yes you can simply pass in undefined as a value and that value will be skipped. Or as you've stated yourself you can alter the original data set to do what you want.
