### ISSUE TITLE
How do animations work? I set animated=true and animationDuration=500 and there is not animation

### ISSUE THREAD

**Issue by escobar5** [JesperLekland/react-native-svg-charts#27]
### What is the problem?
Animations don't work

### When does it happen?
Immediately on render

### What platform?
Android 6.0

React Native version: 0.52

### Code to reproduce
With the example of a Pie chart in readme.md

**Comment by mchen37** [comment]
It looks like animation isn't even available for PieChart as it uses the basic Path from react-native-svg in the source code and not the animated-path.js that other charts use. I saw that ProgressCircle was using animated-path.js so I tested it to see how the animation looks. The initial load looks good but when I change the progress, the animation moves in a strange way.

Could we get animations fixed for PieChart and ProgressCircle?

**Comment by JesperLekland** [comment]
Animations occur when the dataset changes, i.e not from null -> data. It works by calculating a tween between the two svg paths. The animations aren't the best and haven't been worked on that much

**Comment by JesperLekland** [comment]
On further investigation it might actually be `PieChart` that is causing trouble. Either way this will be a "no fix" for now as the animations don't behave particularly well anyway

**Comment by v-vashchenko** [comment]
Hello! Have a try with "animate"
