### ISSUE TITLE
Inset of graph problem (Areachart)

### ISSUE THREAD

**Issue by webdevsyd** [JesperLekland/react-native-svg-charts#273]
### What is the problem?
I have an issue wherein if I put a contentinset to the AreaChart it messed up with the background that I have below the chart, is there a way that I put a content inset in the chart the background still exists in the left and right side?

**Screenshot**
This is what I have after I add the contentinset
<img width="419" alt="screen shot 2018-12-02 at 10 01 34 am" src="https://user-images.githubusercontent.com/15810023/49334850-dfda2c00-f61a-11e8-9f9c-00f2eb953704.png">

This is what I want to achieve which doesn't have the content inset, however the problem is the ticker which is not fully displayed.
<img width="427" alt="screen shot 2018-12-02 at 10 02 07 am" src="https://user-images.githubusercontent.com/15810023/49334899-f8971180-f61b-11e8-8e5b-92f45f2fc970.png">

### What platform?
Any IOS Version

React Native version: 0.57

### Code to reproduce

```javascript
import React, {Component, Fragment} from 'react'
import {AreaChart, XAxis} from 'react-native-svg-charts'
import {Circle, G} from 'react-native-svg'
import {GREEN} from '../../config/colors'
import * as shape from 'd3-shape'

class Graph extends Component {
  render() {
    const data = [18, 20, 30, 40, 33, 42, 50]
    const month = ['Jun', 'Jul', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec']

    const Tooltip = ({x, y}) => (
      <G x={x(6) - (75 / 2)}>
        <G x={75 / 2}>
          <Circle
            cy={y(data[6])}
            r={6}
            stroke={GREEN}
            strokeWidth={3}
            fill={'white'}
          />
        </G>
      </G>
    )

    return (
      <Fragment>
        <XAxis
          style={{marginTop: 50}}
          data={data}
          formatLabel={(value, labelIndex) => month[labelIndex]}
          contentInset={{left: 25, right: 25}}
          svg={{fontSize: 14, fill: 'white'}}
        />
        <AreaChart
          style={{height: 130}}
          data={data}
          curve={shape.curveNatural}
          contentInset={{top: 30, bottom: 20, left: 25, right: 25}}
          svg={{fill: '#0B6A76', fillOpacity: 1}}
        >
          <Tooltip />
        </AreaChart>
      </Fragment>
    )
  }
}

export default Graph

**Comment by JesperLekland** [comment]
well no. Since you're adding content inset the content is effectively moved in. Removing the contentInset on the AreaChart would do the trick. Your XAxis might misalign slighlty but you could just displace the "tooltip" instead
