### ISSUE TITLE
Axes should pass down layout props like charts for children

### ISSUE THREAD

**Issue by alburdette619** [JesperLekland/react-native-svg-charts#275]
### What is the problem?

The axes support children but do not pass down their layout props to the children for ease of layout.  This would force the user to emulate the layout procedure done by the axis to layout children along side the ticks. 

### When does it happen?
In every case.

### What platform?

* [x] iOS
* [x] Android

**Comment by alburdette619** [comment]
Taking care of it ;)

**Comment by usrbowe** [comment]
Closing, since PR #276 merged.
