### ISSUE TITLE
StackedAreaChart Animation blinking

### ISSUE THREAD

**Issue by callmejm** [JesperLekland/react-native-svg-charts#277]
### What is the problem?
StackedAreaChart animation have a blinking issue

### When does it happen?
When changing the data value 

### What platform?

* [ ] iOS 
* [x] Android 

React Native version: 0.57.7

### Code to reproduce

```javascript
// put code here
  componentDidMount(){
      setInterval(() => {
          this._addValue();
      }, 1000);
  }

  _addValue = () =>{
      this.setState({
        data : [
            {
                month: new Date(2015, 0, 1),
                apples: Math.random(),
            },
            {
                month: new Date(2015, 1, 1),
                apples: Math.random(),
            },
            {
                month: new Date(2015, 1, 1),
                apples: Math.random(),
            },
            {
                month: new Date(2015, 1, 1),
                apples: Math.random(),
            }
        ]
      });
  }

<StackedAreaChart
    style={ { height: 200, paddingVertical: 16 } }
    animate={true}
    data={ this.state.data }
    keys={ keys }
    colors={ colors }
    curve={ shape.curveNatural }
    showGrid={ false }
    svgs={ svgs }
 />
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6957533/49635684-7e132b00-fa3b-11e8-8e28-a754cf91d9a5.gif)

**Comment by JesperLekland** [comment]
The animation implementation is highly experimental and not something we're working actively on. From the video I can't see the use for the stacked area chart though? Looks like a regular area chart.

**Comment by likern** [comment]
> The animation implementation is highly experimental and not something we're working actively on. From the video I can't see the use for the stacked area chart though? Looks like a regular area chart.

@JesperLekland is this developed with `Animated` RN library? Or is it pure JavaScript animation?

**Comment by usrbowe** [comment]
Closing, since PR #329 was merged.
