### ISSUE TITLE
No component found for view with name 'RNSVGPath'

### ISSUE THREAD

**Issue by luchoster** [JesperLekland/react-native-svg-charts#28]
I'm getting this error, after installing, linking and running 

```
<ProgressCircle
    style={ { height: 200 } }
    progress={ 0.7 }
    progressColor={'rgb(134, 65, 244)'}
/>
```
React Native: 0.51
svg: 6.0.1-rc.3
svg-charts: 2.1.0

![simulator screen shot - iphone 6 - 2018-01-19 at 12 56 42](https://user-images.githubusercontent.com/694367/35171286-1f895148-fd18-11e7-8895-22fe37787252.png)

**Comment by JesperLekland** [comment]
It looks like you might have failed to link `react-native-svg`. Also try not to use pre-release versions.

**Comment by JesperLekland** [comment]
I'll go ahead and close this due to inactivity. Feel free to re-open an issue if you can't get it to work.
