### ISSUE TITLE
How to stack charts?

### ISSUE THREAD

**Issue by mykelaballe** [JesperLekland/react-native-svg-charts#282]
What I want to do is put a put a Line Chart on top of a Bar Chart

![image](https://user-images.githubusercontent.com/22584900/49790418-1590ba80-fd69-11e8-901f-c94442d582a7.png)

**Comment by JesperLekland** [comment]
Absolutely position two charts on top of each other and you're good to go.

**Comment by vishal767** [comment]
it's working with hot reloading..but not reflecting in build version or when i reload in dev mode

**Comment by FirdousNath** [comment]
It didn't work work for me
` render() {

        const data = [0, 10, 40, 5, 10, 30];

        const axesSvg = {fontSize: 10, fill: '#000'};
        const verticalContentInset = {top: 10, bottom: 10};
        const xAxisHeight = 30;

        // Layout of an x-axis together with a y-axis is a problem that stems from flexbox.
        // All react-native-svg-charts components support full flexbox and therefore all
        // layout problems should be approached with the mindset "how would I layout regular Views with flex in this way".
        // In order for us to align the axes correctly we must know the height of the x-axis or the width of the x-axis
        // and then displace the other axis with just as many pixels. Simple but manual.

        return (
            <View style={{height: 200, padding: 20, flexDirection: 'row'}}>
                <YAxis
                    data={data}
                    style={{marginBottom: 15}}
                    contentInset={verticalContentInset}
                    svg={axesSvg}
                />
                <View style={{flex: 1, marginLeft: 10}}>

                    <LineChart
                        style={{flex: 1}}
                        data={data}
                        contentInset={verticalContentInset}
                        svg={{stroke: 'rgb(134, 65, 244)'}}

                    >
                        <Grid/>
                    </LineChart>
                    <XAxis
                        style={{marginHorizontal: -10}}
                        data={data}
                        formatLabel={(value, index) => index}
                        contentInset={{left: 10, right: 10}}
                        svg={axesSvg}
                    />
                    <LineChart
                        style={{ flex: 1, position: "absolute"}}
                        data={data}
                        svg={{stroke: 'rgb(1, 1, 1)'}}

                    >
                    </LineChart>
                </View>
            </View>
        )
    }`
![screenshot_2018-12-28-13-08-04-441_com cdg](https://user-images.githubusercontent.com/19954996/50507057-ca351680-0aa1-11e9-9747-66ba5b90a7cb.png)

**Comment by mazenchami** [comment]
@FirdousNath any luck with fixing the stacking issue? can you please post your code?

**Comment by mazenchami** [comment]
@FirdousNath any luck with fixing the stacking issue? can you please post your code?
