### ISSUE TITLE
need fake padding instead of fake margin

### ISSUE THREAD

**Issue by vikrantnegi** [JesperLekland/react-native-svg-charts#287]
### What is the problem?
Need content inset to add fake padding instead of fake margin

### When does it happen?
Area chart with decorators being cut off at the extreme edges

### Current Senario
![areachart](https://user-images.githubusercontent.com/3294287/50674478-b5f69980-100c-11e9-9374-6add64fe04e7.png)

### Possible fix with content Inset
![possible-fix](https://user-images.githubusercontent.com/3294287/50674526-2998a680-100d-11e9-8cfb-cfa4479cc393.png)

### Desired Fix using fake padding
![desired](https://user-images.githubusercontent.com/3294287/50674690-982a3400-100e-11e9-811e-0f9a9f67e677.png)

React Native version: 0.57.7

### Code to reproduce
Area chart example.

Is there a way we can add fake padding instead of fake margin so that the chart fill color starts at extreme edges?

**Comment by JesperLekland** [comment]
`contentInset` doesn't actually add padding nor margin, it just starts the draw further into the svg canvas. And since you ultimately place the decorators yourself you could easily displace them by as much as you want.

**Comment by vikrantnegi** [comment]
Thank for the quick response.

both the area chart and decorators use the same data array. If I offset the decorators then they will not align correctly with the charts.

Thoughts?

**Comment by JesperLekland** [comment]
Well your "desired fix" is just that, something that doesn't align. But how is using the contentInset an actual problem? It does just what you want, let's the decorators "stick out" from the chart

**Comment by scerelli** [comment]
@JesperLekland you're right but visually it change a lot. With a "padding" you would have the background expanding also at the bottom of the svg.

I've the same problem look at mine:
![chart](https://i.imgur.com/8DzsIv9.png)

the svg starts at the very bottom of the white card and has a content inset so i've this ugly border that links x(0) and x(data.length - 1). 
With a padding the background would start at bottom 0 and the first point would has been drawn at bottom: 0+N, for example

**Comment by vikrantnegi** [comment]
We managed to solve this issue by creating duplicating the first and the last data x-axis points and then hiding chart points for first and last. Doing this I was able to offset the chart horizontally

**Comment by JesperLekland** [comment]
@scerelli Wait why do you have the bottom contentInset? And also the line in can easily be removed by using a decorator instead of borderWidth on the area, [see example](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/area-chart/with-line.js).

@vikrantnegi Glad you fixed it but still not sure I understand the problem

**Comment by usrbowe** [comment]
Closing, as the main issue seems to be solved. Please feel free to reopen, if you need further guidance.
