### ISSUE TITLE
Donut chart doesn't build on Android

### ISSUE THREAD

**Issue by SundeepToor** [JesperLekland/react-native-svg-charts#289]
### What is the problem?
App builds 'successfully' in the terminal. Get the following error on NEXUS 5X API 26 (1080x1920 Android 8.0) simulator:
'Error while updating property 'y' of a view managed by: RNSVGText

null

For input string: "0.7r"
updateViewProp
    ViewManagersPropertyCache.java:92
setProperty
    ViewManagerPropertyUpdater.java:129
updateProps
    ViewManagerPropertyUpdater.java:48
updateProperties
    ViewManager.java:32
createView
    NativeViewHierarchyManager.java:232
execute
    UIViewOperationQueue.java:152
run
    UIViewOperationQueue.java:815
flushPendingBatches
    UIViewOperationQueue.java:928
access$2100
    UIViewOperationQueue.java:46
doFrameGuarded
    UIViewOperationQueue.java:988
doFrame
    GuardedFrameCallback.java:29
doFrame
    ReactChoreographer.java:134
doFrame
    ChoreographerCompat.java:105
run
    Choreographer.java:909
doCallbacks
    Choreographer.java:723
doFrame
    Choreographer.java:655
run
    Choreographer.java:897
handleCallback
    Handler.java:789
dispatchMessage
    Handler.java:98
loop
    Looper.java:164
main
    ActivityThread.java:6541
invoke
    Method.java
run
    Zygote.java:240
main
    ZygoteInit.java:767
'

### When does it happen?
When I try to build the react native app using yarn android
### What platform?
Android has problems, works on iOS

* [ ] iOS 
* [x ] Android 

React Native version: ~0.55.2

### Code to reproduce
App.js file
```javascript
import React from 'react';
import { StyleSheet, Text, View, FlatList, ScrollView } from 'react-native';
import Donut from './Donut';

export default class App extends React.Component {
  render() {
    return (
      <View>
        <ScrollView>
          <View style={styles.donutcontainer}>
            <Donut />
          </View>
        </ScrollView>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  donutcontainer: {
    height: 200
  },
  container: {
    height: 70
  },
  table: {
    height: '100%',
    width: '100%'
  }
});

```
Donut.js
```javascript
import React from 'react';
import { StyleSheet, View } from 'react-native';
import { PieChart } from 'react-native-svg-charts';
import { Text } from 'react-native-svg';

export default class Donut extends React.Component {
  render() {
    const data = [
      {
        key: 1,
        amount: '5',
        svg: { fill: '#FEC745' }
      },
      {
        key: 2,
        amount: '3',
        svg: { fill: '#0598C3' }
      }
    ];
    function totalClicks(arr, type) {
      return arr.reduce((total, obj) => {
        if (typeof obj[type] === 'string') {
          return total + Number(obj[type]);
        }
        return total + obj[type];
      }, 0);
    }

    let totalAmount = totalClicks(data, 'amount');

    const Labels = ({ slices, height, width }) => {
      return slices.map((slice, index) => {
        const { labelCentroid, pieCentroid, data } = slice;
        return (
          <Text
            key={index}
            fill={'black'}
            textAnchor={'middle'}
            alignmentBaseline={'middle'}
            fontSize={'1.3rem'}
            y={'-0.5rem'}
          >
            {/*{data.amount}*/}
            {totalAmount}
            <Text y={'0.7rem'} fontSize={'0.7rem'}>
              Moments
            </Text>
          </Text>
        );
      });
    };

    return (
      <View style={styles.container}>
        <PieChart
          style={{
            height: '100%',
            flex: 1
          }}
          valueAccessor={({ item }) => item.amount}
          data={data}
          spacing={0}
          outerRadius={'95%'}
        >
          <Labels />
        </PieChart>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    height: '100%',
    borderWidth: 5,
    borderColor: 'red',
    justifyContent: 'center',
    alignItems: 'center'
  }
});
```

**Comment by CuteManiMca** [comment]
import Text into 'react-native'
import  { StyleSheet, View ,Text } from 'react-native';

**Comment by usrbowe** [comment]
Closing due to no response from author.
