### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Taylor123** [JesperLekland/react-native-svg-charts#290]
Commented on a commit, but wondering when a new release will be made. Looking for a particular bug fix that's in `dev`.

If bandwidth is the issue, happy to help contribute a bit and get a release going. Thanks!

**Comment by jnicholls** [comment]
Also wondering this. There's a lot of fixes in dev that deserve to be published to NPM.

**Comment by JesperLekland** [comment]
I agree with you guys. I haven't gotten around to cut a new release yet. I'm not actively maintaining this library as I'm busy with running a startup at the moment. Will try to set up an automatic release script when merging to master and bringing in some contributors to make sure we get active contributions. Any takers?

**Comment by JesperLekland** [comment]
Meanwhile you could just point your `package.json` dependency directly to `dev`

**Comment by Taylor123** [comment]
@JesperLekland I can help do releases and maintain. I don't know how much time I would be able to contribute to new features outside what I'm looking to use the lib for, but happy to help keep releases on track and the community progressing this library.

Would prefer to keep pulling from the npm registry when possible :)

**Comment by usrbowe** [comment]
Closing, most recent release `5.3.0` was made after this issue.
