### ISSUE TITLE
Show correctly dynamic Max axis value, and scale it correctly 

### ISSUE THREAD

**Issue by Davis22xd** [JesperLekland/react-native-svg-charts#292]
### Show correctly dynamic Max axis value, and scale it correctly 

In this case the yAxis doesn't display the Max value, according to the ticks given I wanted to display all the time the max value,  but when setting it, it is not displayed as the max value

### When does it happen?

Setting max value in y axis for example given a 25 as max value upper 20 and lower than 30 and given  3 as the number of ticks we have this graph:  
<img width="305" alt="screen shot 2019-01-28 at 11 19 37 am" src="https://user-images.githubusercontent.com/6964464/51850443-be7e7f00-22ef-11e9-9cb2-5e08545ba0ce.png">

### What platform?

* [x] iOS 
* [x] Android 

React Native version: 0.57.2

### Code to reproduce

```typescript
import React from 'react';
import { View } from 'react-native';
import { LineChart, XAxis, YAxis } from 'react-native-svg-charts';
import { Line } from 'react-native-svg';
import { lineChartYellow, dotedLine, textGrey } from '../../Styles/Colors';
import R from 'ramda';

const getMaxBalanceValue = (weeklyDailyBalance: Balance[]): number => {
    return maximum(weeklyDailyBalance.map(x => x.balance || 0));
}

function maximum(items: number[]): number {
    return R.reduce(R.max, -Infinity, items);
}

 interface Balance {
    balance: number ;
    dayName: string;
    dayNumber: number;
  };

const HorizontalLine = (({ y }: { y: any; }) => (
    <Line
        key={'x-axis'}
        x1={'0%'}
        x2={'100%'}
        y1={y(0)}
        y2={y(0)}
        stroke={dotedLine}
        strokeWidth={1}
    />
))

const CoinBalanceChart = () => {
    const displayBalance: Balance[] = [ { balance: 22, dayName: 'Mon', dayNumber: 1 },
    { balance: 20, dayName: 'Tue', dayNumber: 2 },
    { balance: 20, dayName: 'Wed', dayNumber: 3 },
    { balance: 20, dayName: 'Thu', dayNumber: 4 },
    { balance: 20, dayName: 'Fri', dayNumber: 5 },
    { balance: 25, dayName: 'Sat', dayNumber: 6 },
    { balance: 25, dayName: 'Sun', dayNumber: 7 } ];

    const yMax = getMaxBalanceValue(displayBalance);

    return (
        <View style={{ flexDirection: 'row', display: "flex" }}>
            <YAxis
                contentInset={{ top: 10, bottom: 10 }}
                data={displayBalance}
                yAccessor={({ item }) => item.balance}
                formatLabel={value => value}
                numberOfTicks={3}
                min={0}
                max={yMax}
                style={{ flex: 0.1, marginBottom: 15 }}
                svg={{
                    fill: textGrey
                }}
            />
            <View style={{ flex: 0.9 }}>
                <LineChart
                    style={{ height: 150 }}
                    data={displayBalance}
                    yAccessor={({ item }) => item.balance}
                    svg={{
                        stroke: lineChartYellow,
                        strokeWidth: 2,
                        clipPath: 'url(#clip-path-1)'
                    }}
                    contentInset={{ top: 10, bottom: 10, left: 10, right: 10 }}
                    yMin={0}
                    yMax={yMax}
                >
                    <HorizontalLine />
                </LineChart>
                <XAxis
                    data={displayBalance}
                    formatLabel={(_, index) => displayBalance[index].dayName}
                    contentInset={{ left: 10, right: 10 }}
                    svg={{
                        fill: textGrey,
                        fontSize: 10,
                    }}
                />
            </View>
        </View>
    )
}

export default CoinBalanceChart;

```

**Comment by JesperLekland** [comment]
You can read up on how the ticks calculation works [here](https://github.com/d3/d3-scale#continuous_ticks). Remove "numberOfTicks" prop if you want specific values. Remember that you can pass in any `data` array you want to `YAxis` it will just render it in respect to its bounds

**Comment by usrbowe** [comment]
Closing, no response from author.

**Comment by hanuk25** [comment]
Hi,

<img width="302" alt="Screenshot 2020-01-10 at 5 29 35 PM" src="https://user-images.githubusercontent.com/57976571/72142042-d3ec9c00-33ce-11ea-944c-bbabbe2df566.png">

import React from 'react'
import { AreaChart, XAxis, Grid,BarChart } from 'react-native-svg-charts'
import { View } from 'react-native'
import * as scale from 'd3-scale'
import * as shape from 'd3-shape'
import dateFns from 'date-fns'
import Moment, { min } from 'moment';
import setHours from 'date-fns/setHours'
import format from 'date-fns/format'

class ExampleGraph extends React.PureComponent {



    render() {

        const data = [
        {
                      date: 1577421956000,
                      value: 0.36
                    },

            {
              date: 1577940356000,
              value: 0.36
            },
 {
               date: 1577508356000,
               value: 0.36
             },
  {
                date: 1577594756000,
                value: 0.36
              },
  {
                date: 1577681156000,
                value: 0.36
              },
  {
                date: 1577767556000,
                value: 0.36
              },
              {
                            date: 1577853956000,
                            value: 0.36
                          },
            {
              date: 1578026756000,
              value: 0.34
            },
            {
              date: 1578113156000,
              value: 0.36
            },
            {
              date: 1578199556000,
              value: 0.29
            },
            {
               date: 1578285956000,
               value: 0.26
            },
            {
                date: 1578458756000,
                value: 0.48
            },
            {
                date: 1578545156000,
                value: 0.36
            },
            {
              date: 1578631556000,
              value: 0.54
            },
        ]

        return (
            <View style={{ height: 200, padding: 20 }}>
                <BarChart
                    style={{ flex: 1 }}
                    data={ data }
                    yAccessor={ ({ item }) => item.value }
                    xAccessor={ ({ item }) => item.date }
                    xScale={ scale.scaleTime }
                    contentInset={{ top: 10, bottom: 10 }}
                    svg={{ fill: 'rgba(134, 65, 244, 0.5)' }}
                    curve={ shape.curveLinear }
                >
                    <Grid/>
                </BarChart>
                <XAxis
                    data={ data }
                    svg={{
                        fill: 'black',
                        fontSize: 8,
                        fontWeight: 'bold',
                        rotation: 20,
                        originY: 30,
                        y: 5,
                    }}
                    xAccessor={ ({ item }) => item.date }
                    scale={ scale.scaleTime }

                    style={{ marginHorizontal: -15, height: 20 }}
                    contentInset={{ left: 10, right: 25 }}
                    formatLabel={ (value) => format(value, 'dd:MMM') }
                />
            </View>
        )
    }

}

In the image I would like to show only few labels instead of showing all the labels present in the data set(need to scale the X-Axis Labels).Some times i need to show DD.MMM for month data or hh:mm for day data for Barcharts,LineCharts.


As i am very new to Graphs can you please tell me how can i achieve this?

Thanks

**Comment by josh-thompson13** [comment]
I'm having the same problem. I removed the number of ticks and get the result seen here : https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/screenshots/both-axes.png
As you can see, the line goes above the highest point on the axis, how can I get it to be accurate whilst still using the default number of ticks. 

Any ideas? 

`<View style={{ height: 600, width: 750, flexDirection: "row" }}>
            <YAxis
                data={data}
                contentInset={contentInset}
                svg={{
                    fill: "black",
                    fontSize: 20,
                }}
                formatLabel={value => `${value}ºC`}
                min={Math.min(...data)}
                max={Math.max(...data)}
            />
            <AreaChart
                style={{ flex: 1, borderColor: "black", borderWidth: 1 }}
                data={data}
                svg={{ fill: "rgb(134, 65, 244)" }}
                contentInset={contentInset}
                yMax={Math.max(...data)}
            >
                <Grid />
                <Line />
            </AreaChart>
        </View>`
