### ISSUE TITLE
How to display data on both axis?

### ISSUE THREAD

**Issue by isaaclem** [JesperLekland/react-native-svg-charts#293]
How to display the data at both axis?

```
 <BarChart
  style={{ height: 200 }}         
  data={[100,200,300,400]}
  svg={{ fill }}
  contentInset={{ top: 30, bottom: 30 }}
>
  <Grid />
</BarChart>
```

<img width="355" alt="screen shot 2019-02-11 at 2 03 43 pm" src="https://user-images.githubusercontent.com/32945572/52547972-ed274a00-2e05-11e9-8934-0baffd7f108e.png">

I'm taking your example code and trying out, wishing to display data on both Y-axis and X-Axis but don't seems to find the correct props? Y-axis is expecting to display from 0 to max of 400 and X-axis is expecting to display months Jan Feb and so on... Thanks in advance

**Comment by BalkrishnaBhatt** [comment]
@isaaclem  How can you show data on both axis? I am facing this issue while I am plotting StackedAreaChart.
