### ISSUE TITLE
Can I custom the bar chart like this? Anyone can help?

### ISSUE THREAD

**Issue by dungdt9x** [JesperLekland/react-native-svg-charts#300]
![screen shot 2019-02-27 at 13 25 06](https://user-images.githubusercontent.com/14542376/53470086-1fd27300-3a93-11e9-9272-7ff87112194d.png)

**Comment by JesperLekland** [comment]
Have a look at the [examples repo](https://github.com/JesperLekland/react-native-svg-charts-examples)

**Comment by dungdt9x** [comment]
Thanks for reply.  I did it!

**Comment by JesperLekland** [comment]
Awesome @dungdt9x 👍
