### ISSUE TITLE
Alert on a bar chart

### ISSUE THREAD

**Issue by LeviRoest** [JesperLekland/react-native-svg-charts#307]
Hey, i've a simple question,

Is it possible to put a onPress Alert tag on every individual bar in a bar chart?

And if possible, how does it work exactly.

**Comment by JesperLekland** [comment]
See [this example](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/with-different-bars.js). Each `svg` prop takes an `onPress`
