### ISSUE TITLE
importing { Text } from react-native-svg & react-native throws duplicate declaration error. Any advice on how to proceed?

### ISSUE THREAD

**Issue by alittletf** [JesperLekland/react-native-svg-charts#308]
### What is the problem?
I was following this pie chart example and noticed that you have to import { Text } from react-native-svg....(https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/pie-chart/with-centered-labels.js)

Well i am using the standard `Text` element that react-native gives out of the box. When I try to build the app, I get a duplicate declaration error.

Is there something someone else is doing to get around this issue? I cant understand why react-native-svg would chosen that as an element name. 

### What platform?

React Native version: 0.58.6
react-native-svg-charts-version: 9.3.5

### Code to reproduce

`import { Text, View} from 'react-native';`
`import { PieChart } from 'react-native-svg-charts'`
`import { Text } from 'react-native-svg'`

using the above throws a duplicate declaration error

**Comment by alittletf** [comment]
Ah....probably should have tried this before posting this issue...

I just created a different file, put the pie chart example in there and then imported the component into the file where i use the out of the box `Text` element from react-native and everything works fine.

**Comment by datvp09** [comment]
you can name it as alias

`import {G, Text as SVGText} from 'react-native-svg'`
