### ISSUE TITLE
How to change bar colors in XAxis?

### ISSUE THREAD

**Issue by tal987** [JesperLekland/react-native-svg-charts#309]
Hi,
In your example for XAxis all the bars are in a purple color:

        <LineChart
                    style={{ flex: 1 }}
                    data={ data }
                    gridMin={ 0 }
                    contentInset={{ top: 10, bottom: 10 }}
                    svg={{ stroke: 'rgb(134, 65, 244)' }}
                >

I would like to change the bar color in a way that if the index of the data is even like(0,2,4,6)
the bar will be red and if its odd(1,3,5) the color of the bar will be yellow.
How can I do that?

Thank you

**Comment by JesperLekland** [comment]
Check the [examples repo](https://github.com/JesperLekland/react-native-svg-charts-examples)

**Comment by usrbowe** [comment]
Closing due to no response from author.
