### ISSUE TITLE
StackedAreaChart Overlap When Using curve.curveNatural

### ISSUE THREAD

**Issue by ecssiah** [JesperLekland/react-native-svg-charts#319]
### What is the problem?
When using the StackedAreaChart, the lines begin to overlap or become discontinuous.

### When does it happen?
It occurs particularly when there are large changes between each data point.

### What platform?
* [x] iOS 12.1
* [ ] Android 

React Native version: 0.58.3
react-native-svg-charts-version: 5.2.0

### Code to reproduce

```javascript
const data = [
  {
    'date': 1553922000000,
    'focus1': 0,
    'focus2': 0,
    'focus3': 0,
  },
  {
    'date': 1554008400000,
    'focus1': 24567,
    'focus2': 0,
    'focus3': 7245,
  },
  {
    'date': 1554094800000,
    'focus1': 0,
    'focus2': 0,
    'focus3': 0,
  },
  {
    'date': 1554181200000,
    'focus1': 12456,
    'focus2': 12000,
    'focus3': 4536,
  },
]

const keys = [ 'focus1', 'focus2', 'focus3' ]

<StackedAreaChart
  style={styles.mainChart}
  yMax={86400}
  contentInset={{ left: 16, right: 12}}
  data={data}
  keys={keys}
  colors={this._getMainChartColors()}
  svgs={this._getMainChartSvgs()}
  curve={shape.curveNatural}
  showGrid={true}
>
  <Grid/>
</StackedAreaChart>
```

![Simulator Screen Shot - iPhone X - 2019-04-04 at 19 42 39](https://user-images.githubusercontent.com/5016028/55597357-c8b76200-5712-11e9-8bd9-3866488e08ca.png)

It seems to work fine with `curve.curveLinear`:

![Simulator Screen Shot - iPhone X - 2019-04-04 at 20 04 51](https://user-images.githubusercontent.com/5016028/55597801-fef5e100-5714-11e9-8ddf-d9e78bd4e6ba.png)

**Comment by JesperLekland** [comment]
This has nothing to do with this library unfortunately. The way the curve is calculated is based on a normal interpolation based on [d3](https://github.com/d3/d3-shape#curves). It's just pure math, the chart simply draws what you give it

**Comment by ecssiah** [comment]
Okay, thanks for clarifying that.

It does appear to work fine with the basis interpolation.
