### ISSUE TITLE
formatLabel Does not re-render when supplied with new data

### ISSUE THREAD

**Issue by karanpratapsingh** [JesperLekland/react-native-svg-charts#321]
### What platform?

* [x] iOS 
* [x] Android 

React Native version: 0.59.3
react-native-svg-charts-version: ^5.2.0

### Code to reproduce

```javascript
 <XAxis
style={{ marginHorizontal: -10, height: 30 }}
data={time}
formatLabel={(value, index) => sortBy === 'day' ? this._getWeekDay(time, index) : this._getDayHour(time, index)}
contentInset={{ left: 20, right: 20 }}
svg={{ fontSize: 10, fill: 'grey' }} />
```

I think this is an issue of latest react native because it was working last I remember with 0.59.1

**Comment by siradityaverma** [comment]
Add old data to state and then try using setState to update new data.

**Comment by JesperLekland** [comment]
supplied code is not enough to reproduce anything unfortunately.

**Comment by ntk0104** [comment]
just spend few hours to figured it out. In my case I have the combination of barchart and multi line charts, i set the line chart have position: 'absolute' but sometime the line chart not rendered. My solution is set fully height and width to it and now every work as expected.

**Comment by tony-schumacher** [comment]
FYI this issue is still happening. Setting width and height fixed it for me, too.
