### ISSUE TITLE
Passing text , image to stacked Bar chart 

### ISSUE THREAD

**Issue by GeekRishabh** [JesperLekland/react-native-svg-charts#323]
How to pass label , value based on the data in StackedBarChart . 
I need to achieve somethging like the below image
<img width="44" alt="Screenshot 2019-04-13 at 2 48 56 AM" src="https://user-images.githubusercontent.com/23093075/56066937-ecc01680-5d96-11e9-8bd3-59abfcd5e149.png">

**Comment by andrienpecson** [comment]
+1

**Comment by lucaspiressimao** [comment]
+1

**Comment by JesperLekland** [comment]
See the [examples repo](https://github.com/JesperLekland/react-native-svg-charts-examples)

**Comment by andrienpecson** [comment]
@JesperLekland can you provide us in the repo where can we accomplish the provided example above? I can see no example in the stackbarchart providing the same example.

**Comment by yoavapi** [comment]
did you find any workaround to this?
