### ISSUE TITLE
Define a value from which the yAxis should start.

### ISSUE THREAD

**Issue by themathiou** [JesperLekland/react-native-svg-charts#33]
### What is the problem?
yAxis always starts from 0 and that create a useless area under the chart, if all the values are bigger than 0.

### When does it happen?
I have a chart with values 20.000±200.
The chart is rendered correctly but I would like yAxis to start from 19.000 instead of 0. 

### What platform?
* [x] iOS
* [x] Android

React Native version: 0.49

### Code to reproduce

```javascript
<AreaChart
    style={{ flex: 1 }}
    dataPoints={performance}
    contentInset={{ top: 10, bottom: 10, left: 10, right: 10 }}
    curve={shape.curveNatural}
    svg={{
    fill: 'rgba(134, 65, 244, 0.2)',
    stroke: 'rgb(134, 65, 244)',
    }}
/>
```

![screenshot_1516813945](https://user-images.githubusercontent.com/2776613/35346303-8d169272-013a-11e8-89cb-174e8c0fe042.png)

Thank you in advance :)

**Comment by JesperLekland** [comment]
Hi @themathiou! Good timing I must say. v2.2.0 was released today with fixes for your problem! Enjoy :)

**Comment by themathiou** [comment]
Hehe! Awesome! I'll test it and I'll let you know. Thank you

**Comment by themathiou** [comment]
Works as expected.
Also if a value is smaller than gridMin the grid is automatically adjusted.
Great 👍 

![screenshot_1516815999](https://user-images.githubusercontent.com/2776613/35347975-6011a988-013f-11e8-80ed-56a8a1db073e.png)
