### ISSUE TITLE
Min/Max used before definition?

### ISSUE THREAD

**Issue by tonypee** [JesperLekland/react-native-svg-charts#335]
https://github.com/JesperLekland/react-native-svg-charts/blob/56b781f2e9199dc1fcb5433756f0733c3978d78c/src/y-axis.js#L75

Im trying to extract this compenent to typescript, but this line is very confusing. How are you using the min/max before their destructuring, escpecially since the defaults rely on the extent variable. It seems like a circular defendancy of variables?

**Comment by tonypee** [comment]
seems the min/min must just be undefineds and ignored by the .extent

**Comment by saji-ryu** [comment]
As I say in PR, I got an error when I use it in Storybook with react-native-web and [svgs](https://github.com/godaddy/svgs). ↓like this
```
Cannot access 'min' before initialization
ReferenceError: Cannot access 'min' before initialization
    at YAxis.render (http://localhost:9001/vendors~main.7f9b4aa8c2e8d95c391b.hot-update.js:12885:80)
    ...
```
