### ISSUE TITLE
Any plans to support scaleTime

### ISSUE THREAD

**Issue by ln0v** [JesperLekland/react-native-svg-charts#34]
Do you have plans to support d3.scaleTime for time series data. Would be a useful addition to this very useful module.

**Comment by JesperLekland** [comment]
@ln0v Hi! Tell me more about your use case and I'll see what I can do :)

**Comment by ln0v** [comment]
I want to plot a line graph where the X axis is time series data and Y axis has corresponding values. Would like the points on the X-axis to be proportionally placed based on the start and end date, so scaleTime would be very useful.  Thank you for your consideration.

**Comment by JesperLekland** [comment]
That sounds more as a problem with your datasets. Supply a `LineChart` with your dataPoints sorted by time and then just use `formatLabel` on the `XAxis` to

**Comment by ln0v** [comment]
guess that is a matter of perspective, d3.scaleTime support this.

**Comment by JesperLekland** [comment]
This isn't a data formatting library, it's a charting library. You're more than welcome to use any additional library to format your data. If you can think of a nice way to integrate a `scaleTime` api please submit a PR.

**Comment by anater** [comment]
I'd like to request this be re-opened. Time series data still can't be accommodated by this library due to the single data point. For instance if I have 3 data points, say `[{ value: 1, time: '8:00' }, {value: 2, time: '10:00'}, {value: 3, time: '18:00'}]` across a day, they'll simply be spaced evenly, even though they are not.

**Comment by JesperLekland** [comment]
Fair point and good example @anater. Reopening

**Comment by Achilles718611** [comment]
Can you add example chart which works with time series data?
