### ISSUE TITLE
[progress-circle] Duplicate children

### ISSUE THREAD

**Issue by nartc** [JesperLekland/react-native-svg-charts#348]
### What is the problem?
`children` is duplicated.

### What platform?

* [x] iOS 
* [ ] Android 

React Native version: 0.59
react-native-svg-charts-version: 5.2.0

### Code to reproduce

```javascript
<ProgressCircle progress={ 0.5 }
                            progressColor={ colors.primary }
                            style={ { height: 100, flex: 1 } }
                            strokeWidth={ 2 }>
              <Text>test</Text>
</ProgressCircle>
```

### Screenshot
![image](https://user-images.githubusercontent.com/25516557/59972274-c4e8ee00-9551-11e9-944b-2f9c73fa1336.png)
The second circle is the one with `children`

**Comment by rgoarias** [comment]
Same problem here. Anyone found a solution? It also seems that it's not possible to center the content.

react-native: 0.59.8
react-native-svg: 9.5.3
react-native-svg-charts: 5.3.0

**Comment by nartc** [comment]
@rgoarias I have a solution. https://github.com/nartc/rn-movies/blob/master/src/components/Personal/Personal.tsx#L64 

Check this component out :)

**Comment by rgoarias** [comment]
Thanks for that Chau, it was helpful!
