### ISSUE TITLE
Stacked Bar Chart: Different color for each bar.

### ISSUE THREAD

**Issue by andrienpecson** [JesperLekland/react-native-svg-charts#349]
How can I obtain to make every stacked bar chart different color from each other.

**Comment by Unicity-Pimentel** [comment]
This worked for me :

`<StackedBarChart
	style={style}
	keys={ ['positive','negative']}
	colors={['green','red']}
	data={ data}
	showGrid={ false }
	horizontal={true}/>`

**Comment by andrienpecson** [comment]
@Unicity-Pimentel currently that is what I am doing. But I need something like the image below. 
![NmrFC](https://user-images.githubusercontent.com/13114319/60098928-3363c100-9789-11e9-93cb-f56d8f70406b.png)

**Comment by Unicity-Pimentel** [comment]
yup same application.  try setting the `horizontal={false}`

**Comment by andrienpecson** [comment]
@Unicity-Pimentel how about for example in the image I posted in the bar one the colors will be blue and orange while for the second bar the colors are blue, white and red?

**Comment by Unicity-Pimentel** [comment]
put your data in an array and map it in your stacked chart together with your color scheme.
like this one:

`const data_sample = [{
  color : ['blue','orange'],
  data : [{
    positive: 3840,
    negative: 1920,
  }],
  keys : ['positive','negative'],
  label : 'test'
},
{
  color : ['brown','green','red'],
  data : [{
    positive: 3840,
    negative: 1920,
    neutral : 1000
  }],
  keys : ['positive','negative','neutral'],
  label : 'test2'
}]

<View style={[{flexDirection:'column',alignText : 'left', justifyContent : 'flex-start', borderWidth:0,flex:1}]}>
  <View style={[{flexDirection:'row',alignText : 'left', justifyContent : 'flex-start', borderWidth:0}]}>
  {data_sample.map(value => {
    return(<StackedBarChart
      style={{ height: 100, width:'20%' ,marginLeft: '5%'}}
      keys={ value.keys}
      colors={value.color}
      data={ value.data}
      showGrid={ false }
      horizontal={false}/>
      )
  })
  } 
  </View>
</View>`



this will produce this view : 


![Screen Shot 2019-06-26 at 2 37 23 PM](https://user-images.githubusercontent.com/45195420/60156835-f8f93300-981f-11e9-8aa7-b33d308cae37.png)
