### ISSUE TITLE
Using BarChart with data as array of objects doesn't work

### ISSUE THREAD

**Issue by idanlo** [JesperLekland/react-native-svg-charts#360]
### What is the problem?
when setting the data like so `[100, 200, 300]` everything works fine, when setting is like this: 
`[ { value: 100, svg: { fill: "#58CC72' } }, { value : 200, svg: { fill: "#58CC72" } } ]` it doesn't work and I cannot see the bars, but I can see the x axis color change

### What platform?

* [X] Android

React Native version: 0.60.3
react-native-svg-charts-version: 5.3.0

### Code to reproduce

```javascript
function App() {
  const data = [4200, 6000, 6800, -3000, 4000, 5000, 5500, 6000, 7000, 4000, 2000];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Dec'];

  const axesSvg = { fontSize: 10, fill: 'grey' };
  const verticalContentInset = { top: 10, bottom: 10 };
  const xAxisHeight = 30;

  const chartData = data.map((value, index) => {
    return {
      value,
      svg: {
        fill: value > 0 ? '#58CC72' : '#FC6A6E'
      }
    };
  });

  const CustomXAxis = ({ bandwidth, ...restProps }: any) => (
    <XAxis
      {...restProps}
      style={{ marginHorizontal: -10, height: xAxisHeight }}
      contentInset={{ left: 20 + bandwidth / 2, right: 20 + bandwidth / 2 }}
      svg={axesSvg}
      formatLabel={(_, index) => months[index]}
    />
  );

  return (
    <View
      style={{
        height: 450,
        flexDirection: 'row'
      }}>
      <YAxis data={data} style={{ marginBottom: xAxisHeight }} contentInset={verticalContentInset} svg={axesSvg} />
      <BarChart
        style={{ flex: 1 }}
        data={chartData}
        svg={{ fill: colors.primary }}
        contentInset={{ top: 10, bottom: 10, left: 10, right: 10 }}
        spacingInner={0.65}
        spacingOuter={0}>
        <Grid direction={Grid.Direction.BOTH} />

        <CustomXAxis />
      </BarChart>
    </View>
  );
}
```

when supplying the `data` array to the `BarChart` component it works fine, when supplying the `chartData` array it does not

using `chartData` - 
![image](https://user-images.githubusercontent.com/28350511/61277161-42eb8e00-a7ba-11e9-931b-523be495ff08.png)

using `data` - 
![image](https://user-images.githubusercontent.com/28350511/61277171-4b43c900-a7ba-11e9-92ed-b62271e4eb61.png)

**Comment by kuzzmi** [comment]
@idanlo Have you found a solution for this? Having the same issue.

**Comment by ITArtist** [comment]
I don't know why, but put the below property in your BarChart.

`yAccessor={({ item }) => item.value}`

Then it will be working.

**Comment by usrbowe** [comment]
@idanlo I'm closing this issue, as it seems to be fixed with using `yAccessor`, which specifies how to access data for chart.
