### ISSUE TITLE
I want to how can i used upside down for line chart

### ISSUE THREAD

**Issue by berrybar** [JesperLekland/react-native-svg-charts#364]
### What is the problem?
I want to upside down the line chart, so i find data reverse()!

But it turns on both sides.

How can i used upside down for line chart??

### What platform?

* [ ] iOS 
* [x] Android 

React Native version: 0.54
"react-native-svg-charts": "^5.3.0"

![1](https://user-images.githubusercontent.com/48274978/62506199-a0fc1600-b83a-11e9-8f4b-edbb63c81994.PNG)

**Comment by berrybar** [comment]
import React from 'react'
import { Grid, LineChart, XAxis, YAxis } from 'react-native-svg-charts'
import { View } from 'react-native'

class AxesExample extends React.PureComponent {

    render() {

        const data = [ 50, 10, 40, 95, -4, -24, 85, 91, 35, 53, -53, 24, 50, -20, -80 ]
        const data2 = [ 1, 5, 7]

        const axesSvg = { fontSize: 10, fill: 'grey' };
        const verticalContentInset = { top: 10, bottom: 10 }
        const xAxisHeight = 30

        return (
            <View style={{ height: 200, padding: 20, flexDirection: 'row' }}>
                <YAxis
                    data={data2}
                    style={{ marginBottom: xAxisHeight }}
                    contentInset={verticalContentInset}
                    svg={axesSvg}
                />
                <View style={{ flex: 1, marginLeft: 10 }}>
                    <LineChart
                        style={{ flex: 1 }}
                        data={data2}
                        contentInset={verticalContentInset}
                        svg={{ stroke: 'rgb(134, 65, 244)' }}
                    >
                        <Grid/>
                    </LineChart>
                    <XAxis
                        style={{ marginHorizontal: -10, height: xAxisHeight }}
                        data={data2}
                        formatLabel={(value, index) => index}
                        contentInset={{ left: 10, right: 10 }}
                        svg={axesSvg}
                    />
                </View>
            </View>
        )
    }

}

export default AxesExample

**Comment by jakmak24** [comment]
Hi. The first think that came up to my mind is to map data to opposite values data = data.map(x=>-x) and then add formatLabel = {(value)=>-value} prop to YAxis.

**Comment by jakmak24** [comment]
Hi. The first think that came up to my mind is to map data to opposite values data = data.map(x=>-x) and then add formatLabel = {(value)=>-value} prop to YAxis.

**Comment by berrybar** [comment]
You're a genius!
I ran it with that code and solved the problem.
Thank you for your reply.

**Comment by Ryabchikus** [comment]
...or you can do something like this:             

```
<YAxis
  min={maxValue}
  max={minValue}
  {.........}
/>
{.........}
<LineChart
  yMin={maxValue}
  yMax={minValue}
  {.........}
/>
```
