### ISSUE TITLE
YAxis don't work with scale={scale.scaleBand}

### ISSUE THREAD

**Issue by RafaelA977** [JesperLekland/react-native-svg-charts#390]
### What is the problem?
YAxis don't work with scale={scale.scaleBand}.
Error message: y.ticks is not a function
Problem related with compare scaleBand functions, then always false
<img width="842" alt="Screenshot 2019-10-12 at 21 36 43" src="https://user-images.githubusercontent.com/34536550/67237985-6a0ec700-f45d-11e9-922f-6c8b054f6a18.png">

### When does it happen?
everytime if use scaleBand
### What platform?

* [ ] iOS 
* [ ] Android 

React Native version: 0.60.4
react-native-svg-charts-version: 5.3.0

### Code to reproduce

Your example code https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/horizontal-with-axis.js is don't work. This is failed with error y.ticks is not a function

**Comment by usrbowe** [comment]
@RafaelA977 I believe you hitting into this [issue](https://github.com/JesperLekland/react-native-svg-charts/issues/392#issuecomment-550995454), can confirm if this solve your problem?

**Comment by usrbowe** [comment]
closing this duplicate issue, and keeping this for reference: #392
