### ISSUE TITLE
How to install this lib?

### ISSUE THREAD

**Issue by Abhishek9634** [JesperLekland/react-native-svg-charts#391]
Biggest Foolish thing came to across.
You have everything but you have nothing about installation steps great

**Comment by usrbowe** [comment]
@Abhishek9634 That's a good idea, would be able to help with this?
I can imagine, basic info like this would be enough:

---

### Getting started
> This library depends on `react-native-svg`, so please install this library first [Installation](https://github.com/react-native-community/react-native-svg#installation).

Install the library using either Yarn:

```
yarn add react-native-svg-charts
```

or npm:

```
npm install --save react-native-svg-charts
```

**Comment by vitorverasm** [comment]
I think this should be added to the docs. @usrbowe I can help with that if that's case.

**Comment by vitorverasm** [comment]
PR open.

**Comment by usrbowe** [comment]
closing this, since @vitorverasm PR was merged.
