### ISSUE TITLE
Is it possible to animate ECG animation to the Line chart?

### ISSUE THREAD

**Issue by NaseebullahSafi** [JesperLekland/react-native-svg-charts#40]
Firstly I just want to say you guys are doing a great job and I'm grateful for finding this library.

I had a question regarding the animation. You see my situation is the following:

I have an app that Receives data from an external device. What I'd like to do is visualize the data in line graph.

The main issue, we cant use CSS animation and CSS keyframes, this makes it hard for the animation of the line.

For example, suppose this is the data I receive from an external device:

```js
var _data = [
  0, 0, 0, 0, 0.0000050048828125, 0.0000137939453125, 0.000049560546875,
  0.00008740234375, 0.00015966796875, 0.000262451171875, 0.0003975830078125, 0.0005687255859375,
  0.0007802734375, 0.001037353515625, 0.0013468017578125, 0.00172119140625, 0.0021756591796875,
  0.0027232666015625, 0.0033880615234375, 0.004206787109375, 0.0052380371093750005,
  0.006586181640625, 0.008400146484375001, 0.010904296875, 0.0144892578125, 0.0196798095703125,
  0.049684204101562504, 0.0886883544921875, 0.11185363769531251, 0.134164306640625,
  0.137352294921875, 0.1160369873046875, 0.08516308593750001, 0.0539765625,
  0.014997436523437501, -0.015882568359375, -0.0387554931640625, -0.06125732421875, -0.0745780029296875, -0.07479357910156251, -0.0725338134765625, -0.0418538818359375,
  0.08582861328125001, 0.397717529296875, 0.8136408691406251, 1.2295617980957032,
  0.9944150390625001, 0.2824605712890625, -0.38949267578125, -0.597251220703125, -0.425675537109375, -0.1537947998046875, -0.0500914306640625, -0.0111041259765625,
  0.0027451171875, 0.0071739501953125, 0.008443359375, 0.0094327392578125, 0.012530517578125,
  0.0176046142578125, 0.0300162353515625, 0.0433489990234375, 0.056962646484375004,
  0.0704832763671875, 0.0770511474609375, 0.0898175048828125, 0.10311853027343751,
  0.117046142578125, 0.1312630615234375, 0.1529300537109375, 0.167607177734375,
  0.1899068603515625, 0.2124422607421875, 0.235044677734375, 0.2575535888671875,
  0.2724073486328125, 0.286978271484375, 0.3007579345703125, 0.3067425537109375,
  0.3106370849609375, 0.303756103515625, 0.2897236328125, 0.25916931152343753,
  0.2200599365234375, 0.1728209228515625, 0.133416259765625, 0.086224853515625,
  0.05493408203125, 0.02409423828125, 0.00922607421875, -0.0043409423828125, -0.0097349853515625, -0.013127685546875, -0.01423095703125, -0.013834716796875, -0.012556030273437501, -0.010675048828125, -0.00835888671875, -0.0057305908203125, -0.0000562744140625
];
```
I want to be able to make it readable using line animation: [`ECG Animation`](http://joakimkemeny.github.io/jke.d3.ecg/).

> Note that the example is using d3 library.

Thanks guys!

**Comment by JesperLekland** [comment]
Hi @NaseebullahSafi and thank you for the kind words. 
This is not something that is supported at the moment and probably won't be for a while. CSS animations and keyframes is not supported in React Native at all. Animations with SVG's are tricky and so far I haven't stumbled on any particularly nice frameworks that works well on RN. Let me know if you find any :)

**Comment by JesperLekland** [comment]
PS. One "ugly fix" for now would be to set all unknown values as undefined and then fill them in, that would create an illusion of an animation that grows along the xAxis. i.e
```
data = [ value , undefined, undefined ....etc  ]
// on next render data would have one more value
data = [ value1, value2, undefined, undefined ]

**Comment by NaseebullahSafi** [comment]
@JesperLekland I see, unfortunately, I had a feeling this would be the case. Ok mate I'll let you know if I do find anything.

The issue is I cant predefine the array as undefined as the array might not be fixed size, as we're dealing with real-time data.

Thanks for the help

**Comment by vvazzim** [comment]
Hey guys i have the same issue as @bitabs.
i really look forward to find a framework that solve it.
