### ISSUE TITLE
I have the chart on the left using "LIne". I want the one on the right. Please advise

### ISSUE THREAD

**Issue by toddrimes** [JesperLekland/react-native-svg-charts#401]
Hi:

I have the plot on the left, which plots a maximum data value per minute. I want the plot on the right, which plots minimum -and- maximum values per minute.  How can I do this with this lib?

![Screen Shot 2019-11-13 at 6 58 37 PM](https://user-images.githubusercontent.com/363950/68823614-29affc80-0649-11ea-8a0e-a946b4c0e3c5.png)

Thank you in advance!
~Todd

**Comment by toddrimes** [comment]
I see there is already an issue open for this, so I upvoted it.  Will close this one.  Thank you.

**Comment by usrbowe** [comment]
@toddrimes I guess you talking about this issue right? https://github.com/JesperLekland/react-native-svg-charts/issues/137

> Just want to mention it here, for the reference.

**Comment by toddrimes** [comment]
> @toddrimes I guess you talking about this issue right? #137
> 
> > Just want to mention it here, for the reference.

Yes, that's the one.  Thank you.
