### ISSUE TITLE
Rerender blinking

### ISSUE THREAD

**Issue by gwumkt** [JesperLekland/react-native-svg-charts#409]
Hi there,
I'm using the Line chart as following:

`<LineChart
                style={{ height: 200 }}
                data={feed}
                svg={{ stroke: 'rgb(134, 65, 244)' }}
                contentInset={{ top: 20, bottom: 20 }}
            >
            </LineChart>`

The issue is that when the LineChart reRender, even if the feed param contains the same area, the chart will have a small blink, like the chart will re render but with a small annoying blink..

Thanks!

**Comment by Peeeep** [comment]
@gwumkt Did you find a solution?

**Comment by gwumkt** [comment]
im using diff lib now
import { AreaChart } from 'react-native-svg-charts';
