### ISSUE TITLE
How to 'force' chart scale 

### ISSUE THREAD

**Issue by toddrimes** [JesperLekland/react-native-svg-charts#411]
Hi:
I'm sure this is simple but I haven't figured it out.

I'm charting data collected every minute in 60-minute batches.  WIth full batches, the line chart coincides with my 60-minute X-axis just fine (gaps are collapsed). For example:
![Screen Shot 2019-12-14 at 9 51 35 PM](https://user-images.githubusercontent.com/363950/70858717-139d9200-1ebc-11ea-8ded-1144c5ab8a7b.png)

But when my last interval has fewer than 60 minutes, the line charts stretches to fit the width of the chart and then no longer matches the X-axis.
![Screen Shot 2019-12-14 at 9 45 06 PM](https://user-images.githubusercontent.com/363950/70858722-231cdb00-1ebc-11ea-8fa3-823538c97bc1.png)

How can I force (e.g.) 20 minutes of data to fit over the first 20 minutes of the 60 minute X-axis?

Thank you,
~Todd

**Comment by JesperLekland** [comment]
Have a look at `scaleTime` and [this example](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/x-axis/scale-time.js) 👍

**Comment by toddrimes** [comment]
Cool -  I will.

Thank you!

**Comment by JesperLekland** [comment]
No problem 🌮 
Closing for now, feel free to reopen if you can't figure it out
