### ISSUE TITLE
Android: not working RNSVGLine

### ISSUE THREAD

**Issue by nam89vn** [JesperLekland/react-native-svg-charts#42]
### What is the problem?
Android: Error while updating property 'strokeWidth' in shadow node of type: RNSVGLine #583
TypeError: expected dynamic type double, but had type string

### What platform?

* [ ] iOS 
* [x] Android 
I was working on Expo version 24.0.0 It uses  "react-native-svg-charts": "^2.1.0",
IOS working fine

### Code to reproduce

```javascript
![35194523-fc730914-feda-11e7-8c4b-d356af6ee276](https://user-images.githubusercontent.com/12689764/35909846-5a9926be-0c27-11e8-8f49-865aa29f8982.jpg)
<AreaChart
                        style={{ height: 200 }}
                        dataPoints={this.state.charts}
                        contentInset={ { top: 30, bottom: 30 } }
                        curve={shape.curveNatural}
                        svg={{
                            fill: 'rgba(134, 65, 244, 0.2)',
                            stroke: 'rgb(134, 65, 244)',
                        }}
                    />
```

**Comment by namnn89** [comment]
![35194523-fc730914-feda-11e7-8c4b-d356af6ee276](https://user-images.githubusercontent.com/20234482/35909940-98918420-0c27-11e8-9f16-351aa924dfc2.jpg)

**Comment by nam89vn** [comment]
![35194523-fc730914-feda-11e7-8c4b-d356af6ee276](https://user-images.githubusercontent.com/12689764/35911290-fa7b455a-0c2b-11e8-9a8f-13ccc7c640c6.jpg)

**Comment by JesperLekland** [comment]
I think this might be a compatibility issue with the `react-native-svg` that Expo uses. What version is that?

**Comment by namnn89** [comment]
with expo `react-native-svg` this is pre-installed. Jump ahead to Usage
I dont know version that

**Comment by nam89vn** [comment]
with expo react-native-svg this is pre-installed. Jump ahead to Usage
I dont know version that

**Comment by JesperLekland** [comment]
This [snack](https://snack.expo.io/HyJ7yPPvf) works fine. Closing
