### ISSUE TITLE
How can we give margin between bar chart lines ?

### ISSUE THREAD

**Issue by suresh777** [JesperLekland/react-native-svg-charts#422]
I am using bar chart using this library. How can i give margins between lines.
Can we have spacing prop? 

 <BarChart
              style={{height: 120}}
              data={ data }
              svg={{ fill }}
              contentInset={{ top: 30, bottom: 10, left:5, right:5 }}
          >
          </BarChart>

**Comment by JesperLekland** [comment]
There is exactly that. See the documentation [here](https://github.com/JesperLekland/react-native-svg-charts#props-2)
