### ISSUE TITLE
Is there any way to apply different stroke color values to the stroke based on range data point lies ?

### ISSUE THREAD

**Issue by pranaybinju** [JesperLekland/react-native-svg-charts#423]
Hi, I'm trying to create an Electrocardiogram chart and want to have different values of stroke color based on range the point lies something like this below using Area chart or Line chart

![heart-rate](https://user-images.githubusercontent.com/24493084/72232963-89e00200-35ea-11ea-8efd-9ce11489e2a0.png)

Also, data I'm getting is dynamic, which means there is no fixed number of points. I tried checking whether the upcoming data point lies within a particular range and updated stroke value in svg prop but that changes stroke color of the whole line. Currently, I'm using gradients to show different ranges the heartbeat lies in the background. But it would be better if I could achieve something like this above.

Please, let me know if there is any way I can apply different stroke color based on the range the point lies. Thank you in anticipation.

**Comment by JesperLekland** [comment]
It's absolutely possible, albeit a bit advanced. You have have to create as many lines as you want colors (with the same input data) and then just clip the charts outside of a specific range. See [this example] to learn how to clip charts.

PS. Gotta love "Heart rate while playing Witcher" 🥇

**Comment by pranaybinju** [comment]
> It's absolutely possible, albeit a bit advanced. You have have to create as many lines as you want colors (with the same input data) and then just clip the charts outside of a specific range. See [this example] to learn how to clip charts.
> 
> PS. Gotta love "Heart rate while playing Witcher" 🥇

I can't see the link. Can you provide the link again?

**Comment by JesperLekland** [comment]
Sorry! Updated the original post with the link

> > It's absolutely possible, albeit a bit advanced. You have have to create as many lines as you want colors (with the same input data) and then just clip the charts outside of a specific range. See [this example] to learn how to clip charts.
> > PS. Gotta love "Heart rate while playing Witcher" 🥇
> 
> I can't see the link. Can you provide the link again?

**Comment by beatrizsabbatini** [comment]
@pranaybinju did you do it? I´m trying a similar chart but still coudn´t make it work.

**Comment by pranaybinju** [comment]
> @pranaybinju did you do it? I´m trying a similar chart but still coudn´t make it work.

Hi @beatrizsabbatini , sorry for late response. It was a long time ago that I had worked on.
Here's the code using Clipath to somehow achieve the result, hope this helps you!

```
import React from 'react';
import {View} from 'react-native';
import {ClipPath, Defs, Rect} from 'react-native-svg';
import {LineChart, Path} from 'react-native-svg-charts';

class PartialLineChartExample extends React.PureComponent {
  render() {
    const data = [50, 10, 40, 95];

    const indexToClipFrom = 10;

    const Clips = ({x, width}) => (
      <Defs key={'clips'}>
        <ClipPath id="clip-path-1">
          <Rect x={'0'} y={'0'} width={x(indexToClipFrom)} height={'100%'} />
        </ClipPath>
        <ClipPath id={'clip-path-2'}>
          <Rect
            x={x(indexToClipFrom)}
            y={'0'}
            width={width - x(indexToClipFrom)}
            height={'100%'}
          />
        </ClipPath>
      </Defs>
    );

    // Line extras:
    const DashedLine = ({line}) => (
      <Path
        key={'line-1'}
        d={line}
        stroke={'rgb(134, 65, 244)'}
        strokeWidth={2}
        fill={'none'}
        strokeDasharray={[4, 4]}
        clipPath={'url(#clip-path-2)'}
      />
    );

    return (
      <LineChart
        style={{height: 200}}
        data={data}
        contentInset={{top: 20, bottom: 20}}
        svg={{
          stroke: 'rgb(134, 65, 244)',
          strokeWidth: 2,
          clipPath: 'url(#clip-path-1)',
        }}>
        <Clips />

        <DashedLine line={10} />
      </LineChart>
    );
  }
}

export default PartialLineChartExample;
```

**Comment by lurdharry** [comment]
this suggestion does not work for me.
@pranaybinju  were you able to solve this issue

**Comment by pranaybinju** [comment]
> this suggestion does not work for me. @pranaybinju were you able to solve this issue

Hi @lurdharry , I did it a long time ago. Code in above comment might help you.
