### ISSUE TITLE
How to place tooltips at the top of the each bar on bar chart?

### ISSUE THREAD

**Issue by luk3skyw4lker** [JesperLekland/react-native-svg-charts#435]
Hi! Sorry for bothering, but I want to make tooltips for a bar chart and I'm not being able to do it.

I'm using a decorator to make the Tooltip as a SVG Text, the y axis is definitely right but when I try to make it stay at the top of each bar (using the x axis), is doesn't works.

My component code:

`import React, { PureComponent } from 'react';
import { LineChart, BarChart } from 'react-native-svg-charts';
import { Circle, Text } from 'react-native-svg';
import * as shape from 'd3-shape';
import { fromUnixTime, format } from 'date-fns';
import { View } from 'react-native';

export default class RainChart extends PureComponent {
  render() {
    const { data } = this.props;

    const Markers = ({ x, y, data }) => {
      return data.map((item, index) => (
        <Circle
          key={index}
          cx={x(item.time)}
          cy={y(item.milimeters)}
          r={5}
          stroke="#fff"
          fill="#fff"
        />
      ));
    };

    const Tooltips = ({ x, y, data }) => {
      // console.log(data);
      return data.map((item, index) => (
        <Text
          key={index}
          x={x(fromUnixTime(item.time).getDate())}
          y={y(item.milimeters) - 15}
          fontSize={15}
          fontWeight="lighter"
          stroke="#fff"
          fill="#fff"
          textAnchor="middle"
          alignmentBaseline="middle"
        >
          {`${item.milimeters}mm`}
        </Text>
      ));
    };

    const Labels = ({ x, data }) => {
      return data.map((item, index) => {
        const date = fromUnixTime(item.time);
        const label = format(date, 'dd/MM');

        return (
          <Text
            key={index}
            x={x(item.time)}
            y={280}
            fontSize={15}
            stroke="#fff"
            fontWeight="lighter"
            fontStyle="normal"
            fill="#fff"
            textAnchor="middle"
          >
            {label}
          </Text>
        );
      });
    };

    return (
      <View style={{ height: '40%' }}>
        <BarChart
          style={{ height: '100%', width: data.length * 130 }}
          data={data}
          xAccessor={({ item }) => {
            const date = fromUnixTime(item.time).getDate();

            return date;
          }}
          yAccessor={({ item }) => {
            return item.milimeters;
          }}
          contentInset={{ top: 60, bottom: 30, left: 10, right: 10 }}
          svg={{
            fill: '#fff'
          }}
          curve={shape.curveNatural}
        >
          <Tooltips />
        </BarChart>
        {/* <LineChart
          style={{ height: '100%', width: data.length * 120 }}
          data={data}
          svg={{
            stroke: 'rgb(255, 255, 255)',
            strokeWidth: 1.8
          }}
          contentInset={{ top: 150, bottom: 100, left: 30, right: 30 }}
          showGrid={false}
          yAccessor={({ item }) => {
            return item.milimeters;
          }}
          xAccessor={({ item }) => {
            return item.time;
          }}
          curve={shape.curveNatural}
        >
          <Labels />
          <Tooltips />
          <Markers />
        </LineChart> */}
      </View>
    );
  }
}
`

**Comment by JesperLekland** [comment]
Check [this example](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/vertical-with-labels.js), you can easily switch out the Texts for whatever you want

**Comment by luk3skyw4lker** [comment]
Nice, thanks for helping.

Sorry for bothering.

**Comment by rikinshah23** [comment]
@JesperLekland Could you guide me to an example on how to show data labels for LineChart ? Thanks
