### ISSUE TITLE
Instructions for sample app are not working

### ISSUE THREAD

**Issue by otusweb** [JesperLekland/react-native-svg-charts#44]
### What is the problem?
I followed the instruction to get the sample app running and it did not work. I'm getting a "No bundleURL present" error in the simulator.

Googling the error seem to point toward the need to upgrade react native. The package still includes 0.46 when the current version is 0.53.

### When does it happen?
Follow instruction in readme
the only difference is I'm using the version of reacting native installed in the node_mobulde directory:
./node_modules/.bin/react-native run-ios

### What platform?

* [ ] iOS iphone 8 ios 11.2 simulator
* [ ] Android 

React Native version: 0.46.0 (installed via the command yarn on the project)

**Comment by JesperLekland** [comment]
I can't recreate this. I do however recognise the error message from other projects. I'ts normally when you haven't had the packager running on the correct port or not running at all ( sometimes it needs to be running while compiling the native code ). 

I'll close this as I can't recreate it. Try with the latest release v3.0.0 and request a re-open if you still can't get it to work
