### ISSUE TITLE
[Feature] bar chart grouped do not showing right data if your data only have positive numbers

### ISSUE THREAD

**Issue by ntk0104** [JesperLekland/react-native-svg-charts#444]
If any body is stucking in bar-chart-grouped because of it do not showing right proportion please read my case. I have spent couple of hours to figure out what problem with this lib and I firgure out that in the example for bar-chart-grouped in includes both negative and positive numbers so everything working fine. But when you data only have positive number, your chart seem to be cut of the bottom side and the visualization absolutely wrong. My workaround is add 1 object { value: 0} to my array data to tell the chart know let start draw from the root with value = 0. And know everything work fine. Would be nice if s.o have this additional check in the lib to make this chart showing right in more general cases.

**Comment by JesperLekland** [comment]
Have you tried the `yMin` prop, setting it to zero? 
The chart will of course only display the range you provide unless you tell it otherwise

**Comment by gitVera** [comment]
yMin={0} helps my BarChart!) thanks!
