### ISSUE TITLE
License missing from react-native-svg-charts-examples

### ISSUE THREAD

**Issue by AGIsmail** [JesperLekland/react-native-svg-charts#445]
### What is the problem?

MIT license is referenced in the README.md for `react-native-svg-charts-examples`, but it is missing from the package.
[The link in question.](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/LICENSE)

**Comment by JesperLekland** [comment]
You are more than welcome to supply a PR 👍 As the examples repo is not meant to serve as anything else than examples I'll just close this issue as it doesn't affect anyone
