### ISSUE TITLE
LineChart doesn't render properly with only one datapoint

### ISSUE THREAD

**Issue by lkoehl** [JesperLekland/react-native-svg-charts#463]
### What is the problem?
LineChart doesn't get rendered properly when there is only one datapoint. See attach image. The LineChart uses the space provided (yellow) but doesn't stretch.

### When does it happen?
On rendering with only one datapoint.

### What platform?

-   [x] iOS 
-   [ ] Android 

react-native version: `0.61.5`
react-native-svg-charts version: `5.4.0`
react-native-svg version: `12.1.0`

#### Styles
```
const styles = StyleSheet.create({
  layout: {
    flex: 1,
    paddingVertical: 20,
    justifyContent: 'center',
  },
  lineChart: {flexGrow: 1, marginLeft: 10},
});
```

#### Component
```
<View style={[styles.layout, {flexDirection: 'row'}]}>
  <YAxis
    data={[40]}
    contentInset={{top: 20, bottom: 20}}
    numberOfTicks={5}
    svg={{fontSize: 10, fill: 'grey'}}
  />
  <LineChart
    style={styles.lineChart}
    data={[40]}
    svg={{
      stroke: 'rgb(134, 65, 244)',
      strokeWidth: 4,
    }}
    numberOfTicks={5}
    contentInset={{top: 20, bottom: 20, left: 10, right: 10}}
    showGrid={true}
    curve={shape.curveCatmullRom.alpha(0.8)}>
    <Grid />
  </LineChart>
</View>
```

![Simulator Screen Shot - iPhone 11 Pro - 2020-04-18 at 10 20 47](https://user-images.githubusercontent.com/48966896/79689318-471a6f80-8254-11ea-9209-b1e0596cdc84.png)

**Comment by lkoehl** [comment]
Same problem occurs when all the data points have the same y value

**Comment by lkoehl** [comment]
Fixed by using `yMin` and `yMax`

**Comment by lkoehl** [comment]
Adding `yMin` and `yMax`brings a lot of different problems with it. The Labels doesn't scale with the graph and the labels are way off from the values

**Comment by ajacquierbret** [comment]
Hi @lkoehl ! Try to use the 'scale' prop with d-3 scale values to ensure correct label positions.
