### ISSUE TITLE
Unable to resolve module `react-native-svg` from `node_modules/react-native-svg-charts/src/stacked-area-chart.js`: react-native-svg could not be found within the project.

### ISSUE THREAD

**Issue by zerocsss** [JesperLekland/react-native-svg-charts#466]
### What is the problem?
Unable to resolve module `react-native-svg` from `node_modules/react-native-svg-charts/src/stacked-area-chart.js`: react-native-svg could not be found within the project.

### What platform?

-   [x] iOS 
-   [ ] Android 

react-native version: `0.62.2`
react-native-svg-charts version: `5.4.0`
react-native-svg version: `6.2.1||^7.0.3`

### Code to reproduce

```javascript
Error: Unable to resolve module `react-native-svg` from `node_modules/react-native-svg-charts/src/stacked-area-chart.js`: react-native-svg could not be found within the project.
```

**Comment by imurielr** [comment]
I solved this problem by installing and linking react-native-svg
