### ISSUE TITLE
XAxis rotate labels

### ISSUE THREAD

**Issue by namxam** [JesperLekland/react-native-svg-charts#47]
Due to the ordering of styles on labels, it is not possible to set transformations. They are overriden by the internals.

In our case we would like to rotate the text labels to have more space for its contents.

Have a look here:
https://github.com/JesperLekland/react-native-svg-charts/blob/7a9292431932dd01c66e09369cd2b745a9db536c/src/x-axis.js#L110

What do you think, would it make sense to reorder the attributes? Or at least to not return an empty array, but null / undefined. I think this would be than ignored and would only break transforms on PIE charts.

**Comment by JesperLekland** [comment]
I see your problem. Version 3.0 actually replaces the XAxis for an `react-native-svg` based one. Meaning that regular transforms won't work, but svg ones should. Keep an eye out for 3.0!

**Comment by namxam** [comment]
Nice. For now we reduced the resolution of our data, so we have more space for labels 😄
