### ISSUE TITLE
PieChart taking up more area than it should

### ISSUE THREAD

**Issue by philipeneves** [JesperLekland/react-native-svg-charts#470]
Hello, I have a problem using the PieChart, it's ocupating a big rectangular area, I was able to visualize this using the backgroundColor property. What can I do to make the chart use only the area where it is shown? I'll let the code I am using bellow:

**index.js**
````
import React from 'react';
import { PieChart } from 'react-native-svg-charts'


import styles from './styles'

class DonutChart extends React.PureComponent {

    constructor(props) {
        super(props);
        this.state = {
        selectedSlice: {
            label: '',
            value: ''
        },
        labelWidth: 0
        }
    }
    render() {
        const { labelWidth, selectedSlice } = this.state;
        const { label, value } = selectedSlice;
        const keys = [
            'Compras', 
            'Educação', 
            'Transporte', 
            'Saúde', 
            'Lazer'
        ];
        const values = [
            10, 
            50, 
            30, 
            10, 
            50
        ];
        const colors=[
            '#9372EF', 
            '#C7463A', 
            '#EFCF00', 
            '#16A085', 
            '#5DADE2'
        ];
        const data = keys.map((key, index) => {
            return {
                key,
                value: values[index],
                svg: { fill: colors[index] },
                arc: { outerRadius: (40) + '%', padAngle: label === key ? 0.1 : 0 },
                onPress: () => this.setState({ selectedSlice: { label: key, value: values[index] } })
            }
        })

        return (
                <PieChart
                    style={styles.chart}
                    outerRadius={'95%'}
                    data={data}></PieChart>
        )
    }
}

export default DonutChart
````

**styles.js**
````
import { StyleSheet } from 'react-native'

export default StyleSheet.create({
    chart: {
        height: 300,
        margin: 0,
        padding: 0,
        backgroundColor: 'red'
    },
    legend: {
        position: 'absolute',
        left: 150
    }
})
````

**Comment by JesperLekland** [comment]
Can you supply screenshots showing the issue?

**Comment by philipeneves** [comment]
> Can you supply screenshots showing the issue?

![Screenshot_20200430-154327_otto_assistente](https://user-images.githubusercontent.com/49224281/81066107-fd1bc580-8eb2-11ea-9048-b0306f2f628b.jpg)

I don't want this whole area in red off the chart. I've even tried to reduce the size of the component, but when doing this the chart decreases along with the area, it is as if they were one thing, as if the component had a standard padding / margin.

**Comment by JesperLekland** [comment]
Have you experimented with this line? It obviously shrinks the arc but not the container.
```js
arc: { outerRadius: (40) + '%', padAngle: label === key ? 0.1 : 0 }
```

 To  shrink the container just use the `style` prop

---
> it is as if they were one thing, as if the component had a standard padding / margin.

Well, they are one thing, but there is no standard padding or margin

**Comment by philipeneves** [comment]
> Have you experimented with this line? It obviously shrinks the arc but not the container.
> 
> ```js
> arc: { outerRadius: (40) + '%', padAngle: label === key ? 0.1 : 0 }
> ```
> 
> To shrink the container just use the `style` prop
> 
> > it is as if they were one thing, as if the component had a standard padding / margin.
> 
> Well, they are one thing, but there is no standard padding or margin

Thank you, I just removed the outerRadius part and it worked!
