### ISSUE TITLE
How to set a fixed bar width on grouped bar chart, with fixed spacing in between groups?

### ISSUE THREAD

**Issue by caseydaly** [JesperLekland/react-native-svg-charts#473]
How can I change the spacing between groups of bars **without changing the widths of the bars**? I am trying to decrease the "spacingInner" prop...

```
                <BarChart
                    style={{ height: 300, width: "100%", paddingRight: 10, alignSelf: 'stretch' }}
                    data={barData}
                    yAccessor={({ item }) => item.value}
                    contentInset={contentInset}
                    {...this.props}
                    spacingInner={0.45}
                    grid
                    yMax={10}
                >
                    <CustomGrid belowChart={true}/>
                    <Gradient/>
                </BarChart>
```

However, whenever I decrease it, it not only decreases the spacing in between groups of bars, but it **makes the bar widths bigger**. How can I set a static bar width so that I can change the spacing between groups without having the bar width affected?

**Comment by JesperLekland** [comment]
It's unfortunately not possible. Allowing it would open up a ton possibilities to error by the user. The bars will always scale to fill the view while taking the spacing into consideration. Either change the size (width) of the chart, experiment with number of datapoints or the spacing.

**Comment by caseydaly** [comment]
Understandable. I think messing around with both inner and outer spacing as well as separation between the bars using the 'x' prop passed to each bar should do. Thanks for the response and making this great library!
