### ISSUE TITLE
question: Barchart rounded corner

### ISSUE THREAD

**Issue by otusweb** [JesperLekland/react-native-svg-charts#48]
### What is the problem?
I'm trying to round the corner of the bars in a barchart.
I found a solution online for D3, i'm wondering how i can use that within this library.

https://stackoverflow.com/questions/39842964/how-to-make-vertical-corners-on-a-bar-chart

I can't find where to start in the docs

**Comment by JesperLekland** [comment]
As of now the bars are rendered using a `path`, meaning there's no option for rounded corners. One possible solution for the future could be to render the bars with an svg `rect` instead. This is not something I will prioritise because of it's very narrow use case. Feel free to submit a PR :) 
Closing issue as this isn't supported

**Comment by antoinerousseau** [comment]
Hi, still no easy way to have rounded bar corners?

**Comment by lauridskern** [comment]
Hi, is this going to get implemented sometime? Happy holidays

**Comment by aniruddhashevle** [comment]
@JesperLekland : We can use `stroke-linecap="round"` for `path` to make both the sides of the path rounded.

**Comment by DarbyBrown** [comment]
Another solution is to use a transparent fill on the bars themselves, and create a new path with rounded corners. 
This way you don't have to consider this:
>Though keep in mind that you may need to do adjustments to Grid and YAxis if you use those, the rect will increase the height of the bar since half of the Rect need to be above the existing bar.

gist for function creating a path with rounded corners https://gist.github.com/danielpquinn/dd966af424030d47e476

```
import React from 'react';
import { G, Path } from 'react-native-svg';

import { roundedRectData } from '../utils/roundedRectData';

// this is a hack to add rounded top to the chart
const RoundedBars = ({ x, y, bandwidth, data, height, contentInset }) => {
  return data.map((item, index) => (
    <G x={x(index)} y={y(item.value)}>
      <Path
        d={roundedRectData(
          bandwidth,
          height - y(item.value) - (contentInset?.bottom || 0),
          bandwidth / 2,
          bandwidth / 2
        )}
        fill={item.svg.fill}
      />
    </G>
  ));
};

export default RoundedBars;
```
Result
![image](https://user-images.githubusercontent.com/4050771/117137296-658cd380-ada1-11eb-8558-af3a6243d5a0.png)

**Comment by ko-devHong** [comment]
> An easy workaround to get rounded corners in a bar chart is to add a SVG `<Rect>` on top of each bar and apply rounded corners to the `<Rect>`. Though keep in mind that you may need to do adjustments to Grid and YAxis if you use those, the rect will increase the height of the bar since half of the Rect need to be above the existing bar.
> 
> The following function will add rounded corners and a label on top of each bar.
> 
> ```
>  const Labels = ({ x, y, bandwidth, data }) => (
>       data.map((value, index) => (
>         <G
>           key={index}>
>           <Text
>             x={x(index) + (bandwidth / 2)}
>             y={y(value) - 10}
>             fontSize={8}
>             fontWeight={'bold'}
>             fill={'#ff0000'}
>             alignmentBaseline={'middle'}
>             textAnchor={'middle'}
>           >
>             {'$' + value}
>           </Text>
>           <Rect
>             x={x(index)}
>             y={y(value) - 5 } // Subtract Height / 2 to make half of the Rect above the bar
>             rx={5} // Set to Height / 2
>             ry={5} // Set to Height / 2
>             width={bandwidth}
>             height={10} // Height of the Rect
>             fill={'#ff0000'}
> 
>           />
>         </G>
>       ))
>     )
> ```
> 
> <img alt="image-1" width="351" src="https://user-images.githubusercontent.com/3678047/44958722-582e3580-aee4-11e8-9432-88094731ca4f.png">

how to know (x ,y ) function and bandwidth ?

**Comment by RubenHamakers** [comment]
For anyone in the future seeing this, the props you need to access are added by the library with the following code:

```
}, React.Children.map(children, child => {
      if (child && child.props.belowChart) {
        return React.cloneElement(child, extraProps);
      }
```

which, if you're using typescript, is not gonna work lol

What I did was make the props of my decorator of type any and then just 

`const { const { x, y, bandwidth, data, height, contentInset } = props;`

so for the barchart

```
          <BarChart
            yMin={-1}
            yMax={1}
            animate={true}
            animationDuration={300}
            style={{ flex: 1, position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, marginBottom: 10, marginTop: 10, backgroundColor: 'transparent' }}
            data={preparedSellNormalized}
            gridMin={0}
            contentInset={verticalContentInset}
            yAccessor={({ item }) => item.y}
          >
            <RoundedBars belowChart={false} activeIndex={activeIndex}/>
          </BarChart>
```

and for the decorator

```
const RoundedBars = (props: any) => {
  const { x, y, bandwidth, data, height, contentInset } = props;
  etc etc
```

**Comment by Major-Usama** [comment]
Bar Chart Rounded Corners working code (I have custom-made a bar chart with rounded corners and different colors for each bar line using React-Native-SVG-Charts and react-native-svg )

here is the code 

import React from "react";
import { View, Text, StyleSheet } from "react-native";
import { BarChart, Grid } from "react-native-svg-charts";
import { RFValue } from "react-native-responsive-fontsize";
import { G, Rect, Text as SVGText } from "react-native-svg";

const RoundedBars = ({
  x,
  y,
  bandwidth,
  data,
  height,
  barColors,
  barLabels,
}) => {
  return data.map((value, index) => {
    const barHeight = height - y(value);
    const barX = x(index);
    const barY = y(value);
    const barWidth = 38; // Fixed width of each bar
    const barSpacing = -RFValue(20); // Space between bars
    const borderRadius = 10;
    const barColor = barColors[index % barColors.length];
    const barLabel = barLabels[index];

    return (
      <G key={index}>
        <Rect
          x={barX + barSpacing - 0 / 1}
          y={barY}
          width={barWidth}
          height={barHeight}
          rx={borderRadius}
          ry={borderRadius}
          fill={barColor}
        />
        <SVGText
          x={barX + barWidth / 2 + barSpacing / 2}
          y={height + 14} // Adjusted y position for label
          fontSize={8}
          fontWeight={"bold"}
          fill={"#ffffff"}
          alignmentBaseline={"middle"}
          textAnchor={"middle"}
        >
          {barLabel}
        </SVGText>
      </G>
    );
  });
};

export default function BarGraph() {
  const data = [10, 35, 20, 50, 20, 30];
  const barColors = [
    "rgba(0, 168, 243, 0.2)",
    "rgba(0, 168, 243, 0.8)",
    "rgba(0, 168, 243, 0.5)",
    "rgba(0, 168, 243, 0.8)",
    "rgba(0, 168, 243, 0.2)",
    "rgba(0, 168, 243, 0.5)",
  ];
  const barLabels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"];

  return (
    <View style={styles.barChartContainer}>
      <View style={styles.yAxisLabels}>
        <Text style={styles.yAxisLabel}>100$</Text>
        <Text style={styles.yAxisLabel}>50$</Text>
        <Text style={styles.yAxisLabel}>0$</Text>
      </View>
      <View>
        <View style={styles.chartContainer}>
          <BarChart
            style={{ height: RFValue(150), width: RFValue(270) }}
            data={data}
            yAccessor={({ item }) => item}
            contentInset={{ top: 0, bottom: 50, left: 20, right: -20 }}
          >
            <RoundedBars barColors={barColors} barLabels={barLabels} />
          </BarChart>
        </View>
        <View style={styles.xAxisLabels}>
          {barLabels.map((label, index) => (
            <Text key={index} style={styles.xAxisLabel}>
              {label}
            </Text>
          ))}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  barChartContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 7,
  },
  yAxisLabels: {
    top: RFValue(10),
  },
  yAxisLabel: {
    fontSize: RFValue(11),
    color: "#DCDCDC",
    fontFamily: "Medium",
    marginBottom: RFValue(52),
    marginLeft: 12,
  },
  chartContainer: {},
  xAxisLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: RFValue(5),
    marginTop: 7,
    marginRight: RFValue(12),
    // backgroundColor:"red",
  },
  xAxisLabel: {
    fontSize: RFValue(11),
    color: "#DCDCDC",
    fontFamily: "Bold",
  },
});

**Comment by Major-Usama** [comment]
`import React from "react";
import { View, Text, StyleSheet } from "react-native";
import { BarChart, Grid } from "react-native-svg-charts";
import { RFValue } from "react-native-responsive-fontsize";
import { G, Rect, Text as SVGText } from "react-native-svg";

const RoundedBars = ({
  x,
  y,
  bandwidth,
  data,
  height,
  barColors,
  barLabels,
}) => {
  return data.map((value, index) => {
    const barHeight = height - y(value);
    const barX = x(index);
    const barY = y(value);
    const barWidth = 38; // Fixed width of each bar
    const barSpacing = -RFValue(20); // Space between bars
    const borderRadius = 10;
    const barColor = barColors[index % barColors.length];
    const barLabel = barLabels[index];

    return (
      <G key={index}>
        <Rect
          x={barX + barSpacing - 0 / 1}
          y={barY}
          width={barWidth}
          height={barHeight}
          rx={borderRadius}
          ry={borderRadius}
          fill={barColor}
        />
        <SVGText
          x={barX + barWidth / 2 + barSpacing / 2}
          y={height + 14} // Adjusted y position for label
          fontSize={8}
          fontWeight={"bold"}
          fill={"#ffffff"}
          alignmentBaseline={"middle"}
          textAnchor={"middle"}
        >
          {barLabel}
        </SVGText>
      </G>
    );
  });
};

export default function BarGraph() {
  const data = [10, 35, 20, 50, 20, 30];
  const barColors = [
    "rgba(0, 168, 243, 0.2)",
    "rgba(0, 168, 243, 0.8)",
    "rgba(0, 168, 243, 0.5)",
    "rgba(0, 168, 243, 0.8)",
    "rgba(0, 168, 243, 0.2)",
    "rgba(0, 168, 243, 0.5)",
  ];
  const barLabels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"];

  return (
    <View style={styles.barChartContainer}>
      <View style={styles.yAxisLabels}>
        <Text style={styles.yAxisLabel}>100$</Text>
        <Text style={styles.yAxisLabel}>50$</Text>
        <Text style={styles.yAxisLabel}>0$</Text>
      </View>
      <View>
        <View style={styles.chartContainer}>
          <BarChart
            style={{ height: RFValue(150), width: RFValue(270) }}
            data={data}
            yAccessor={({ item }) => item}
            contentInset={{ top: 0, bottom: 50, left: 20, right: -20 }}
          >
            <RoundedBars barColors={barColors} barLabels={barLabels} />
          </BarChart>
        </View>
        <View style={styles.xAxisLabels}>
          {barLabels.map((label, index) => (
            <Text key={index} style={styles.xAxisLabel}>
              {label}
            </Text>
          ))}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  barChartContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 7,
  },
  yAxisLabels: {
    top: RFValue(10),
  },
  yAxisLabel: {
    fontSize: RFValue(11),
    color: "#DCDCDC",
    fontFamily: "Medium",
    marginBottom: RFValue(52),
    marginLeft: 12,
  },
  chartContainer: {},
  xAxisLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: RFValue(5),
    marginTop: 7,
    marginRight: RFValue(12),
    // backgroundColor:"red",
  },
  xAxisLabel: {
    fontSize: RFValue(11),
    color: "#DCDCDC",
    fontFamily: "Bold",
  },
});
`

**Comment by ishaanbuildsthings** [comment]
> 

Hi Darby,

Thanks for your help. I would appreciate any clarification, I am trying to get this setup to work, though I'm not too proficient in these things.

Currently I have:

1) Rounded Bars Component
```
const RoundedBars = ({x, y, bandwidth, data, height, contentInset}) => {
  return data.map((item, index) => (
    <G x={x(index)} y={y(item.value)}>
      <Path
        d={roundedRectData(
          bandwidth,
          height - y(item.value) - (contentInset?.bottom || 0),
          bandwidth / 2,
          bandwidth / 2,
        )}
        fill={'green'}
      />
    </G>
  ));
};
```

2) My chart component

```
<BarChart
        data={data}
        style={styles.chart}
        gridMin={0}
        svg={{
          fill: 'transparent',
        }}>
        <RoundedBars data={data} />
</BarChart>
```

I set the bar chart color to be transparent and the rounded bars to be green, thinking that is how I could display the rounded data. I also modified my data to be like this:

```
const data = [{value: 10}, {value: 15}, {value: 9}, {value: 22}];
```

As you can see I made `data` (which is what I pass to my `RoundedBars` component) an array of objects. I'm not sure if this is correct but it looks like the `.map` on `data` required a `.value` property.

When I try to run my code, I get an error, giving invalid numbers. It kind of looks like this:

![Screenshot 2023-07-25 at 12 36 53 AM](https://github.com/JesperLekland/react-native-svg-charts/assets/113543798/64e183bb-357e-4980-8b01-b1d722857745)

I can't tell if it's because the transform function, `roundedRectData` is wrong? It seems to expect 6 arguments but we only pass 6. I just copy pasted the one from the gist: https://gist.github.com/danielpquinn/dd966af424030d47e476
Do you have any idea?

I also tried passing `data.map(item => item.value)` to my `BarChart` thinking that still needs the actual data as opposed to the array of objects, but it didn't fix anything.
