### ISSUE TITLE
XAxis - No display

### ISSUE THREAD

**Issue by krrevilla** [JesperLekland/react-native-svg-charts#5]
I've followed your example in XAxis, but it doesn't display anything. All I get was a padding in bottom.

**Comment by JesperLekland** [comment]
Hi @krrevilla, sorry to hear. How did you test it? In your own project? Could you provide me with your code?

**Comment by JesperLekland** [comment]
I took a quick look an suspect that you have ignored the `formatLabel` prop. If you use this to format the value into something useful it should work. I will tweak the default `formatLabel` to always return at least the index. Please confirm if this worked for you

**Comment by krrevilla** [comment]
Hi @JesperLekland yep, with my own project.

`<XAxis
            style={{ paddingVertical: 16 }}
            values={value}
            formatLabel={(value, index) => index}
            chartType={ XAxis.Type.BAR }
            labelStyle={{ color: '#fff' }}
          />`

I've tried it again this morning, still not working.

**Comment by JesperLekland** [comment]
@krrevilla could you show me the entire file? I'm interested in the the `values` look and how you've aligned the axis with the rest of the views

**Comment by rafaelviny** [comment]
>             const data    = [ 14, 80, 100,55]
            const barData = [
                {
                    values: data,
                    fillColor: 'rgb(134, 65, 244)',
                    fillColorNegative: 'rgba(134, 65, 244, 0.2)',
                },
            ]
    
            return (
                <View style={ { height: 200, padding: 20 } }>
                    <BarChart
                        style={ { flex: 1 } }
                        data={ barData }
                    />
                    <XAxis
                        style={ { paddingVertical: 16 } }
                        values={ data }
                        formatLabel={ (value, index) => index }
                        chartType={ XAxis.Type.BAR }
                        labelStyle={ { color: 'grey' } }
                    />
                </View>
            )
        }

**Comment by rafaelviny** [comment]
XAxis no display.


beautiful work in this lib

**Comment by OZhang** [comment]
After I added flex: 1 to the XAxis style, the XAxis displayed.

**Comment by JesperLekland** [comment]
@rafaelviny Very strange, I get an XAxis when using your code. I'll have to dig deeper into this.

**Comment by JesperLekland** [comment]
@OZhang `flex:1` should only be needed if parent view has `flexDirection: 'row'`

**Comment by guilherme-dias** [comment]
Hey guys, my XAxis is "eating" a piece of the first and the last label on Android, any style that I can apply to fix this?

**Comment by JesperLekland** [comment]
@guilherme-dias use the `contentInset` prop with `left`and `right`

**Comment by JesperLekland** [comment]
fixed it! Released in v1.6.1. Please re-open if problem persists

**Comment by sammysium** [comment]
@JesperLekland sorry to bug you but can you believe i still face the same issue? From the lastest product and just copied pasted the example code. Playing with the style as follows shows me an empty box that spans horizontally below the chart. So I am guessing there is space but no labels?

![image](https://user-images.githubusercontent.com/46919720/86073835-752ce480-ba39-11ea-93a1-76c01eeb7349.png)

this is the code. Removing <Labels/> makes no difference.

```
 <View style={{marginTop: 7, height: 250, paddingVertical: 16}}>
          <BarChart
            style={{flex: 1}}
            data={values}
            gridMin={0}
            svg={{fill: 'rgb(134, 65, 244)'}}>
            <Labels />
          </BarChart>
          <XAxis
            style={{marginTop: 10, borderWidth: 1, height:50}}
            data={values}
            scale={scale.ScaleBand}
            formatLabel={(value, index) => index}
            labelStyle={{color: 'black'}}
          />
        </View>
```

**Comment by yerycs** [comment]
XAxis still does not render at all, as well as YAxis label.
