### ISSUE TITLE
[Question] How to group Bar Chart data?

### ISSUE THREAD

**Issue by geovrisco** [JesperLekland/react-native-svg-charts#505]
Hi I want to achive [this](https://i.stack.imgur.com/YW2gL.png
) kind of chart with 2 datasets

my data look like this
```
const data1 = [
  {label: 'bad', svg: {fill: '#E55300'}, value: 5},
  {label: 'marginal', svg: {fill: '#EB742F'}, value: 10},
  {label: 'fair', svg: {fill: '#F5A77A'}, value: 20},
  {label: 'good', svg: {fill: '#9BD4DE'}, value: 30},
  {label: 'satisfactory', svg: {fill: '#1D8091'}, value: 10},
];
const data2 = [
  {label: 'bad', svg: {fill: '#E55300'}, value: 10},
  {label: 'marginal', svg: {fill: '#EB742F'}, value: 21},
  {label: 'fair', svg: {fill: '#F5A77A'}, value: 32},
  {label: 'good', svg: {fill: '#9BD4DE'}, value: 44},
  {label: 'satisfactory', svg: {fill: '#1D8091'}, value: 75},
];
const data3 = [
  {label: 'bad', svg: {fill: '#E55300'}, value: 50},
  {label: 'marginal', svg: {fill: '#EB742F'}, value: 81},
  {label: 'fair', svg: {fill: '#F5A77A'}, value: 77},
  {label: 'good', svg: {fill: '#9BD4DE'}, value: 33},
  {label: 'satisfactory', svg: {fill: '#1D8091'}, value: 21},
];
```

andd i group them like this
```
const barDataY = [
    {
      data: data1,
      svg: {
        stroke: 'red',
        strokeWidth: 2,
      },
    },
    {
      data: data2,
      svg: {
        stroke: 'dodgerblue',
        strokeWidth: 2,
      },
    },
    {
      data: data3,
      svg: {
        stroke: 'grey',
        strokeWidth: 2,
      },
    },
  ];
```

instead getting the chart that i wanted, i got barchart like [this]( https://i.stack.imgur.com/HlFUQ.png)
i wonder how do i group them by its data set, not by its value?

**Comment by geovrisco** [comment]
so i transform my data into 5 different array that contain each label, i dont know if this the proper way to group data though

**Comment by ashokkumar88** [comment]
@geovrisco How did you create group bar chart?

**Comment by geovrisco** [comment]
so instead of this data

`
const data1 = [
  {label: 'bad', svg: {fill: '#E55300'}, value: 5},
  {label: 'marginal', svg: {fill: '#EB742F'}, value: 10},
  {label: 'fair', svg: {fill: '#F5A77A'}, value: 20},
  {label: 'good', svg: {fill: '#9BD4DE'}, value: 30},
  {label: 'satisfactory', svg: {fill: '#1D8091'}, value: 10},
];
const data2 = [
  {label: 'bad', svg: {fill: '#E55300'}, value: 10},
  {label: 'marginal', svg: {fill: '#EB742F'}, value: 21},
  {label: 'fair', svg: {fill: '#F5A77A'}, value: 32},
  {label: 'good', svg: {fill: '#9BD4DE'}, value: 44},
  {label: 'satisfactory', svg: {fill: '#1D8091'}, value: 75},
];
const data3 = [
  {label: 'bad', svg: {fill: '#E55300'}, value: 50},
  {label: 'marginal', svg: {fill: '#EB742F'}, value: 81},
  {label: 'fair', svg: {fill: '#F5A77A'}, value: 77},
  {label: 'good', svg: {fill: '#9BD4DE'}, value: 33},
  {label: 'satisfactory', svg: {fill: '#1D8091'}, value: 21},
];`

i transform it into 5 categories

`
bad=[
  {
    svg:{},
    value:xxx,
 },
{
    svg:{},
    value:xxx,
 },
{
    svg:{},
    value:xxx,
 },

]

marginal =[{margina1,marginal2,marginal3...}]
and so on
`

**Comment by geovrisco** [comment]
@ashokkumar88 
you group them by the label => so 
good =[{good1},{good2},{good3}]
bad=[{bad1},{bad2},{bad3}]

**Comment by ashokkumar88** [comment]
@geovrisco Thanks.

**Comment by geovrisco** [comment]
@ashokkumar88  no problem dude, glad that i could help
