### ISSUE TITLE
[Feature] Pie Chart border spacing

### ISSUE THREAD

**Issue by brain00021** [JesperLekland/react-native-svg-charts#506]
### Description of feature
Thank you for pie chart plugin. Is it good for me to reduce time to figure out react native.
but i wonder it possible have option can change pie chart border spacing.

many thanks.
![image](https://user-images.githubusercontent.com/5819532/98794717-53f6ee80-2444-11eb-9676-722ec4c50eeb.png)

**Comment by raazatul7** [comment]
@brain00021 Have you tried `padAngle` ?

**Comment by brain00021** [comment]
it's work 
`    return {
      key,
      value: values[index],
      svg: {
        fill: colors[index],
      },
      arc: {padAngle: 0},
      onPress: () => {
        setSelectedSlice({...selectedSlice, selectTitle: key, selectData: values[index]});
      },
    };`

thank you your help
