### ISSUE TITLE
Line Chart not rendering

### ISSUE THREAD

**Issue by olympiawoj** [JesperLekland/react-native-svg-charts#515]
### What is the problem?
This is a bug with my code and not react-native-svg-charts, but I'm struggling to get a line chart plotting. The Grid lines plot successfully, but the the line chart does not show. I've looked at all of the line chart examples and tried a variety of solutions using `xAccessor` and `yAccessor`, but have not been able to get the line chart to render. 

### When does it happen?
When I render this StockChart:

`stockData` is an array of objects with `price` and `date` properties: 
`Array [
  Object {
    "date": "2020-12-23",
    "price": "131.97",
  },
  Object {
    "date": "2020-12-22",
    "price": "130.96",
  },
  Object {
    "date": "2020-12-21",
    "price": "131.88",
  },
  Object {
    "date": "2020-12-20",
    "price": "128.23",
  }`

```
import React, { useEffect, useState } from 'react'
import {Text, View} from 'react-native'
import { LineChart, Grid, XAxis } from 'react-native-svg-charts'
import * as scale from 'd3-scale'
import * as shape from 'd3-shape'
import * as dateFns from 'date-fns'

export const StockChart = ({data}) =>{

    const [stockData, setStockData] = useState<any[]>([])

    interface valInteface {
        close?: string;
    }

    useEffect(()=>{
        const stockDataArr:any[] = []
        for (let [key, value] of Object.entries(data)) {

            const newObj  = {
                date: dateFns.format(new Date(key), 'yyyy-MM-dd'),
                price: value["close"]
            }
            // console.log(newObj)
            stockDataArr.push(newObj)
          }
         setStockData(stockDataArr)
    }, [data])

    return (
        <View>
        <LineChart
            style={{ height: 200, width: 300}}
            data={stockData}
            svg={{ stroke: 'rgb(134, 65, 244)' }}
            contentInset={{ top: 20, bottom: 20 }}
            xScale={ scale.scaleTime }
            xAccessor={({item}) => item.date}
            yAccessor={({item}) => item.price}
        >
            <Grid />
        </LineChart>
        </View>
    )
}`
```

### What platform?

-   [X] iOS 
-   [ ] Android 

react-native version: `0.xx`     "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz" (Installed with expo)
react-native-svg-charts version: `12.1.0`
react-native-svg version: `5.4.0`

### Code to reproduce

```javascript
Code above
```

**Comment by minseokk** [comment]
@olympiawoj  How did you solve the issue?
