### ISSUE TITLE
AreaChart renders an area when a value is 0

### ISSUE THREAD

**Issue by sckellig** [JesperLekland/react-native-svg-charts#528]
### What is the problem?
AreaChart renders an area when values = 0, and I can't replace 0 with null because in this case if I have e.g. [null, 80, null] it won't render anything because the chart needs at least two consecutive points to draw an area.

### When does it happen?
Randomly, some 0 values aren't visible, some are.
In this example, I only have values for the first 2 points and the rest are 0 (please see the code example below), but it still draws an area (albeit small) in the middle.
<img width="377" alt="Screenshot 2021-02-24 at 13 29 06" src="https://user-images.githubusercontent.com/11229226/108994871-ff027f80-76a4-11eb-8e5a-9e084201187c.png">

### What platform?

-   [x] iOS 
-   [x] Android 

react-native version: `0.63.3`
react-native-svg-charts version: `^5.2.0`
react-native-svg version: `^12.0.3`

### Code to reproduce

```javascript
<AreaChart
          style={{ flex: 1, height: 200 }}
          data={[400, 100, 0, 0, 0, 0, 0]}
          svg={{ fill: 'rgba(190,50,141, 0.5)' }}
          contentInset={{ top: 8, right: 8, bottom: 0, left: 8 }}
          curve={shape.curveNatural}
          yMax={400}
          yMin={0}
          numberOfTicks={5}
        />
        <XAxis
          style={{ width: '100%', marginTop: 12 }}
          data={['2021-02-20', '2021-02-21', '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25', '2021-02-26']}
          scale={scale.scaleBand}
          xAccessor={xAccessorExtractor}
          formatLabel={(value) => moment(value).format('D.MM')}
          svg={axesSvg}
        />
```

**Comment by ricardonazario** [comment]
This might be a just an artifact of the curve type. `.curveNatural` will overshoot the value for effect as you can see here -> [https://raw.githubusercontent.com/d3/d3-shape/master/img/natural.png](url)

Try `curveMonotoneX`

**Comment by sckellig** [comment]
@ricardonazario thanks a lot! `curveMonotoneX` is exactly what I need 👍
