### ISSUE TITLE
Not compatible with reac-native-svg 12?

### ISSUE THREAD

**Issue by zabojad** [JesperLekland/react-native-svg-charts#548]
### What is the problem?

I cannot make this lib displaying a simple BarChart. Nothing is displayed at all, even when copy pasting simple samples from this repo.

### When does it happen?

It seems it  is not compatible with  react-native-svg 12, which my project is already using... Is  that possible ?

### What platform?

-   [x] iOS <!-- specific os version ?
-   [ ] Android <!-- specific os version ? not tested

react-native version: `0.63.3`
react-native-svg-charts version: `5.4.0`
react-native-svg version: `12.1.0`

### Code to reproduce

Code from any samples from this repo...

**Comment by zabojad** [comment]
Sorry, issue came from my code actually...

**Comment by vickypathak123** [comment]
Great Thanks

**Comment by vidyaap** [comment]
I'm actually having the same issue. `react-native-svg-charts` claims to require `react-native-svg` version ^6.2.1 or ^7.0.3 but if I install version 7.0.3 and try to run my React application, I get an error that the module `imageSourceProp` cannot be found. I understand that `imageSourceProp` is a deprecated feature, but upgrading my `react-native-svg` breaks `react-native-svg-charts`. Any suggestions on what to do here? Thanks!
