### ISSUE TITLE
LineChart is not drawn when used with BarChart in react-native-web

### ISSUE THREAD

**Issue by watanabeyu** [JesperLekland/react-native-svg-charts#557]
### What is the problem?
LineChart is not drawn when used with BarChart.
https://snack.expo.dev/@watanabe_yu/grumpy-waffle

Works fine in iOS, but not fine in Web.

### What platform?

-   [ ] iOS 
-   [ ] Android 
-   [x] Web

```
"d3-scale": "*",
"d3-shape": "1.2.0",
"react-native-svg": "12.1.1",
"react-native-svg-charts": "*"
```

### Code to reproduce
https://snack.expo.dev/@watanabe_yu/grumpy-waffle

```javascript
<BarChart
        style={{ height: 300 }}
        data={data_}
        yAccessor={({ item }) => item.bar}
        svg={{ fill: 'rgb(134, 65, 244)' }}
        yMin={0}
        yMax={3}>
        <LineChart
          yAccessor={({ item }) => item.line}
          style={{ height: 300 }}
          yMin={0}
          yMax={3}
          svg={{ stroke: '#444', strokeWidth: 3 }}
        />
        <Grid />
      </BarChart>
```

**Comment by dimpalshetty** [comment]
Hey @JesperLekland, I figured out how to fix the issue, it was using Zindex specific to the web. Could you assign this issue to me? I could fix and send a PR.

**Comment by JesperLekland** [comment]
Don't render the LineChart as a child to the BarChart, they need to be rendered at the same level, absolutely positioned if you want them to be on top of each other. Check the examples for inspiration
