### ISSUE TITLE
Axis labels are rendered overlapping

### ISSUE THREAD

**Issue by jayesbe** [JesperLekland/react-native-svg-charts#58]
### What is the problem?
XAxis and YAxis labels are not rendering or are being rendered overlapping

### When does it happen?
On Render

### What platform?
* [ x] iOS 
* [ ] Android (untested)

React Native version: 0.52

### Code to reproduce

```javascript
<YAxis
  data={[50,10,40,95]}
  svg={{ fontSize: 8, fill: 'grey' }}
  style={[{ flex: 1, width: 50 }]}
```

**Comment by JesperLekland** [comment]
Hi @jayesbe. Could you provide a screenshot? And when you say "are not rendering" what exactly do you mean? Regarding the overlapping part, the labels are spaced based on the scale and on the available space, they do not take each other into consideration, this is up to the user to handle, i.e create a wider/taller axis, smaller labels (fontSize) or rotate the labels

**Comment by jayesbe** [comment]
@JesperLekland  will get an iOS screenshot. I just checked on Android and it worked :+1: 

Was working on it all afternoon yesterday on iOS and it wasn't. Will try again today.

**Comment by jayesbe** [comment]
@JesperLekland  please take a look at https://imgur.com/a/A18VE

this is an iOS screenshot. You can see how the labels are being displayed. On Android, the labels are showing as expected.

**Comment by JesperLekland** [comment]
Hmm weird. The YAxis in the project example (storybook) works as expected. Could you provide me with a [expo snack](https://snack.expo.io/) that showcases the problem so that I can troubleshoot?

**Comment by jayesbe** [comment]
hmm.. before I work on the expo snack..

perhaps its related to the way I am setting the height?  It is being set based on layout.

Here is the basics

```
    return (
      <View 
        ref="graph" 
        style={[Theme.Styles.column, Theme.Styles.f1]}
        onLayout={e => {
          if (e.nativeEvent.layout.height === 0 && e.nativeEvent.layout.width === 0) {
            return;
          }
          const newHeight = e.nativeEvent.layout.height - 40;
          const newWidth = e.nativeEvent.layout.width;
          if (newHeight <= 0 || newWidth <= 0) return;
          this.setState({
            height: newHeight,
            width: newWidth
          });
        }}
      >
        <View style={[Theme.Styles.row]}>
          <YAxis
            data={dataPoints}
            numberOfTicks={4}
            style={[{ height: this.state.height, width: 40 }]}
            svg={{ fontSize: 10, fill: 'grey', height: 10 }}
          />
          <View style={[Theme.Styles.column, { overflow: 'scroll', flexWrap: 'nowrap' }]}>
            {this.renderChart()}
            <XAxis
              style={[{height: 15, width: this.state.width, backgroundColor: 'red' }]}
              contentInset={{ top: 0, bottom: 0, left: 25, right: (this.state.width / 7) + 35 }}
              data={ this.state.days }
              formatLabel={ (value, index) => value }
              // labelStyle={{ color: 'grey' }}
              svg={{ fontSize: 6, fill: 'grey' }}
            />
          </View>
        </View>
      </View>
    );
```

**Comment by jayesbe** [comment]
The height and width start at 1 and grow to a size based on the content

**Comment by JesperLekland** [comment]
Why are you setting the height that way?

**Comment by jayesbe** [comment]
the height may change because the height of the xaxis area may change.  If this is related to the height.. I will try changing the way this is handled.

**Comment by JesperLekland** [comment]
I've noticed myself that `react-native-svg` have difficulties re-rendering when its container changes. It probably is related to the height handling as it works in the static examples.

**Comment by jayesbe** [comment]
Thanks @JesperLekland  I will try rewriting the ui around this.

**Comment by JesperLekland** [comment]
I also think there is a flexbox conformant way of handling your use case. The only time you should have to do what you're doing is when you want to animate the height changes.

Hope you fix it 👍

**Comment by jayesbe** [comment]
@JesperLekland  all the examples have a static height of 200.. is it possible to create a chart without a height?  so that the chart takes up the height of its container ?

**Comment by JesperLekland** [comment]
Charts support flex :)

**Comment by jayesbe** [comment]
Do you have a flex example?

**Comment by JesperLekland** [comment]
I don't unfortunately. Just think of a Chart or Axis as a regular View and you'll be fine, they should behave exactly the same way.

**Comment by jayesbe** [comment]
I have removed all style from the example above.. including all width and height and onLayout.  The chart doesn't render at all.  I believe this is what I originally tried and then ended up with the onLayout solution.

**Comment by JesperLekland** [comment]
Neither would a View without content. Just handle it exactly like you would with a View. i.e if you want a box that has a height of 200 pixels `<View style={{height: 200}}>` or one that takes up it's entire parent `<View style={{flex: 1}}`. An empty View, `<View/>` wouldn't render, neither do the Charts

**Comment by JesperLekland** [comment]
If you want to be sure that your layout is correct. Just do it with `View` to begin with ( without children ) and then switch them out for the `react-native-svg-charts` component of your choosing with the same styling

**Comment by jayesbe** [comment]
ok.. thanks will continue at it.

**Comment by jayesbe** [comment]
@JesperLekland  thanks the flex worked just fine for the charts I was using BarChart, LineChart, and StackedBarChart. 

However the example AreaChart is throwing an error

```
            <AreaChart
                style={{ flex: 1 }}
                data={ [ 50, 10, 40, 95, -4, -24, 85, 91, 35, 53, -53, 24, 50, -20, -80 ] }
                svg={ { fill: 'rgba(134, 65, 244, 0.2)' } }
                contentInset={ { top: 20, bottom: 30 } }
                renderDecorator={ ({ x, y, index, value }) => (
                    <Circle
                        key={ index }
                        cx={ x(index) }
                        cy={ y(value) }
                        r={ 4 }
                        stroke={ 'rgb(134, 65, 244)' }
                        fill={ 'white' }
                    />
                ) }
            />
```

the above chart throws an error with flex:1 but works with a set height. 

The error thrown is "width and height must be > 0"

If I remove the style prop, it gives another error

SurfaceView should have explicit width and height set

**Comment by jayesbe** [comment]
@JesperLekland nevermind.. it must be the same issue in some way. Thanks again.

**Comment by burhanahmed92** [comment]
any solution?

**Comment by burhanahmed92** [comment]
I did like this, same result with lables:

```
const data = [ 10, 15, 40, 50 ]
        const CUT_OFF = 50
        const Label = ({ item: value, x, y, index, bandwidth }) => (
            <Text
                key={index}
                y={value < CUT_OFF ? y(value) - 10 : y(value) + 15}
                x={x(index) + (bandwidth / 2)}
                fontSize={14}
                fill={value > CUT_OFF ? 'red' : 'yellow'}
                alignmentBaseline={'middle'}
                textAnchor={'middle'}
            >
                {value}
            </Text>
        )

<View style={{ flexDirection: 'row', height: 200, paddingVertical: 16 }}>
                            <BarChart
                                style={{ flex: 1 }}
                                data={data}
                                svg={{ fill: 'rgba(134, 65, 244, 0.8)' }}
                                contentInset={{ top: 10, bottom: 10 }}
                                spacing={10}
                                gridMin={0}
                                renderDecorator={Label}
                                renderGrid={Grid.Horizontal}
                            />
                        </View>

```
``

**Comment by PetroPavlenko** [comment]
Probably I had the same problem, but I looks like fixed it 

It's because `react-native-svg-charts` uses other version(v 6) of `react-native-svg` then expo

and expo linked with `react-native-svg`(v 8)

so we can force npm to use v 8 by
```
  "resolutions": {
    "react-native-svg": "8.0.8"
  },
```
And that fixed all wrong Axis alignment
