### ISSUE TITLE
render 2 line charts into 1 chart?

### ISSUE THREAD

**Issue by sj602** [JesperLekland/react-native-svg-charts#61]
is there a way to render 2 line charts in 1 chart?
I want to merge these 2 line charts to 1 chart
and also render another Yaxis to the right of the merged chart.
|  ------------------  |
|  ------------------  |
|  ------------------  |
|  ------------------  |
Yaxis1               Yaxis2

<img width="276" alt="charts" src="https://user-images.githubusercontent.com/18183483/36600767-82c8ac6e-18f6-11e8-96e4-976fa8c0018e.PNG">

**Comment by JesperLekland** [comment]
absolute position the second chart on top of the first chart. See [layered charts](https://github.com/JesperLekland/react-native-svg-charts#layered-charts)

**Comment by sj602** [comment]
Thanks! and sorry It was just a stupid question :)
