### ISSUE TITLE
Different inner/outer radius for piechart?

### ISSUE THREAD

**Issue by hansen94** [JesperLekland/react-native-svg-charts#62]
First of all, thank you for the library. It's awesome. I've been using it for making charts on my react-native applications. 
I was just wondering if there is any way to have different inner/outer radius in piechart for different data point?

**Comment by JesperLekland** [comment]
Thank you for the kind words 🙂
Not implememted yet but a great feature request! 
A PR would be highly appreciated but I will definitely look into it eventually.
