### ISSUE TITLE
Horizontal BarChart

### ISSUE THREAD

**Issue by chauhanshubham** [JesperLekland/react-native-svg-charts#63]
Any easy way out to create horizontal bar charts with x-axis (which would eventually look like the y)?

**Comment by JesperLekland** [comment]
Nothing I've implemented yet. What about just rotating a regular BarChart 90 degrees?

**Comment by chauhanshubham** [comment]
I tried that, works with the bar chart, but seems to be a lot of changes for the x-axis (which i rotated by 270 for the alignment). 
I'm stuck at changing the width of the Text in XAxis (Type.BAR), to make it render the full text, in order to rotate it and make it work. For now it just matches the width of the bar (which it should in the vertical bar graph scenario)

The ability to do something [like](https://conceptdraw.com/a205c3/p1/preview/640/pict--vertical-bar-graph-global-competitiveness-index-infrastructure-score) this with the x-axis would make it easier to implement a horizontal bar graph.

**Comment by JesperLekland** [comment]
What version of the library are you using? 
In 3.0.0 you can rotate each label individually. Check [`react-native-svg-charts-examples`](https://github.com/JesperLekland/react-native-svg-charts-examples).

I'm not sure you'll be able to exactly what you want though. I'll take a look at it in the near future. If you figure out a solution I would really appreciate a PR :)
