### ISSUE TITLE
XAxis formatLabel not showing value

### ISSUE THREAD

**Issue by stefblokdijk** [JesperLekland/react-native-svg-charts#66]
Hey.

I'm stuck with the formatLabel prop. I want to show the date under my chart. Now it just shows the array key.

This is the array that gets returned by the `this._chartXAxis()` function:

`["2018-02-20", "2018-02-21", "2018-02-22", "2018-02-23", "2018-02-24", "2018-02-25", "2018-02-26", "2018-02-27"]`

![image](https://user-images.githubusercontent.com/15145744/36739941-ed70c508-1bbf-11e8-8a71-1706847101a4.png)

Here's my code:

```jsx
<View style={styles.chartContainer}>
    <Card>
        <View style={styles.chart}>
            <LineChart
                style={{ flex: 1 }}
                data={this._chartStats('impressions')}
                gridMin={0}
                svg={{ stroke: '#969FAD' }}
                contentInset={{ top: 10, bottom: 10 }}
            />
            <LineChart
                style={ StyleSheet.absoluteFill }
                data={this._chartStats('clicks')}
                gridMin={0}
                svg={{ stroke: '#1E92FF' }}
                contentInset={{ top: 10, bottom: 10 }}
            />
            <LineChart
                style={ StyleSheet.absoluteFill }
                data={this._chartStats('payout')}
                gridMin={0}
                svg={{ stroke: '#FE2851' }}
                contentInset={{ top: 10, bottom: 10 }}
            />
            <LineChart
                style={ StyleSheet.absoluteFill }
                data={this._chartStats('conversions')}
                gridMin={0}
                svg={{ stroke: '#FE2851' }}
                contentInset={{ top: 10, bottom: 10 }}
            />
            <LineChart
                style={ StyleSheet.absoluteFill }
                data={this._chartStats('payout')}
                gridMin={0}
                svg={{ stroke: '#44DB5E' }}
                contentInset={{ top: 10, bottom: 10 }}
            />
            <XAxis
                style={{ marginHorizontal: -10 }}
                data={ this._chartXAxis() }
                formatLabel={(value, index) => value}
                contentInset={{ left: 10, right: 10 }}
                svg={{ fontSize: 10 }}
            />
        </View>
    </Card>
</View>
```

**Comment by jmolinao** [comment]
i have the same issue. =S

**Comment by JesperLekland** [comment]
Hey guys! You need to add the `xAccessor` prop. If it's omitted the XAxis will assume you're only interested in the index. i.e `xAcessor={ ({ value }) => value }`

**Comment by stefblokdijk** [comment]
Thanks for the quick reply! That worked for me. Btw in your example you use `xAcessor` instead of `xAccessor` took a few mins to realize why it wasn't doing anything.

Also, I noticed if you pass a string with a date, it won't show the XAxis. I found a way around with [Moment.js](https://momentjs.com/) like this:

1.) Change each date to Unix timestamp when passing it to the data prop:
`moment(date).format('X') // date = "2018-02-20"`

This is what the array looks like that I passed to the data prop:
`["1519095600", "1519182000", "1519268400", "1519354800", "1519441200", "1519527600", "1519614000", "1519700400"]`

2.) Change data to preferred format in the `formatLabel` prop like this:

```jsx
<XAxis
    style={{ marginHorizontal: -15, height: 20 }}
    data={ this._chartXAxis() }
    xAccessor={({ value }) => value}
    formatLabel={(value) => moment.unix(value).format('DD MMM')}
    contentInset={{ left: 10, right: 25 }}
    svg={{
         fill: '#A4AAB3',
         fontSize: 8,
         fontWeight: '500',
         rotation: 20,
         originY: 30,
         y: 5,
    }}
/>
```

Hopefully this could be easier in the future by being able to pass strings on the XAxis.

**Comment by JesperLekland** [comment]
Yeah that was a simple typo, my bad. 

If you pass a date string you must also make sure that the correct `scale` is used (how else would it know to layout the labels?). Again, check out the examples repo 🙂

**Comment by JesperLekland** [comment]
Closing this issue now, feel free to reopen if you still think this is a problem

**Comment by holtc** [comment]
Should now be `xAccessor={({ item, index }) => item}`
