### ISSUE TITLE
Support for raster <Image /> in "PieChart with label"?

### ISSUE THREAD

**Issue by mocon** [JesperLekland/react-native-svg-charts#67]
Hi there. Thanks for this awesome library!

I'm trying to place .png images into the circular labels, is this supported?

Here's my code so far:

```jsx
<PieChart
  style={{ height: 240 }}
  data={pieData}
  spacing={0}
  innerRadius={16 * 2.75}
  outerRadius={16 * 3}
  labelRadius={16 * 6}
  renderDecorator={({ item, pieCentroid, labelCentroid, index }) => (
    <G key={index}>
      <Line
        x1={labelCentroid[0]}
        y1={labelCentroid[1]}
        x2={pieCentroid[0]}
        y2={pieCentroid[1]}
        stroke={item.color}
        strokeWidth={2}
      />
      <Circle
        cx={labelCentroid[0]}
        cy={labelCentroid[1]}
        r={18}
        fill={item.color}
      />
      <Image
        x={0}
        y={0}
        width={15}
        height={15}
        preserveAspectRatio="xMidYMid slice"
        opacity="1"
        href={require('../assets/images/logo.png')}
        strokeWidth={2}
      />
    </G>
  )}
/>
```

**Comment by JesperLekland** [comment]
Hi @mocon! 

It should indeed be supported. Does it not work as expected? The rendering of the <Image> is done 100% by [`react-native-svg`](https://github.com/react-native-community/react-native-svg) so you might want to check there for more help

**Comment by mocon** [comment]
Thanks @JesperLekland,

Yeah it's very strange, the code above throws no errors, but the image doesn't appear to be rendering. I tried looking through all the `react-native-svg` issues as well, but I didn't see anything similar. I believe my syntax is correct.

<img width="762" alt="example" src="https://user-images.githubusercontent.com/4172870/36881064-133845d2-1d81-11e8-84ed-94212b87ed18.png">

**Comment by JesperLekland** [comment]
Hmm... haven't tried it myself. My best suggestion is to try to render a standalone image using just `react-native-svg` and see if you can make it work.

**Comment by JesperLekland** [comment]
I've confirmed it works. I think your issue is your `x` and `y` coordinates of the image, they're no where near close to the circle. There's an example over at the [examples repo](https://github.com/JesperLekland/react-native-svg-charts-examples), check it out.

Feel free to reopen if you think this is an issue with this library.
