### ISSUE TITLE
Different color for each bar in a bar chart;

### ISSUE THREAD

**Issue by dineshmm23** [JesperLekland/react-native-svg-charts#68]
### What is the problem?
**Warning: Failed prop type: Invalid prop ‘fill‘ of type ‘array‘ supplied to ‘AnimatedPath‘, expected ‘string‘.**
### When does it happen?

> const barData = [
      {
        values: [10,20,40],
        positive: {
          fill: ["#a7d4fb", "#a7d4fc", "#a7d4fd"]
          // warning Happens at this points...i was trying fill different color for each bar
        }
      }
    ];

### What platform?

* [ ] Android -->26.0.2

"dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.1",
    "react-native-svg": "^6.2.1"
  }

### Stacktrace (if crash) 
Warning: Failed prop type: Invalid prop ‘fill‘ of type ‘array‘ supplied to ‘AnimatedPath‘, expected ‘string‘.

in AnimatedPath (at bar-chart.js:157) 

in BarChart (at App .:1s 96) 

in RCTView (at View. 13: 1 12) 

in View (at App .:1s 94) 

in RCTView (at View .:1s 112) 

in View (at App' .:1s 68) 

in RCTView (at View. 13: 112) 

in View (at ScrollView.js:748) 

in RCTScrollView (at ScrollView.jsz857) 

in ScrollView (at App' .:1s 67) 

in RCTView (at View. 13: 112) 

in View (at App .15: 66) 

in App (at renderApplication.js:35) in RCTView (at View.js:1 12) 

in View (at AppContainer.js:102) in RCTView (at View.js:1 12) in View (at AppContainer.js:122) 

in AppContainer (at renderApplication.js: 34)

**Comment by JesperLekland** [comment]
as you've noticed yourself it's not supported to pass an array colors. The only way to do what you want right now is to create a dataset for each datapoint and set a color for that. Have a look at the multiple data set example for barcharts. I will consider this a feature request

**Comment by sunilzalavadiya** [comment]
any update on this? is this feature available yet?

**Comment by JesperLekland** [comment]
See [this example](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/with-different-bars.js)

**Comment by keerthi-m-hng** [comment]
Is that examples are working properly?

**Comment by keerthi-m-hng** [comment]
Please help me out.  I am unable to render different color for each bar

**Comment by Sandeepbadri** [comment]
> 
> 
> See [this example](https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/bar-chart/with-different-bars.js)
We can't use this when vertical labels are used.
