### ISSUE TITLE
ProgressCircle takes empty space when using startAngle and endAngle

### ISSUE THREAD

**Issue by seriiix** [JesperLekland/react-native-svg-charts#71]
I want a half circle chart but when i set startAngle and endAngle the invisible bottom part takes space and because of that, the `dasdsa` text is positioned far away.

<img width="980" alt="screen shot 2018-03-01 at 11 18 24 pm" src="https://user-images.githubusercontent.com/16124619/36866193-e0acbda2-1da6-11e8-8e3a-cadff9d979ff.png">

**Comment by JesperLekland** [comment]
Hi @seriiix 🙂 I'll look into a fix. It's not a trivial fix as d3 uses a full circle to calculate the svg path. I'll get back to you

**Comment by JesperLekland** [comment]
I've looked into it and while it's not the most elegant solution I would advise you to simply do `marginBottom: -100` on the ProgressCircle. I've tested it on both Android and iOS and it works as expected. I tried to implement an automatic solution but it became way to complex to support all different combinations of `startAngle` and `endAngle`. I hope this solves your problem, if it doesn't feel free to reopen
