### ISSUE TITLE
No component found for view with name "RNSVGGroup"

### ISSUE THREAD

**Issue by caihc001** [JesperLekland/react-native-svg-charts#72]
![screen shot 2018-03-01 at 9 47 56 pm](https://user-images.githubusercontent.com/22379323/36881107-67077b6a-1d9a-11e8-8f00-5efe3d92c603.png)
I install the react-native-svg and do react-native-link. Get these error when I am trying the line-chart example. I try to reboot but still got these. Any idea how to fix this?
Thank you.

**Comment by JesperLekland** [comment]
It looks like your link has failed. Try to get `react-native-svg` working first (with a minimal example). This most likely has nothing to do with this library

**Comment by caihc001** [comment]
Sorry about that. This is the bug from react-native-svg.
