### ISSUE TITLE
Setting innerSpacing and outerSpacing separatedly on charts and axises

### ISSUE THREAD

**Issue by fqueiruga** [JesperLekland/react-native-svg-charts#73]
I would like to propose adding a way to just set the inner spacing on bar charts and axis, without setting the outer one. Currently both spacings are set at the same time (https://github.com/JesperLekland/react-native-svg-charts/blob/master/src/bar-chart.js#L99).

I would be open to provide a MR. with the solution

**Comment by fqueiruga** [comment]
I've got an API proposal. 2 new props would be added to all components with a _spacing_ prop, _spacingInner_ and _spacingOuter_. These props would default to _undefined_ and, if present, would override the value of _spacing_. Some examples

**Example 1**
Current behavior of _spacing_:  `<StackedBarChartExample showGrid spacing={0.5} />`
![image](https://user-images.githubusercontent.com/5738588/36908681-3f2112f8-1e3c-11e8-9549-2f4f5c1c6b81.png)

**Example 2**
`<StackedBarChartExample showGrid spacing={0.2} spacingOuter={0.7} />`
![spacing2_outer7](https://user-images.githubusercontent.com/5738588/36908745-71e0867e-1e3c-11e8-917b-02c5d8dc7e7f.png)
 
**Example 3**
`<StackedBarChartExample showGrid spacingInner={0.5} spacingOuter={0} />`
![outer0_inner5](https://user-images.githubusercontent.com/5738588/36908771-864d2572-1e3c-11e8-91c5-be3d2c5f5146.png)

**Comment by JesperLekland** [comment]
Hi @fqueiruga and thank you for the great issue. It sounds perfectly reasonable. I'll go ahead and implement it this weekend :)

**Comment by fqueiruga** [comment]
Hi @JesperLekland don't worry, I have a PR halfway implemented, I'll finish it on Monday!

**Comment by fqueiruga** [comment]
Thank you for implementing this. Great library!
