### ISSUE TITLE
Render values at the center of the pie.

### ISSUE THREAD

**Issue by sarykemmoun** [JesperLekland/react-native-svg-charts#79]
Hello.
First, thanks for your awesome library.
I like to render the title and value of the chosen slice at the center, something like this:
![screenshot from 2018-03-07 12-26-04](https://user-images.githubusercontent.com/28590349/37087409-dad4ee1c-2202-11e8-823c-41720f8ac9ae.png)

I've looked for a prop or something else to do it, but I didn't succeed.
Do you have any idea for me? Tnx.

**Comment by JesperLekland** [comment]
Simply render whatever you want absolutely position on top of the chart. No need to have the chart handle this

**Comment by JesperLekland** [comment]
I've done it several times on different devices with the proposed solution 🙂

**Comment by JesperLekland** [comment]
I'll go ahead and close this as it's not really an issue with this library. I'll consider making an example for [`react-native-svg-charts-examples`](https://github.com/JesperLekland/react-native-svg-charts-examples). If you do get it to work I would appreciate a PR to the examples repo, your graph looks really nice :)
