### ISSUE TITLE
Animate progress - ProgressCircle

### ISSUE THREAD

**Issue by johanolandero** [JesperLekland/react-native-svg-charts#8]
Hello!

I'm using the animate and the animateDuration prop with a ProgressCircle.
Right now the result of this is that the ProgressCircle scales up from small to large during the duration.

Is there a way to animate the progress instead so the progress 'fills' up to the desired progress over the duration?

Cool library by the way!

**Comment by JesperLekland** [comment]
@johanolandero Hi! Right now it's a very basic animation implementation. Basically I diff the tween of the svg path between "before" and "after". In this case "before" is a zero path meaning that it scales up. It gets really weird when you animate from say 10% -> 90% progress (try it out and have a laugh). Small progress increments animate fine though. As of right now I'm not not putting any effort into improving the animations. You're free to open a PR if you have the time
