### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by Amnesthesia** [JesperLekland/react-native-svg-charts#83]
Hi,

Is touch support, e.g clicking datapoints and/or zooming in graphs, something that's planned for a future? Would be fantastic!

**Comment by JesperLekland** [comment]
Hi again, touch support is there by default through react-native-svg-charts. Using decorators/extras with onPress solves that problem (i.e nothing built in but easy to implement yourself). 

Zooming should be doable by just animating the scale, handling touches is the hard part, but again this is not something that is built into the library, and probably never will be. I'm trying to keep this as low level and extensible as possible instead.

**Comment by Amnesthesia** [comment]
Awesome, thank you :-)
