### ISSUE TITLE
Stacked bar chart - horizontal support?

### ISSUE THREAD

**Issue by colin-young** [JesperLekland/react-native-svg-charts#84]
Is there support for rendering the stacked bar charts horizontally? Not sure if this is a user problem (i.e. me) or it's just not supported. I suspect the latter because I don't see anything in the js for that chart type that looks like a horizontal property.

On the other hand, I've been unable to adapt the horizontal line extra (https://github.com/JesperLekland/react-native-svg-charts-examples/blob/master/storybook/stories/extras.js) to this chart and it does appear to be calling `renderExtra` which makes me think I'm doing something wrong.

I was hoping I could just look at the changes made for the bar chart but I found this in the PR: 

> BarChart has been rewritten from the ground up

:) Guess I'm going to have to figure it out the hard way now...

**Comment by JesperLekland** [comment]
Hi @colin-young! You're indeed correct that the stacked bar chart does not yet support the horizontal prop. Your PR seems to remedy this problem though 🎉  

Regarding the `extras` I see now that the Stacked Charts have fallen behind the API and needs to be updated. `renderExtra` is no longer a used property, each `extras` entry is expected to be called directly
