### ISSUE TITLE
extras and renderExtra in StackedAreaChart.

### ISSUE THREAD

**Issue by rostislav-simonik** [JesperLekland/react-native-svg-charts#86]
Hi Jesper, 

what’s the purpose of extras and renderExtra in StackedAreaChart? 

I understand concept in other charts, there are only extras, which can contain render routines, but I don’t understand what intention you have addressed with this map.  
{ extras.map((item, index) => renderExtra({ item, x, y, index, width, height })) }

Could you just point please a case when this can be handy. 

Thanks for answer.

**Comment by rostislav-simonik** [comment]
Maybe intention was to execute extras per each area, wasn't it ?

**Comment by JesperLekland** [comment]
Hi! 

This is actually legacy code (simply forgot to update it), it will be fixed in the upcoming release

**Comment by JesperLekland** [comment]
It's migrated to the latest `extras` api in 4.2.0 👍
