### ISSUE TITLE
Duplicate X-Axis labels.

### ISSUE THREAD

**Issue by msevestre** [JesperLekland/react-native-svg-charts#89]
Hi @JesperLekland ,

First of all, thanks for a great library. It is very powerful and easy to use.

### What is the problem?
I am trying to wrap my head around the way I can format / customize the X-Axis.  The dataset I am displaying is a list of {x:date, y:number}.  For some reason, I keep getting duplicate labels on the X-axis and I'd like to know what I am doing wrong:

For formatting, I am using a custom label function that returns the day of the week as well as the date
```
// Returns a formatted string such as "Mon 14th"
const formatLabel = date => dateFns.format(date, 'ddd Do');
```

Also I have added a function that calculates the number of unique x labels based on the dataset.

// Calculate the number of distinct labels on the X-Axis to set the number of ticks as expected
```
const distinctLabels = _.uniq(data.map(d => formatLabel(d.x)));
```

With my sample dataset `data`, the function `distinctLabels` returns

`Mon 19th, Tue 20th, Wed 21st, Thu 22nd`

Here is what I tried 

* Using `scale = scale.scaleTime`
```
<XAxis
        data={data}
        svg={{
          fill: 'black',
          fontSize: 10,
          fontWeight: 'bold',
          rotation: 15,
          originY: 0,
          y: 3,
        }}
        xAccessor={({ item }) => item.x}
        scale={scale.scaleTime}
        numberOfTicks={distinctLabels.length}
        style={{ marginHorizontal: -15, height: 20 }}
        contentInset={contentInset}
        formatLabel={formatLabel}
      />
```

which results in the following  graph having duplicate entries
![image](https://user-images.githubusercontent.com/1041237/37607472-8485d5d8-2b6e-11e8-96cc-acb35087b5ef.png)

Even though numberOfTicks is 4, 5 entries are generated on the X Axis. Mon 19th is not shown and Tue 20th is shown twice, as well as Wen 21st

* Using `scale = scale.scaleLinear`

![image](https://user-images.githubusercontent.com/1041237/37607599-d1ccedb8-2b6e-11e8-8623-8ff36a755991.png)

I have 4 ticks as expected. However the labels are not what I am expecting. As you can see, Tue 20th is shown twice and Thu 22nd is not visible

I am really not sure how to prevent duplicate entries on the X Axis. Ideally, I would like the values to be the distinct values of my dataset or at least a subset thereof without ANY duplicates.

Any pointers as to what I could try would be greatly appreciated,

Thanks,
Michael

**Comment by msevestre** [comment]
I'd like to add that if I set the numberOfTicks to 3, I only get 2 entries on the X Axis...

![image](https://user-images.githubusercontent.com/1041237/37608676-906e9972-2b71-11e8-9b31-2cb492bb2d73.png)

**Comment by JesperLekland** [comment]
Hi @msevestre! When you use `numberOfTicks` we use the d3 implementation of ticks calculation, i.e it does the closest and most even approximation of datapoints to fit the number of ticks based on the data extent. Please see [this](https://github.com/d3/d3-scale#time_ticks). This is the de facto standard of tick calculation.

**Comment by msevestre** [comment]
@JesperLekland Ok I understand. Is there a way that I can avoid having duplicate entries on the X-label? This just looks very weird.

**Comment by JesperLekland** [comment]
The thing is that `ticks` returns evenly spaced data points, so if you don't truncate them by showing only the date you'll see that they are the best approximation of the data extent. In order to show what you want you'll need to tweak the data from the start, to only include one point from each date. Which is fair enough if you think about it

**Comment by msevestre** [comment]
@JesperLekland Yeah ok. I can appreciate the logic behind that.
Thanks for your quick response. Cheers,

**Comment by henricazottes** [comment]
> you'll need to tweak the data from the start, to only include one point from each date.

I don't see any effect on the problem as the extent is based only on the lower and the greater values. A dataset with only two points will have the same extent as a dataset with one point per day, two points per day, or X points per day as soon as they are in the same range. Maybe I'm missing something but for me data density has no impact on the X axis :/

@msevestre would you mind sharing how you ended up setting your XAxis ?

**Comment by msevestre** [comment]
@henricazottes I have not found a great solution yet. At the moment I am showing the time as well (something like Tue 28th, 6am , Tue 28th 6pm etc... but I am not very happy with the solution.
I am going to try what was suggested in issue #97. I know you said it does not work  (and I was really hoping it would :))) but I am going to give it a try anyways and report back.
