### ISSUE TITLE
XAxis & scaleTime & renderGrid (CustomGrid)

### ISSUE THREAD

**Issue by ChrisBrinton** [JesperLekland/react-native-svg-charts#90]
Is there a way to access the array of XAxis values determined by scaleTime in order to create vertical lines in a custom renderGrid? Ive created an example (by mashing the XAxis scaleTime and CustomGrid examples) that shows the issue Im trying to work around. I'd like to have the XAxis legend values line up with the vertical lines Im creating in the CustomGrid.

    import React from 'react'
    import { LineChart, XAxis } from 'react-native-svg-charts'
    import { View } from 'react-native'
    import { G, Line } from 'react-native-svg'
    import dateFns from 'date-fns'
    import * as scale from 'd3-scale'

    class CustomGridExample extends React.PureComponent {

        render() {

            const data = [
                {
                    value: 50,
                    date: dateFns.setHours(new Date(2018, 0, 0), 1),
                  },
                  {
                      value: 10,
                      date: dateFns.setHours(new Date(2018, 0, 0), 9),
                  },
                  {
                      value: 150,
                      date: dateFns.setHours(new Date(2018, 0, 0), 10),
                  },
                  {
                     value: 10,
                      date: dateFns.setHours(new Date(2018, 0, 0), 13),
                  },
                  {
                      value: 100,
                     date: dateFns.setHours(new Date(2018, 0, 0), 21),
                  },
                  {
                      value: 20,
                      date: dateFns.setHours(new Date(2018, 0, 0), 24),
                  },
                  {
                      value: 115,
                      date: dateFns.setHours(new Date(2018, 0, 0), 32),
                  },
                  {
                     value: 75,
                      date: dateFns.setHours(new Date(2018, 0, 0), 34),
                  },
                  {
                      value: 25,
                      date: dateFns.setHours(new Date(2018, 0, 0), 40),
                 },
                  {
                      value: 125,
                      date: dateFns.setHours(new Date(2018, 0, 0), 41),
                  },
                  {
                      value: 66,
                      date: dateFns.setHours(new Date(2018, 0, 0), 42),
                  },
                  {
                      value: 85,
                      date: dateFns.setHours(new Date(2018, 0, 0), 50),
                  },
              ]

              const CustomGrid = ({ x, y, data, ticks }) => (
                  <G>
                      {
                          // Horizontal grid
                          ticks.map(tick => (
                              <Line
                                  key={ tick }
                                  x1={ '0%' }
                                  x2={ '100%' }
                                  y1={ y(tick) }
                                  y2={ y(tick) }
                                  stroke={ 'rgba(0,0,0,0.2)' }
                              />
                          ))
                      }
                      {
                          // Vertical grid
                          data.map((item, index) => (
                              <Line
                                  key={ index }
                                  y1={ '0%' }
                                  y2={ '100%' }
                                 x1={ x(item.date) }
                                  x2={ x(item.date) }
                                  stroke={ 'rgba(0,0,0,0.2)' }
                              />
                          ))
                      }
                  </G>
              )

              return (
                  <View style={ { height: 200, padding: 20 } }>
                      <LineChart
                          style={ { flex: 1 } }
                          data={ data }
                          yAccessor={({ item }) => item.value}
                          xAccessor={({ item }) => item.date}
                          xScale={scale.scaleTime}
                          svg={ {
                              stroke: 'rgb(134, 65, 244)',
                          } }
                          renderGrid={ CustomGrid }
                      />
                      <XAxis
                        data={data}
                        svg={{
                            fill: 'black',
                            fontSize: 8,
                            fontWeight: 'bold',
                            rotation: 20,
                            originY: 30,
                            y: 5,
                        }}
                        xAccessor={({ item }) => item.date}
                        scale={scale.scaleTime}
                        numberOfTicks={6}
                        style={{ marginHorizontal: -15, height: 20 }}
                        contentInset={{ left: 10, right: 25 }}
                        formatLabel={(value) => dateFns.format(value, 'HH:mm')}
                      />
                  </View>
              )
          }

      }

      export default CustomGridExample

**Comment by ChrisBrinton** [comment]
Additionally, is the numberOfTicks on XAxis a hint rather than a firm value? The above code yields the below chart with 8 XAxis ticks.

![untitled](https://user-images.githubusercontent.com/18555846/37620163-d4ad1b16-2b91-11e8-95c0-256c86c6b942.png)

**Comment by msevestre** [comment]
@ChrisBrinton Indeed looks very similar.
Do you have any insights as to what the `originY` value means? You set it to `30` in your example. I am trying to find a rational as to what it means but I was not successful so far...

**Comment by msevestre** [comment]
Also the `marginHorizontal: -15` is also somewhat unclear to me. It seems that axis position and labels are not related whatsoever. How can we ensure that we do not shift the axis too much to the left or right?

**Comment by JesperLekland** [comment]
Hi guys! In this particular use case you can use the d3scale.scaleTime in the grid calculation.
Without digging too deep I think you could do something like this 

```javascript
 const CustomGrid = ({ x, y, data, ticks, width }) => {
   
  const xTicks = d3Scale.scaleTime()
          .domain(data)
          .range(leftInset, width - rightInset)

  // xTicks should now be the same ticks as for the xAxis
    return (
              <G>
                  {
                      // Horizontal grid
                      ticks.map(tick => (
                          <Line
                              key={ tick }
                              x1={ '0%' }
                              x2={ '100%' }
                              y1={ y(tick) }
                              y2={ y(tick) }
                              stroke={ 'rgba(0,0,0,0.2)' }
                          />
                      ))
                  }
                  {
                      // Vertical grid
                      xTicks.map((date, index) => (
                          <Line
                              key={ index }
                              y1={ '0%' }
                              y2={ '100%' }
                             x1={ x(date) }
                              x2={ x(date) }
                              stroke={ 'rgba(0,0,0,0.2)' }
                          />
                      ))
                  }
              </G>
          )
})
```

**Comment by JesperLekland** [comment]
The above is just something I threw together to offer inspiration, hopefully it helps you. 
Regarding the `numberOfTicks` it is indeed a suggestion. Read up on the calculation [here](https://github.com/d3/d3-scale#time_ticks), this is the de facto standard of tick calculation

**Comment by ChrisBrinton** [comment]
Thanks Jesper, that was just the pointer I needed. I was able to get it working close enough to the way that I wanted. For completeness, here is the code for the above example corrected to work properly.

    import React from 'react'
    import { LineChart, XAxis } from 'react-native-svg-charts'
    import { View } from 'react-native'
    import { G, Line } from 'react-native-svg'
    import dateFns from 'date-fns'
    import * as scale from 'd3-scale'

    class CustomGridExample extends React.PureComponent {

        render() {

            const data = [
                {
                    value: 50,
                    date: dateFns.setHours(new Date(2018, 0, 0), 1),
                },
                {
                   value: 10,
                    date: dateFns.setHours(new Date(2018, 0, 0), 9),
                },
                {
                    value: 150,
                    date: dateFns.setHours(new Date(2018, 0, 0), 10),
                },
                {
                    value: 10,
                    date: dateFns.setHours(new Date(2018, 0, 0), 13),
                },
                {
                    value: 100,
                    date: dateFns.setHours(new Date(2018, 0, 0), 21),
                },
                {
                    value: 20,
                    date: dateFns.setHours(new Date(2018, 0, 0), 24),
                },
                {
                    value: 115,
                    date: dateFns.setHours(new Date(2018, 0, 0), 32),
                },
                {
                    value: 75,
                    date: dateFns.setHours(new Date(2018, 0, 0), 34),
                },
                {
                    value: 25,
                    date: dateFns.setHours(new Date(2018, 0, 0), 40),
                },
                {
                    value: 125,
                    date: dateFns.setHours(new Date(2018, 0, 0), 41),
                },
                {
                    value: 66,
                    date: dateFns.setHours(new Date(2018, 0, 0), 42),
                },
                {
                    value: 85,
                    date: dateFns.setHours(new Date(2018, 0, 0), 50),
                },
            ]

            const CustomGrid = ({ x, y, data, ticks, width }) => {

              const xValues = data.map((item, index) => item.date)
              const xTicks = scale.scaleTime()
                      .domain(xValues)
                      .ticks(10)

              console.log(xTicks)

              return (
                <G>
                    {
                        // Horizontal grid
                        ticks.map(tick => (
                            <Line
                                key={ tick }
                               x1={ '0%' }
                                x2={ '100%' }
                                y1={ y(tick) }
                               y2={ y(tick) }
                                stroke={ 'rgba(0,0,0,0.2)' }
                            />
                        ))
                    }
                    {
                        // Vertical grid
                        xTicks.map((value, index) => {
                            console.log('x', x(value))
                            return (
                              <Line
                                  key={ index }
                                  y1={ '0%' }
                                  y2={ '100%' }
                                  x1={ x(value) }
                                  x2={ x(value) }
                                  stroke={ 'rgba(0,0,0,0.2)' }
                              />
                            )
                        })
                    }
                </G>
              )
            }

            return (
               <View style={ { height: 200, padding: 20 } }>
                    <LineChart
                       style={ { flex: 1 } }
                        data={ data }
                        yAccessor={({ item }) => item.value}
                        xAccessor={({ item }) => item.date}
                        contentInset={{ left: 10, right: 25 }}
                        xScale={scale.scaleTime}
                        numberOfTicks={10}
                        svg={ {
                            stroke: 'rgb(134, 65, 244)',
                        } }
                        renderGrid={ CustomGrid }
                    />
                    <XAxis
                      data={data}
                      svg={{
                          fill: 'black',
                          fontSize: 8,
                          fontWeight: 'bold',
                          rotation: 20,
                          originY: 30,
                         y: 5,
                      }}
                      xAccessor={({ item }) => item.date}
                      scale={scale.scaleTime}
                      numberOfTicks={10}
                      style={{ marginHorizontal: -15, height: 20 }}
                      contentInset={{ left: 15, right: 45 }}
                      formatLabel={(value) => dateFns.format(value, 'HH:mm')}
                    />
                </View>
            )
        }

    }

    export default CustomGridExample

Which produces this output:
![image](https://user-images.githubusercontent.com/18555846/37671042-342a3f7e-2c41-11e8-94d4-703862f5d291.png)


Interestingly (and confusingly) I couldnt get the range method to alter the behavior of the d3Scale results, so I dropped it. I will look into that a bit more I think.

@msevestre - I dont have a reason for setting originY and marginHorizonal the way they are, I was just copying from the examples in the storybook.
