### ISSUE TITLE
Decorator is drawn under extras

### ISSUE THREAD

**Issue by ittna** [JesperLekland/react-native-svg-charts#93]
I have AreaChart which draws line with extras and renderDecorator which draws circles. Circles appear to be under the line. Is it possible to somehow change the order?

**Comment by ittna** [comment]
![screen shot 2018-03-24 at 16 39 22](https://user-images.githubusercontent.com/2304597/37865221-0efa23ec-2f82-11e8-954c-882d4b498c6e.png)

**Comment by ittna** [comment]
I guess as workaround I could use LineChart to draw lines and decorator instead of using extras.

**Comment by JesperLekland** [comment]
Yeah that should definitely be supported. I'll try to figure something out. Thanks for reporting 👍

**Comment by Neha3011** [comment]
@ittna Were you able to figure out workaround for this? I am facing the same issue. It would be really helpful if you can help me out, have been stuck on this for a while. Thanks

**Comment by JesperLekland** [comment]
I haven't had time to look at it yet unfortunately. I'll give it a go as soon as I can but in the meantime I'd love a PR

**Comment by JesperLekland** [comment]
Fixed in 5.0.0
