### ISSUE TITLE
XAxis not rendering with array of strings

### ISSUE THREAD

**Issue by emretekince** [JesperLekland/react-native-svg-charts#98]
### What platform?
 Android 8

React Native version: 0.54.4

### Code to reproduce

```javascript
<XAxis
   style={{height: 18}}
   data={["asd", "dasd", "dasd"]}
   xAccessor={({ item  }) => item }
/>
```
![screenshot_2](https://user-images.githubusercontent.com/5754074/38164790-532c05fe-3512-11e8-99b4-9c231697c0b0.png)

But it renders when change data to array of numbers like [1,2,3]

![screenshot_3](https://user-images.githubusercontent.com/5754074/38164925-a0b6fd04-3514-11e8-9504-e28e6b5efa9a.png)

**Comment by JesperLekland** [comment]
How would it possibly distribute just strings along an axis? What is the data extent?.. See the examples repo for inspiration. Please read the README and put in a little effort to understand how a library works  before posting issues
